# Form implementation generated from reading ui file '/home/joe/Projects/imagetopixel/airunner/src/airunner/../../src/airunner/windows/prompt_browser/templates/prompt_browser.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_prompt_browser(object):
    def setupUi(self, prompt_browser):
        prompt_browser.setObjectName("prompt_browser")
        prompt_browser.resize(768, 597)
        self.gridLayout_2 = QtWidgets.QGridLayout(prompt_browser)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(parent=prompt_browser)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 748, 577))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_2.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(prompt_browser)
        QtCore.QMetaObject.connectSlotsByName(prompt_browser)

    def retranslateUi(self, prompt_browser):
        _translate = QtCore.QCoreApplication.translate
        prompt_browser.setWindowTitle(_translate("prompt_browser", "Prompt Browser"))
