# Form implementation generated from reading ui file '/home/joe/Projects/imagetopixel/airunner/src/airunner/../../src/airunner/widgets/breadcrumbs/templates/breadcrumb.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_breadcrumb_widget(object):
    def setupUi(self, breadcrumb_widget):
        breadcrumb_widget.setObjectName("breadcrumb_widget")
        breadcrumb_widget.resize(310, 25)
        self.horizontalLayout = QtWidgets.QHBoxLayout(breadcrumb_widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.home_button = QtWidgets.QPushButton(parent=breadcrumb_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.home_button.sizePolicy().hasHeightForWidth())
        self.home_button.setSizePolicy(sizePolicy)
        self.home_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.home_button.setText("")
        icon = QtGui.QIcon.fromTheme("go-home")
        self.home_button.setIcon(icon)
        self.home_button.setObjectName("home_button")
        self.horizontalLayout.addWidget(self.home_button)
        self.button = QtWidgets.QPushButton(parent=breadcrumb_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button.sizePolicy().hasHeightForWidth())
        self.button.setSizePolicy(sizePolicy)
        self.button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.button.setText("")
        self.button.setObjectName("button")
        self.horizontalLayout.addWidget(self.button)
        self.slash = QtWidgets.QLabel(parent=breadcrumb_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.slash.sizePolicy().hasHeightForWidth())
        self.slash.setSizePolicy(sizePolicy)
        self.slash.setMinimumSize(QtCore.QSize(20, 0))
        self.slash.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.slash.setObjectName("slash")
        self.horizontalLayout.addWidget(self.slash)

        self.retranslateUi(breadcrumb_widget)
        self.home_button.clicked.connect(breadcrumb_widget.breadcrumb_clicked) # type: ignore
        self.button.clicked.connect(breadcrumb_widget.breadcrumb_clicked) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(breadcrumb_widget)

    def retranslateUi(self, breadcrumb_widget):
        _translate = QtCore.QCoreApplication.translate
        breadcrumb_widget.setWindowTitle(_translate("breadcrumb_widget", "Form"))
        self.slash.setText(_translate("breadcrumb_widget", "/"))
