# Form implementation generated from reading ui file '/home/joe/Projects/imagetopixel/airunner/src/airunner/widgets/translation_preferences/templates/translation_preferences_widget.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_translation_preferences(object):
    def setupUi(self, translation_preferences):
        translation_preferences.setObjectName("translation_preferences")
        translation_preferences.resize(390, 379)
        self.gridLayout = QtWidgets.QGridLayout(translation_preferences)
        self.gridLayout.setObjectName("gridLayout")
        self.translate_groupbox = QtWidgets.QGroupBox(parent=translation_preferences)
        self.translate_groupbox.setCheckable(True)
        self.translate_groupbox.setObjectName("translate_groupbox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.translate_groupbox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_5 = QtWidgets.QLabel(parent=self.translate_groupbox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 13, 0, 1, 1)
        self.line = QtWidgets.QFrame(parent=self.translate_groupbox)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_3.addWidget(self.line, 3, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.translate_groupbox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(parent=self.translate_groupbox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 14, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.translate_groupbox)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 5, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(parent=self.translate_groupbox)
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_3.addWidget(self.line_2, 12, 0, 1, 1)
        self.language_combobox = QtWidgets.QComboBox(parent=self.translate_groupbox)
        self.language_combobox.setObjectName("language_combobox")
        self.gridLayout_3.addWidget(self.language_combobox, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.translate_groupbox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.translate_groupbox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 4, 0, 1, 1)
        self.translation_model_combobox = QtWidgets.QComboBox(parent=self.translate_groupbox)
        self.translation_model_combobox.setObjectName("translation_model_combobox")
        self.gridLayout_3.addWidget(self.translation_model_combobox, 15, 0, 1, 1)
        self.voice_combobox = QtWidgets.QComboBox(parent=self.translate_groupbox)
        self.voice_combobox.setObjectName("voice_combobox")
        self.gridLayout_3.addWidget(self.voice_combobox, 6, 0, 1, 1)
        self.horizontalWidget = QtWidgets.QWidget(parent=self.translate_groupbox)
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.formLayout = QtWidgets.QFormLayout(self.horizontalWidget)
        self.formLayout.setObjectName("formLayout")
        self.female_radio_button = QtWidgets.QRadioButton(parent=self.horizontalWidget)
        self.female_radio_button.setObjectName("female_radio_button")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.female_radio_button)
        self.male_radio_button = QtWidgets.QRadioButton(parent=self.horizontalWidget)
        self.male_radio_button.setObjectName("male_radio_button")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.male_radio_button)
        self.gridLayout_3.addWidget(self.horizontalWidget, 8, 0, 1, 1)
        self.gridLayout.addWidget(self.translate_groupbox, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)

        self.retranslateUi(translation_preferences)
        self.language_combobox.currentTextChanged['QString'].connect(translation_preferences.language_text_changed) # type: ignore
        self.translate_groupbox.toggled['bool'].connect(translation_preferences.toggle_translation) # type: ignore
        self.translation_model_combobox.currentTextChanged['QString'].connect(translation_preferences.translation_model_changed) # type: ignore
        self.female_radio_button.clicked.connect(translation_preferences.female_clicked) # type: ignore
        self.male_radio_button.clicked.connect(translation_preferences.male_clicked) # type: ignore
        self.voice_combobox.currentTextChanged['QString'].connect(translation_preferences.voice_text_changed) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(translation_preferences)

    def retranslateUi(self, translation_preferences):
        _translate = QtCore.QCoreApplication.translate
        translation_preferences.setWindowTitle(_translate("translation_preferences", "Form"))
        self.translate_groupbox.setTitle(_translate("translation_preferences", "Translate"))
        self.label_5.setText(_translate("translation_preferences", "Translation model"))
        self.label_4.setText(_translate("translation_preferences", "Your preferred language"))
        self.label_6.setText(_translate("translation_preferences", "This model will be used to translate"))
        self.label.setText(_translate("translation_preferences", "Override TTS voice model"))
        self.label_3.setText(_translate("translation_preferences", "Language"))
        self.label_2.setText(_translate("translation_preferences", "Voice"))
        self.female_radio_button.setText(_translate("translation_preferences", "Female"))
        self.male_radio_button.setText(_translate("translation_preferences", "Male"))
