# Form implementation generated from reading ui file '/home/joe/Projects/imagetopixel/airunner/src/airunner/../../src/airunner/widgets/deterministic/templates/deterministic_widget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_deterministic_widget(object):
    def setupUi(self, deterministic_widget):
        deterministic_widget.setObjectName("deterministic_widget")
        deterministic_widget.resize(322, 256)
        deterministic_widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(8)
        deterministic_widget.setFont(font)
        self.gridLayout_4 = QtWidgets.QGridLayout(deterministic_widget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scrollArea = QtWidgets.QScrollArea(parent=deterministic_widget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 302, 236))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.category = QtWidgets.QComboBox(parent=self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.category.setFont(font)
        self.category.setObjectName("category")
        self.gridLayout_3.addWidget(self.category, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 2, 0, 1, 1)
        self.line = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 1, 0, 1, 1)
        self.deterministic_seed = SeedWidget(parent=self.scrollAreaWidgetContents)
        self.deterministic_seed.setObjectName("deterministic_seed")
        self.gridLayout_2.addWidget(self.deterministic_seed, 4, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(parent=self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.images_per_batch = QtWidgets.QSpinBox(parent=self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        self.images_per_batch.setFont(font)
        self.images_per_batch.setMinimum(1)
        self.images_per_batch.setMaximum(16)
        self.images_per_batch.setProperty("value", 4)
        self.images_per_batch.setObjectName("images_per_batch")
        self.gridLayout.addWidget(self.images_per_batch, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 3, 0, 1, 1)
        self.generate_batches_button = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.generate_batches_button.setFont(font)
        self.generate_batches_button.setObjectName("generate_batches_button")
        self.gridLayout_2.addWidget(self.generate_batches_button, 5, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 7, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 6, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_4.addWidget(self.scrollArea, 0, 0, 1, 1)

        self.retranslateUi(deterministic_widget)
        self.category.currentTextChanged['QString'].connect(deterministic_widget.action_text_changed_category) # type: ignore
        self.images_per_batch.valueChanged['int'].connect(deterministic_widget.action_value_changed_images_per_batch) # type: ignore
        self.generate_batches_button.clicked.connect(deterministic_widget.action_clicked_button_generate_batch) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(deterministic_widget)

    def retranslateUi(self, deterministic_widget):
        _translate = QtCore.QCoreApplication.translate
        deterministic_widget.setWindowTitle(_translate("deterministic_widget", "Form"))
        self.groupBox_2.setTitle(_translate("deterministic_widget", "Cateogry"))
        self.label.setText(_translate("deterministic_widget", "Deterministic generation"))
        self.groupBox.setTitle(_translate("deterministic_widget", "Images per-batch"))
        self.generate_batches_button.setText(_translate("deterministic_widget", "Generate Deterministic Batch"))
from airunner.widgets.seed.seed_widget import SeedWidget
