# Form implementation generated from reading ui file '/home/joe/Projects/imagetopixel/airunner/src/airunner/../../src/airunner/pyqt/widgets/embeddings/embeddings_container.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_embeddings_container(object):
    def setupUi(self, embeddings_container):
        embeddings_container.setObjectName("embeddings_container")
        embeddings_container.resize(583, 771)
        self.gridLayout = QtWidgets.QGridLayout(embeddings_container)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.embeddings = QtWidgets.QScrollArea(parent=embeddings_container)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.embeddings.setFont(font)
        self.embeddings.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.embeddings.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.embeddings.setWidgetResizable(True)
        self.embeddings.setObjectName("embeddings")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 583, 771))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.embeddings.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout.addWidget(self.embeddings, 0, 0, 1, 1)

        self.retranslateUi(embeddings_container)
        QtCore.QMetaObject.connectSlotsByName(embeddings_container)

    def retranslateUi(self, embeddings_container):
        _translate = QtCore.QCoreApplication.translate
        embeddings_container.setWindowTitle(_translate("embeddings_container", "Form"))
