version: "3.6"
services:
  windows_prod:
    restart: always
    container_name: airunner_windows
    image: ghcr.io/capsize-games/airunner/airunner:windows
    user: root
    build:
      context: ./
      dockerfile: ./windows.Dockerfile
    environment:
      - DEV_ENV=1
      - AIRUNNER_ENVIRONMENT=dev
      - AIRUNNER_OS=windows
      - PYTORCH_CUDA_ALLOC_CONF=garbage_collection_threshold:0.9,max_split_size_mb:512
      - NUMBA_CACHE_DIR=/tmp/numba_cache
      - LD_LIBRARY_PATH=/home/.wine-win10/drive_c/Program\ Files/NVIDIA\ GPU\ Computing\ Toolkit/CUDA/v11.7/lib/x64
      - DISABLE_TELEMETRY=1
