# Form implementation generated from reading ui file '/home/joe/Projects/imagetopixel/airunner/src/airunner/windows/settings/templates/airunner_settings.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_airunner_settings(object):
    def setupUi(self, airunner_settings):
        airunner_settings.setObjectName("airunner_settings")
        airunner_settings.resize(1014, 726)
        self.gridLayout = QtWidgets.QGridLayout(airunner_settings)
        self.gridLayout.setObjectName("gridLayout")
        self.directory = QtWidgets.QTreeView(parent=airunner_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.directory.sizePolicy().hasHeightForWidth())
        self.directory.setSizePolicy(sizePolicy)
        self.directory.setMinimumSize(QtCore.QSize(300, 0))
        self.directory.setObjectName("directory")
        self.gridLayout.addWidget(self.directory, 0, 0, 1, 1)
        self.preferences = QtWidgets.QScrollArea(parent=airunner_settings)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.preferences.sizePolicy().hasHeightForWidth())
        self.preferences.setSizePolicy(sizePolicy)
        self.preferences.setMinimumSize(QtCore.QSize(350, 0))
        self.preferences.setWidgetResizable(True)
        self.preferences.setObjectName("preferences")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 688, 706))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.preferences.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout.addWidget(self.preferences, 0, 1, 1, 1)

        self.retranslateUi(airunner_settings)
        QtCore.QMetaObject.connectSlotsByName(airunner_settings)

    def retranslateUi(self, airunner_settings):
        _translate = QtCore.QCoreApplication.translate
        airunner_settings.setWindowTitle(_translate("airunner_settings", "AI Runner Settings"))
