# Form implementation generated from reading ui file '/home/joe/Projects/imagetopixel/airunner/src/airunner/../../src/airunner/widgets/batch/templates/batch_widget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_batch_widget(object):
    def setupUi(self, batch_widget):
        batch_widget.setObjectName("batch_widget")
        batch_widget.resize(322, 137)
        batch_widget.setMaximumSize(QtCore.QSize(16777215, 137))
        font = QtGui.QFont()
        font.setPointSize(8)
        batch_widget.setFont(font)
        self.gridLayout_2 = QtWidgets.QGridLayout(batch_widget)
        self.gridLayout_2.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=batch_widget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.total_batches = QtWidgets.QSpinBox(parent=self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        self.total_batches.setFont(font)
        self.total_batches.setMinimum(1)
        self.total_batches.setMaximum(500)
        self.total_batches.setObjectName("total_batches")
        self.gridLayout_3.addWidget(self.total_batches, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 3, 0, 1, 1)
        self.generate_batches_button = QtWidgets.QPushButton(parent=batch_widget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.generate_batches_button.setFont(font)
        self.generate_batches_button.setObjectName("generate_batches_button")
        self.gridLayout_2.addWidget(self.generate_batches_button, 4, 0, 1, 2)
        self.groupBox = QtWidgets.QGroupBox(parent=batch_widget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.images_per_batch = QtWidgets.QSpinBox(parent=self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        self.images_per_batch.setFont(font)
        self.images_per_batch.setMinimum(1)
        self.images_per_batch.setMaximum(34)
        self.images_per_batch.setObjectName("images_per_batch")
        self.gridLayout.addWidget(self.images_per_batch, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=batch_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 1)
        self.line = QtWidgets.QFrame(parent=batch_widget)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 2, 0, 1, 2)

        self.retranslateUi(batch_widget)
        QtCore.QMetaObject.connectSlotsByName(batch_widget)

    def retranslateUi(self, batch_widget):
        _translate = QtCore.QCoreApplication.translate
        batch_widget.setWindowTitle(_translate("batch_widget", "Form"))
        self.groupBox_2.setTitle(_translate("batch_widget", "Batches"))
        self.generate_batches_button.setText(_translate("batch_widget", "Generate batches"))
        self.groupBox.setTitle(_translate("batch_widget", "Images per batch"))
        self.label.setText(_translate("batch_widget", "Batch Generation"))
