# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGridLayout, QHBoxLayout,
    QMainWindow, QMenu, QMenuBar, QPushButton,
    QSizePolicy, QSpacerItem, QSplitter, QStatusBar,
    QVBoxLayout, QWidget)

from airunner.widgets.canvas.canvas_widget import CanvasWidget
from airunner.widgets.generator_form.generator_form_widget import GeneratorForm
from airunner.widgets.tool_tab.tool_tab_widget import ToolTabWidget
import airunner.resources_light_rc
import airunner.resources_dark_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1304, 829)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(0, 0))
        font = QFont()
        font.setPointSize(8)
        MainWindow.setFont(font)
        icon = QIcon()
        icon.addFile(u":/icons/icon_256.png", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(u"")
        self.actionNew = QAction(MainWindow)
        self.actionNew.setObjectName(u"actionNew")
        self.actionImport = QAction(MainWindow)
        self.actionImport.setObjectName(u"actionImport")
        self.actionExport = QAction(MainWindow)
        self.actionExport.setObjectName(u"actionExport")
        self.actionCopy = QAction(MainWindow)
        self.actionCopy.setObjectName(u"actionCopy")
        self.actionPaste = QAction(MainWindow)
        self.actionPaste.setObjectName(u"actionPaste")
        self.actionUndo = QAction(MainWindow)
        self.actionUndo.setObjectName(u"actionUndo")
        icon1 = QIcon()
        icon1.addFile(u"../../../../../../../../../../../../../../.designer/src/icons/007-undo.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionUndo.setIcon(icon1)
        self.actionRedo = QAction(MainWindow)
        self.actionRedo.setObjectName(u"actionRedo")
        icon2 = QIcon()
        icon2.addFile(u"../../../../../../../../../../../../../../.designer/src/icons/008-redo.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionRedo.setIcon(icon2)
        self.actionGrid = QAction(MainWindow)
        self.actionGrid.setObjectName(u"actionGrid")
        self.actionPreferences = QAction(MainWindow)
        self.actionPreferences.setObjectName(u"actionPreferences")
        self.actionCanvas_color = QAction(MainWindow)
        self.actionCanvas_color.setObjectName(u"actionCanvas_color")
        self.actionReset_Settings = QAction(MainWindow)
        self.actionReset_Settings.setObjectName(u"actionReset_Settings")
        self.actionResize_on_Paste = QAction(MainWindow)
        self.actionResize_on_Paste.setObjectName(u"actionResize_on_Paste")
        self.actionResize_on_Paste.setCheckable(True)
        self.actionMemory = QAction(MainWindow)
        self.actionMemory.setObjectName(u"actionMemory")
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionCheck_for_updates = QAction(MainWindow)
        self.actionCheck_for_updates.setObjectName(u"actionCheck_for_updates")
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        self.actionView = QAction(MainWindow)
        self.actionView.setObjectName(u"actionView")
        self.actionAdvanced = QAction(MainWindow)
        self.actionAdvanced.setObjectName(u"actionAdvanced")
        self.actionGaussian_Blur = QAction(MainWindow)
        self.actionGaussian_Blur.setObjectName(u"actionGaussian_Blur")
        self.actionGaussian_Blur.setEnabled(True)
        self.actionBox_Blur = QAction(MainWindow)
        self.actionBox_Blur.setObjectName(u"actionBox_Blur")
        self.actionUnsharp_Mask = QAction(MainWindow)
        self.actionUnsharp_Mask.setObjectName(u"actionUnsharp_Mask")
        self.actionPixel_Art = QAction(MainWindow)
        self.actionPixel_Art.setObjectName(u"actionPixel_Art")
        self.actionPixel_Art.setVisible(True)
        self.actionInvert = QAction(MainWindow)
        self.actionInvert.setObjectName(u"actionInvert")
        self.actionSaturation = QAction(MainWindow)
        self.actionSaturation.setObjectName(u"actionSaturation")
        self.actionSaturation.setVisible(True)
        self.actionColor_Balance = QAction(MainWindow)
        self.actionColor_Balance.setObjectName(u"actionColor_Balance")
        self.actionColor_Balance.setCheckable(False)
        self.actionColor_Balance.setEnabled(True)
        self.actionColor_Balance.setVisible(True)
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.actionLoad = QAction(MainWindow)
        self.actionLoad.setObjectName(u"actionLoad")
        self.actionQuit = QAction(MainWindow)
        self.actionQuit.setObjectName(u"actionQuit")
        self.actionPixel_Art_2 = QAction(MainWindow)
        self.actionPixel_Art_2.setObjectName(u"actionPixel_Art_2")
        self.actionBug_report = QAction(MainWindow)
        self.actionBug_report.setObjectName(u"actionBug_report")
        self.actionReport_vulnerability = QAction(MainWindow)
        self.actionReport_vulnerability.setObjectName(u"actionReport_vulnerability")
        self.actionDiscord = QAction(MainWindow)
        self.actionDiscord.setObjectName(u"actionDiscord")
        self.actionExtensions = QAction(MainWindow)
        self.actionExtensions.setObjectName(u"actionExtensions")
        self.actionShow_image_preview = QAction(MainWindow)
        self.actionShow_image_preview.setObjectName(u"actionShow_image_preview")
        self.actionShow_image_preview.setCheckable(True)
        self.actionImage_to_new_layer = QAction(MainWindow)
        self.actionImage_to_new_layer.setObjectName(u"actionImage_to_new_layer")
        self.actionImage_to_new_layer.setCheckable(True)
        self.actionAuto_export_images = QAction(MainWindow)
        self.actionAuto_export_images.setObjectName(u"actionAuto_export_images")
        self.actionAuto_export_images.setCheckable(True)
        self.actionImage_export_settings = QAction(MainWindow)
        self.actionImage_export_settings.setObjectName(u"actionImage_export_settings")
        self.actionCheck_for_latest_version_on_startup = QAction(MainWindow)
        self.actionCheck_for_latest_version_on_startup.setObjectName(u"actionCheck_for_latest_version_on_startup")
        self.actionCheck_for_latest_version_on_startup.setCheckable(True)
        self.actionModel_Merger = QAction(MainWindow)
        self.actionModel_Merger.setObjectName(u"actionModel_Merger")
        self.actionSaturation_Filter = QAction(MainWindow)
        self.actionSaturation_Filter.setObjectName(u"actionSaturation_Filter")
        self.actionColor_Balance_2 = QAction(MainWindow)
        self.actionColor_Balance_2.setObjectName(u"actionColor_Balance_2")
        self.actionRGB_Noise = QAction(MainWindow)
        self.actionRGB_Noise.setObjectName(u"actionRGB_Noise")
        self.actionGaussian_Blur_2 = QAction(MainWindow)
        self.actionGaussian_Blur_2.setObjectName(u"actionGaussian_Blur_2")
        self.actionBox_Blur_2 = QAction(MainWindow)
        self.actionBox_Blur_2.setObjectName(u"actionBox_Blur_2")
        self.actionRotate_90_clockwise = QAction(MainWindow)
        self.actionRotate_90_clockwise.setObjectName(u"actionRotate_90_clockwise")
        self.actionRotate_90_counter_clockwise = QAction(MainWindow)
        self.actionRotate_90_counter_clockwise.setObjectName(u"actionRotate_90_counter_clockwise")
        self.actionSave_prompt = QAction(MainWindow)
        self.actionSave_prompt.setObjectName(u"actionSave_prompt")
        self.actionShow_Active_Image_Area = QAction(MainWindow)
        self.actionShow_Active_Image_Area.setObjectName(u"actionShow_Active_Image_Area")
        self.actionShow_Active_Image_Area.setCheckable(True)
        self.actionImage_Interpolation = QAction(MainWindow)
        self.actionImage_Interpolation.setObjectName(u"actionImage_Interpolation")
        self.actionImage_interpolation = QAction(MainWindow)
        self.actionImage_interpolation.setObjectName(u"actionImage_interpolation")
        self.actionFilm = QAction(MainWindow)
        self.actionFilm.setObjectName(u"actionFilm")
        self.actionDeterministic_generation = QAction(MainWindow)
        self.actionDeterministic_generation.setObjectName(u"actionDeterministic_generation")
        self.actionDark_mode = QAction(MainWindow)
        self.actionDark_mode.setObjectName(u"actionDark_mode")
        self.actionDark_mode.setCheckable(True)
        self.actionConsole_window = QAction(MainWindow)
        self.actionConsole_window.setObjectName(u"actionConsole_window")
        self.actionPrompt_Browser = QAction(MainWindow)
        self.actionPrompt_Browser.setObjectName(u"actionPrompt_Browser")
        self.actionClear_all_prompts = QAction(MainWindow)
        self.actionClear_all_prompts.setObjectName(u"actionClear_all_prompts")
        self.actionUndo_2 = QAction(MainWindow)
        self.actionUndo_2.setObjectName(u"actionUndo_2")
        self.actionUndo_2.setIcon(icon1)
        self.actionRedo_2 = QAction(MainWindow)
        self.actionRedo_2.setObjectName(u"actionRedo_2")
        self.actionRedo_2.setIcon(icon2)
        self.actionCut = QAction(MainWindow)
        self.actionCut.setObjectName(u"actionCut")
        self.actionHalftone = QAction(MainWindow)
        self.actionHalftone.setObjectName(u"actionHalftone")
        self.actionQuick_Export = QAction(MainWindow)
        self.actionQuick_Export.setObjectName(u"actionQuick_Export")
        self.actionRegistration_error = QAction(MainWindow)
        self.actionRegistration_error.setObjectName(u"actionRegistration_error")
        self.actionHuggingface_Cache_manager = QAction(MainWindow)
        self.actionHuggingface_Cache_manager.setObjectName(u"actionHuggingface_Cache_manager")
        self.actionModel_Manager = QAction(MainWindow)
        self.actionModel_Manager.setObjectName(u"actionModel_Manager")
        self.actionModel_Manager_2 = QAction(MainWindow)
        self.actionModel_Manager_2.setObjectName(u"actionModel_Manager_2")
        self.actionControlNet = QAction(MainWindow)
        self.actionControlNet.setObjectName(u"actionControlNet")
        self.actionPrompt_Builder = QAction(MainWindow)
        self.actionPrompt_Builder.setObjectName(u"actionPrompt_Builder")
        self.actionEmbeddings = QAction(MainWindow)
        self.actionEmbeddings.setObjectName(u"actionEmbeddings")
        self.actionLoRA = QAction(MainWindow)
        self.actionLoRA.setObjectName(u"actionLoRA")
        self.actionPen = QAction(MainWindow)
        self.actionPen.setObjectName(u"actionPen")
        self.actionStableDiffusion = QAction(MainWindow)
        self.actionStableDiffusion.setObjectName(u"actionStableDiffusion")
        self.actionKandinsky = QAction(MainWindow)
        self.actionKandinsky.setObjectName(u"actionKandinsky")
        self.actionShap_E = QAction(MainWindow)
        self.actionShap_E.setObjectName(u"actionShap_E")
        self.actionRun_setup_wizard = QAction(MainWindow)
        self.actionRun_setup_wizard.setObjectName(u"actionRun_setup_wizard")
        self.actionBrowse_AI_Runner_Path = QAction(MainWindow)
        self.actionBrowse_AI_Runner_Path.setObjectName(u"actionBrowse_AI_Runner_Path")
        self.actionBrowse_Images_Path = QAction(MainWindow)
        self.actionBrowse_Images_Path.setObjectName(u"actionBrowse_Images_Path")
        self.actionBrowse_Images_Path_2 = QAction(MainWindow)
        self.actionBrowse_Images_Path_2.setObjectName(u"actionBrowse_Images_Path_2")
        self.actionBrowse_Gifs_Path = QAction(MainWindow)
        self.actionBrowse_Gifs_Path.setObjectName(u"actionBrowse_Gifs_Path")
        self.actionTxt2img_Img2img_Models = QAction(MainWindow)
        self.actionTxt2img_Img2img_Models.setObjectName(u"actionTxt2img_Img2img_Models")
        self.actionInpaint_Outpaint_Models = QAction(MainWindow)
        self.actionInpaint_Outpaint_Models.setObjectName(u"actionInpaint_Outpaint_Models")
        self.actionActive_Grid = QAction(MainWindow)
        self.actionActive_Grid.setObjectName(u"actionActive_Grid")
        self.actionDeterministic_Batches = QAction(MainWindow)
        self.actionDeterministic_Batches.setObjectName(u"actionDeterministic_Batches")
        self.actionStandard_Batches = QAction(MainWindow)
        self.actionStandard_Batches.setObjectName(u"actionStandard_Batches")
        self.actionLLM_beta = QAction(MainWindow)
        self.actionLLM_beta.setObjectName(u"actionLLM_beta")
        self.actionReset_Settings_2 = QAction(MainWindow)
        self.actionReset_Settings_2.setObjectName(u"actionReset_Settings_2")
        self.actionImage_Browser = QAction(MainWindow)
        self.actionImage_Browser.setObjectName(u"actionImage_Browser")
        self.actionModel_Manager_3 = QAction(MainWindow)
        self.actionModel_Manager_3.setObjectName(u"actionModel_Manager_3")
        self.actionImport_input_image = QAction(MainWindow)
        self.actionImport_input_image.setObjectName(u"actionImport_input_image")
        self.actionExport_input_image = QAction(MainWindow)
        self.actionExport_input_image.setObjectName(u"actionExport_input_image")
        self.actionImport_2 = QAction(MainWindow)
        self.actionImport_2.setObjectName(u"actionImport_2")
        self.actionExport_image = QAction(MainWindow)
        self.actionExport_image.setObjectName(u"actionExport_image")
        self.actionImport_Image = QAction(MainWindow)
        self.actionImport_Image.setObjectName(u"actionImport_Image")
        self.actionExport_Image = QAction(MainWindow)
        self.actionExport_Image.setObjectName(u"actionExport_Image")
        self.actionImport_3 = QAction(MainWindow)
        self.actionImport_3.setObjectName(u"actionImport_3")
        self.actionExport_2 = QAction(MainWindow)
        self.actionExport_2.setObjectName(u"actionExport_2")
        self.controlnet_import = QAction(MainWindow)
        self.controlnet_import.setObjectName(u"controlnet_import")
        self.controlnet_export = QAction(MainWindow)
        self.controlnet_export.setObjectName(u"controlnet_export")
        self.drawingpad_import = QAction(MainWindow)
        self.drawingpad_import.setObjectName(u"drawingpad_import")
        self.drawingpad_export = QAction(MainWindow)
        self.drawingpad_export.setObjectName(u"drawingpad_export")
        self.actionGenerate_while_drawing = QAction(MainWindow)
        self.actionGenerate_while_drawing.setObjectName(u"actionGenerate_while_drawing")
        self.actionGenerate_while_drawing.setCheckable(True)
        self.actionOverlay_input_image = QAction(MainWindow)
        self.actionOverlay_input_image.setObjectName(u"actionOverlay_input_image")
        self.actionOverlay_input_image.setCheckable(True)
        self.enable_controlnet = QAction(MainWindow)
        self.enable_controlnet.setObjectName(u"enable_controlnet")
        self.enable_controlnet.setCheckable(True)
        self.actionUnload_LLm = QAction(MainWindow)
        self.actionUnload_LLm.setObjectName(u"actionUnload_LLm")
        self.actionUnload_Image_model = QAction(MainWindow)
        self.actionUnload_Image_model.setObjectName(u"actionUnload_Image_model")
        self.actionClear_Memory = QAction(MainWindow)
        self.actionClear_Memory.setObjectName(u"actionClear_Memory")
        self.actionSafety_Checker = QAction(MainWindow)
        self.actionSafety_Checker.setObjectName(u"actionSafety_Checker")
        self.actionSafety_Checker.setCheckable(True)
        self.actionSafety_Checker.setChecked(False)
        self.outpaint_import = QAction(MainWindow)
        self.outpaint_import.setObjectName(u"outpaint_import")
        self.outpaint_export = QAction(MainWindow)
        self.outpaint_export.setObjectName(u"outpaint_export")
        self.outpaint_enabled = QAction(MainWindow)
        self.outpaint_enabled.setObjectName(u"outpaint_enabled")
        self.outpaint_enabled.setCheckable(True)
        self.actionModel_Manager_4 = QAction(MainWindow)
        self.actionModel_Manager_4.setObjectName(u"actionModel_Manager_4")
        self.actionRun_setup_wizard_2 = QAction(MainWindow)
        self.actionRun_setup_wizard_2.setObjectName(u"actionRun_setup_wizard_2")
        self.actionStats = QAction(MainWindow)
        self.actionStats.setObjectName(u"actionStats")
        self.actionSettings = QAction(MainWindow)
        self.actionSettings.setObjectName(u"actionSettings")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setEnabled(True)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QSize(0, 0))
        self.centralwidget.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.gridLayout_3 = QGridLayout(self.centralwidget)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.mode_tab_widget = QWidget(self.centralwidget)
        self.mode_tab_widget.setObjectName(u"mode_tab_widget")
        self.mode_tab_widget.setAutoFillBackground(False)
        self.mode_tab_widget.setStyleSheet(u"QTabWidget#mode_tab_widget::pane { border: 0; background: transparent; }")
        self.gridLayout = QGridLayout(self.mode_tab_widget)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.content_splitter = QSplitter(self.mode_tab_widget)
        self.content_splitter.setObjectName(u"content_splitter")
        self.content_splitter.setOrientation(Qt.Orientation.Horizontal)
        self.generator_widget = GeneratorForm(self.content_splitter)
        self.generator_widget.setObjectName(u"generator_widget")
        self.content_splitter.addWidget(self.generator_widget)
        self.canvas_widget = QWidget(self.content_splitter)
        self.canvas_widget.setObjectName(u"canvas_widget")
        self.canvas_widget.setMinimumSize(QSize(0, 0))
        self.gridLayout_2 = QGridLayout(self.canvas_widget)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.canvas_control_bar = QWidget(self.canvas_widget)
        self.canvas_control_bar.setObjectName(u"canvas_control_bar")
        sizePolicy.setHeightForWidth(self.canvas_control_bar.sizePolicy().hasHeightForWidth())
        self.canvas_control_bar.setSizePolicy(sizePolicy)
        self.canvas_control_bar.setMinimumSize(QSize(0, 0))
        self.canvas_control_bar.setMaximumSize(QSize(16777215, 16777215))
        self.horizontalLayout_5 = QHBoxLayout(self.canvas_control_bar)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.undo_button = QPushButton(self.canvas_control_bar)
        self.undo_button.setObjectName(u"undo_button")
        sizePolicy.setHeightForWidth(self.undo_button.sizePolicy().hasHeightForWidth())
        self.undo_button.setSizePolicy(sizePolicy)
        self.undo_button.setMinimumSize(QSize(0, 0))
        self.undo_button.setMaximumSize(QSize(16777215, 16777215))
        self.undo_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.undo_button.setStyleSheet(u"")
        icon3 = QIcon()
        iconThemeName = u"edit-undo"
        if QIcon.hasThemeIcon(iconThemeName):
            icon3 = QIcon.fromTheme(iconThemeName)
        else:
            icon3.addFile(u"../../../../../../../../../../../../../../.designer/backup", QSize(), QIcon.Normal, QIcon.Off)

        self.undo_button.setIcon(icon3)
        self.undo_button.setIconSize(QSize(15, 15))
        self.undo_button.setFlat(True)

        self.horizontalLayout_5.addWidget(self.undo_button)

        self.redo_button = QPushButton(self.canvas_control_bar)
        self.redo_button.setObjectName(u"redo_button")
        sizePolicy.setHeightForWidth(self.redo_button.sizePolicy().hasHeightForWidth())
        self.redo_button.setSizePolicy(sizePolicy)
        self.redo_button.setMinimumSize(QSize(0, 0))
        self.redo_button.setMaximumSize(QSize(16777215, 16777215))
        self.redo_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.redo_button.setStyleSheet(u"")
        icon4 = QIcon()
        iconThemeName = u"edit-redo"
        if QIcon.hasThemeIcon(iconThemeName):
            icon4 = QIcon.fromTheme(iconThemeName)
        else:
            icon4.addFile(u"../../../../../../../../../../../../../../src/icons/008-redo.png", QSize(), QIcon.Normal, QIcon.Off)

        self.redo_button.setIcon(icon4)
        self.redo_button.setIconSize(QSize(15, 15))
        self.redo_button.setFlat(True)

        self.horizontalLayout_5.addWidget(self.redo_button)

        self.file_new_button = QPushButton(self.canvas_control_bar)
        self.file_new_button.setObjectName(u"file_new_button")
        sizePolicy.setHeightForWidth(self.file_new_button.sizePolicy().hasHeightForWidth())
        self.file_new_button.setSizePolicy(sizePolicy)
        self.file_new_button.setMinimumSize(QSize(0, 0))
        self.file_new_button.setMaximumSize(QSize(16777215, 16777215))
        self.file_new_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon5 = QIcon()
        iconThemeName = u"document-new"
        if QIcon.hasThemeIcon(iconThemeName):
            icon5 = QIcon.fromTheme(iconThemeName)
        else:
            icon5.addFile(u"../../../../../../../../../../../../../../.designer/backup", QSize(), QIcon.Normal, QIcon.Off)

        self.file_new_button.setIcon(icon5)
        self.file_new_button.setIconSize(QSize(15, 15))
        self.file_new_button.setFlat(True)

        self.horizontalLayout_5.addWidget(self.file_new_button)

        self.export_button = QPushButton(self.canvas_control_bar)
        self.export_button.setObjectName(u"export_button")
        sizePolicy.setHeightForWidth(self.export_button.sizePolicy().hasHeightForWidth())
        self.export_button.setSizePolicy(sizePolicy)
        self.export_button.setMinimumSize(QSize(0, 0))
        self.export_button.setMaximumSize(QSize(16777215, 16777215))
        self.export_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon6 = QIcon()
        iconThemeName = u"document-send"
        if QIcon.hasThemeIcon(iconThemeName):
            icon6 = QIcon.fromTheme(iconThemeName)
        else:
            icon6.addFile(u"../../../../../../../../../../../../../../src/icons/export.png", QSize(), QIcon.Normal, QIcon.Off)

        self.export_button.setIcon(icon6)
        self.export_button.setIconSize(QSize(15, 15))
        self.export_button.setFlat(True)

        self.horizontalLayout_5.addWidget(self.export_button)

        self.horizontalSpacer_2 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_5.addItem(self.horizontalSpacer_2)

        self.toggle_active_grid_area_button = QPushButton(self.canvas_control_bar)
        self.toggle_active_grid_area_button.setObjectName(u"toggle_active_grid_area_button")
        sizePolicy.setHeightForWidth(self.toggle_active_grid_area_button.sizePolicy().hasHeightForWidth())
        self.toggle_active_grid_area_button.setSizePolicy(sizePolicy)
        self.toggle_active_grid_area_button.setMinimumSize(QSize(0, 0))
        self.toggle_active_grid_area_button.setMaximumSize(QSize(16777215, 16777215))
        self.toggle_active_grid_area_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon7 = QIcon()
        icon7.addFile(u":/icons/light/object-selected-icon.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.toggle_active_grid_area_button.setIcon(icon7)
        self.toggle_active_grid_area_button.setIconSize(QSize(15, 15))
        self.toggle_active_grid_area_button.setCheckable(True)
        self.toggle_active_grid_area_button.setFlat(True)

        self.horizontalLayout_5.addWidget(self.toggle_active_grid_area_button)

        self.toggle_select_button = QPushButton(self.canvas_control_bar)
        self.toggle_select_button.setObjectName(u"toggle_select_button")
        sizePolicy.setHeightForWidth(self.toggle_select_button.sizePolicy().hasHeightForWidth())
        self.toggle_select_button.setSizePolicy(sizePolicy)
        self.toggle_select_button.setMinimumSize(QSize(0, 0))
        self.toggle_select_button.setMaximumSize(QSize(16777215, 16777215))
        icon8 = QIcon()
        icon8.addFile(u":/icons/light/select-svgrepo-com.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.toggle_select_button.setIcon(icon8)
        self.toggle_select_button.setIconSize(QSize(15, 15))
        self.toggle_select_button.setCheckable(True)
        self.toggle_select_button.setFlat(True)

        self.horizontalLayout_5.addWidget(self.toggle_select_button)

        self.toggle_brush_button = QPushButton(self.canvas_control_bar)
        self.toggle_brush_button.setObjectName(u"toggle_brush_button")
        sizePolicy.setHeightForWidth(self.toggle_brush_button.sizePolicy().hasHeightForWidth())
        self.toggle_brush_button.setSizePolicy(sizePolicy)
        self.toggle_brush_button.setMinimumSize(QSize(0, 0))
        self.toggle_brush_button.setMaximumSize(QSize(16777215, 16777215))
        self.toggle_brush_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon9 = QIcon()
        icon9.addFile(u":/icons/light/pencil-icon.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.toggle_brush_button.setIcon(icon9)
        self.toggle_brush_button.setIconSize(QSize(15, 15))
        self.toggle_brush_button.setCheckable(True)
        self.toggle_brush_button.setFlat(True)

        self.horizontalLayout_5.addWidget(self.toggle_brush_button)

        self.toggle_eraser_button = QPushButton(self.canvas_control_bar)
        self.toggle_eraser_button.setObjectName(u"toggle_eraser_button")
        sizePolicy.setHeightForWidth(self.toggle_eraser_button.sizePolicy().hasHeightForWidth())
        self.toggle_eraser_button.setSizePolicy(sizePolicy)
        self.toggle_eraser_button.setMinimumSize(QSize(0, 0))
        self.toggle_eraser_button.setMaximumSize(QSize(16777215, 16777215))
        self.toggle_eraser_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon10 = QIcon()
        icon10.addFile(u":/icons/light/eraser-icon.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.toggle_eraser_button.setIcon(icon10)
        self.toggle_eraser_button.setIconSize(QSize(15, 15))
        self.toggle_eraser_button.setCheckable(True)
        self.toggle_eraser_button.setFlat(True)

        self.horizontalLayout_5.addWidget(self.toggle_eraser_button)

        self.toggle_grid_button = QPushButton(self.canvas_control_bar)
        self.toggle_grid_button.setObjectName(u"toggle_grid_button")
        sizePolicy.setHeightForWidth(self.toggle_grid_button.sizePolicy().hasHeightForWidth())
        self.toggle_grid_button.setSizePolicy(sizePolicy)
        self.toggle_grid_button.setMinimumSize(QSize(0, 0))
        self.toggle_grid_button.setMaximumSize(QSize(16777215, 16777215))
        self.toggle_grid_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon11 = QIcon()
        icon11.addFile(u":/icons/light/frame-grid-icon.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.toggle_grid_button.setIcon(icon11)
        self.toggle_grid_button.setIconSize(QSize(15, 15))
        self.toggle_grid_button.setCheckable(True)
        self.toggle_grid_button.setFlat(True)

        self.horizontalLayout_5.addWidget(self.toggle_grid_button)

        self.focus_button = QPushButton(self.canvas_control_bar)
        self.focus_button.setObjectName(u"focus_button")
        sizePolicy.setHeightForWidth(self.focus_button.sizePolicy().hasHeightForWidth())
        self.focus_button.setSizePolicy(sizePolicy)
        self.focus_button.setMinimumSize(QSize(0, 0))
        self.focus_button.setMaximumSize(QSize(16777215, 16777215))
        self.focus_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon12 = QIcon()
        icon12.addFile(u":/icons/light/circle-center-icon.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.focus_button.setIcon(icon12)
        self.focus_button.setIconSize(QSize(15, 15))
        self.focus_button.setFlat(True)

        self.horizontalLayout_5.addWidget(self.focus_button)


        self.gridLayout_2.addWidget(self.canvas_control_bar, 0, 0, 1, 1)

        self.canvas_widget_2 = CanvasWidget(self.canvas_widget)
        self.canvas_widget_2.setObjectName(u"canvas_widget_2")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.MinimumExpanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.canvas_widget_2.sizePolicy().hasHeightForWidth())
        self.canvas_widget_2.setSizePolicy(sizePolicy1)
        self.canvas_widget_2.setMinimumSize(QSize(0, 0))
        self.canvas_widget_2.setMaximumSize(QSize(16777215, 16777215))
        self.canvas_widget_2.setCursor(QCursor(Qt.ArrowCursor))
        self.canvas_widget_2.setAcceptDrops(True)

        self.gridLayout_2.addWidget(self.canvas_widget_2, 1, 0, 1, 1)

        self.content_splitter.addWidget(self.canvas_widget)
        self.panel_container = QWidget(self.content_splitter)
        self.panel_container.setObjectName(u"panel_container")
        self.verticalLayout_2 = QVBoxLayout(self.panel_container)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.tool_tab_widget = ToolTabWidget(self.panel_container)
        self.tool_tab_widget.setObjectName(u"tool_tab_widget")

        self.verticalLayout_2.addWidget(self.tool_tab_widget)

        self.content_splitter.addWidget(self.panel_container)

        self.gridLayout.addWidget(self.content_splitter, 0, 1, 1, 1)

        self.button_menu = QFrame(self.mode_tab_widget)
        self.button_menu.setObjectName(u"button_menu")
        sizePolicy.setHeightForWidth(self.button_menu.sizePolicy().hasHeightForWidth())
        self.button_menu.setSizePolicy(sizePolicy)
        self.button_menu.setMinimumSize(QSize(0, 0))
        self.button_menu.setMaximumSize(QSize(16777215, 16777215))
        self.button_menu.setStyleSheet(u"")
        self.button_menu.setFrameShape(QFrame.Shape.NoFrame)
        self.button_menu.setFrameShadow(QFrame.Shadow.Raised)
        self.verticalLayout = QVBoxLayout(self.button_menu)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.ai_button = QPushButton(self.button_menu)
        self.ai_button.setObjectName(u"ai_button")
        self.ai_button.setMinimumSize(QSize(36, 36))
        self.ai_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon13 = QIcon()
        icon13.addFile(u":/icons/light/artificial-intelligence-ai-chip-icon.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.ai_button.setIcon(icon13)
        self.ai_button.setIconSize(QSize(18, 18))
        self.ai_button.setCheckable(True)
        self.ai_button.setFlat(True)

        self.verticalLayout.addWidget(self.ai_button)

        self.line = QFrame(self.button_menu)
        self.line.setObjectName(u"line")
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)

        self.verticalLayout.addWidget(self.line)

        self.verticalSpacer = QSpacerItem(20, 10, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout.addItem(self.verticalSpacer)

        self.sd_toggle_button = QPushButton(self.button_menu)
        self.sd_toggle_button.setObjectName(u"sd_toggle_button")
        self.sd_toggle_button.setMinimumSize(QSize(36, 36))
        self.sd_toggle_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon14 = QIcon(QIcon.fromTheme(u"applications-graphics"))
        self.sd_toggle_button.setIcon(icon14)
        self.sd_toggle_button.setIconSize(QSize(18, 18))
        self.sd_toggle_button.setCheckable(True)
        self.sd_toggle_button.setChecked(False)
        self.sd_toggle_button.setFlat(True)

        self.verticalLayout.addWidget(self.sd_toggle_button)

        self.controlnet_toggle_button = QPushButton(self.button_menu)
        self.controlnet_toggle_button.setObjectName(u"controlnet_toggle_button")
        self.controlnet_toggle_button.setMinimumSize(QSize(36, 36))
        self.controlnet_toggle_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon15 = QIcon(QIcon.fromTheme(u"insert-image"))
        self.controlnet_toggle_button.setIcon(icon15)
        self.controlnet_toggle_button.setIconSize(QSize(18, 18))
        self.controlnet_toggle_button.setCheckable(True)
        self.controlnet_toggle_button.setFlat(True)

        self.verticalLayout.addWidget(self.controlnet_toggle_button)

        self.llm_button = QPushButton(self.button_menu)
        self.llm_button.setObjectName(u"llm_button")
        self.llm_button.setMinimumSize(QSize(36, 36))
        self.llm_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon16 = QIcon(QIcon.fromTheme(u"applications-internet"))
        self.llm_button.setIcon(icon16)
        self.llm_button.setIconSize(QSize(18, 18))
        self.llm_button.setCheckable(True)
        self.llm_button.setFlat(True)

        self.verticalLayout.addWidget(self.llm_button)

        self.tts_button = QPushButton(self.button_menu)
        self.tts_button.setObjectName(u"tts_button")
        self.tts_button.setMinimumSize(QSize(36, 36))
        self.tts_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon17 = QIcon(QIcon.fromTheme(u"audio-volume-high"))
        self.tts_button.setIcon(icon17)
        self.tts_button.setIconSize(QSize(18, 18))
        self.tts_button.setCheckable(True)
        self.tts_button.setFlat(True)

        self.verticalLayout.addWidget(self.tts_button)

        self.v2t_button = QPushButton(self.button_menu)
        self.v2t_button.setObjectName(u"v2t_button")
        self.v2t_button.setMinimumSize(QSize(36, 36))
        self.v2t_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon18 = QIcon(QIcon.fromTheme(u"audio-input-microphone"))
        self.v2t_button.setIcon(icon18)
        self.v2t_button.setIconSize(QSize(18, 18))
        self.v2t_button.setCheckable(True)
        self.v2t_button.setFlat(True)

        self.verticalLayout.addWidget(self.v2t_button)

        self.line_3 = QFrame(self.button_menu)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setFrameShape(QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QFrame.Shadow.Sunken)

        self.verticalLayout.addWidget(self.line_3)

        self.settings_button = QPushButton(self.button_menu)
        self.settings_button.setObjectName(u"settings_button")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Maximum, QSizePolicy.Policy.MinimumExpanding)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.settings_button.sizePolicy().hasHeightForWidth())
        self.settings_button.setSizePolicy(sizePolicy2)
        self.settings_button.setMinimumSize(QSize(36, 36))
        self.settings_button.setMaximumSize(QSize(36, 36))
        self.settings_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon19 = QIcon()
        icon19.addFile(u":/icons/light/setting-line-icon.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.settings_button.setIcon(icon19)
        self.settings_button.setIconSize(QSize(18, 18))
        self.settings_button.setFlat(True)

        self.verticalLayout.addWidget(self.settings_button)


        self.gridLayout.addWidget(self.button_menu, 0, 0, 1, 1)


        self.gridLayout_3.addWidget(self.mode_tab_widget, 0, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1304, 22))
        font1 = QFont()
        font1.setPointSize(11)
        self.menubar.setFont(font1)
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuFilters = QMenu(self.menubar)
        self.menuFilters.setObjectName(u"menuFilters")
        self.menuAbout = QMenu(self.menubar)
        self.menuAbout.setObjectName(u"menuAbout")
        self.menuAbout.setTearOffEnabled(False)
        self.menuImage = QMenu(self.menubar)
        self.menuImage.setObjectName(u"menuImage")
        self.menuCanvas_Image = QMenu(self.menuImage)
        self.menuCanvas_Image.setObjectName(u"menuCanvas_Image")
        self.menuDrawingpad = QMenu(self.menuImage)
        self.menuDrawingpad.setObjectName(u"menuDrawingpad")
        self.menuControlnet = QMenu(self.menuImage)
        self.menuControlnet.setObjectName(u"menuControlnet")
        self.menuOutpaint = QMenu(self.menuImage)
        self.menuOutpaint.setObjectName(u"menuOutpaint")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        self.menuTools = QMenu(self.menubar)
        self.menuTools.setObjectName(u"menuTools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuImage.menuAction())
        self.menubar.addAction(self.menuFilters.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuFile.addAction(self.actionReset_Settings_2)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionRotate_90_clockwise)
        self.menuEdit.addAction(self.actionRotate_90_counter_clockwise)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionClear_all_prompts)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionSettings)
        self.menuFilters.addSeparator()
        self.menuAbout.addAction(self.actionAbout)
        self.menuAbout.addAction(self.actionBug_report)
        self.menuAbout.addAction(self.actionReport_vulnerability)
        self.menuImage.addSeparator()
        self.menuImage.addAction(self.menuCanvas_Image.menuAction())
        self.menuImage.addAction(self.menuDrawingpad.menuAction())
        self.menuImage.addAction(self.menuControlnet.menuAction())
        self.menuImage.addAction(self.menuOutpaint.menuAction())
        self.menuImage.addSeparator()
        self.menuCanvas_Image.addAction(self.actionImport)
        self.menuCanvas_Image.addAction(self.actionExport)
        self.menuDrawingpad.addAction(self.drawingpad_import)
        self.menuDrawingpad.addAction(self.drawingpad_export)
        self.menuDrawingpad.addSeparator()
        self.menuDrawingpad.addAction(self.actionOverlay_input_image)
        self.menuControlnet.addAction(self.controlnet_import)
        self.menuControlnet.addAction(self.controlnet_export)
        self.menuControlnet.addSeparator()
        self.menuControlnet.addAction(self.enable_controlnet)
        self.menuOutpaint.addAction(self.outpaint_import)
        self.menuOutpaint.addAction(self.outpaint_export)
        self.menuOutpaint.addAction(self.outpaint_enabled)
        self.menuView.addAction(self.actionPrompt_Browser)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionBrowse_AI_Runner_Path)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionBrowse_Images_Path_2)
        self.menuView.addSeparator()
        self.menuTools.addAction(self.actionRun_setup_wizard_2)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionModel_Manager_3)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionStats)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionClear_Memory)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionSafety_Checker)

        self.retranslateUi(MainWindow)
        self.actionAbout.triggered.connect(MainWindow.action_show_about_window)
        self.actionExport.triggered.connect(MainWindow.action_export_image_triggered)
        self.actionNew.triggered.connect(MainWindow.action_new_document_triggered)
        self.actionImport.triggered.connect(MainWindow.action_import_image_triggered)
        self.actionQuit.triggered.connect(MainWindow.action_quit_triggered)
        self.actionPaste.triggered.connect(MainWindow.action_paste_image_triggered)
        self.actionCopy.triggered.connect(MainWindow.action_copy_image_triggered)
        self.actionCut.triggered.connect(MainWindow.action_cut_image_triggered)
        self.actionRotate_90_clockwise.triggered.connect(MainWindow.action_rotate_90_clockwise_triggered)
        self.actionRotate_90_counter_clockwise.triggered.connect(MainWindow.action_rotate_90_counterclockwise_triggered)
        self.actionPrompt_Browser.triggered.connect(MainWindow.action_show_prompt_browser_triggered)
        self.actionClear_all_prompts.triggered.connect(MainWindow.action_clear_all_prompts_triggered)
        self.actionBrowse_AI_Runner_Path.triggered.connect(MainWindow.action_triggered_browse_ai_runner_path)
        self.actionBrowse_Images_Path_2.triggered.connect(MainWindow.action_show_images_path)
        self.actionTxt2img_Img2img_Models.triggered.connect(MainWindow.action_show_model_path_txt2img)
        self.actionInpaint_Outpaint_Models.triggered.connect(MainWindow.action_show_model_path_inpaint)
        self.actionModel_Manager_2.triggered.connect(MainWindow.action_show_model_manager)
        self.actionBug_report.triggered.connect(MainWindow.action_open_bug_report)
        self.actionDiscord.triggered.connect(MainWindow.action_open_discord)
        self.actionReport_vulnerability.triggered.connect(MainWindow.action_open_vulnerability_report)
        self.ai_button.toggled.connect(MainWindow.action_ai_toggled)
        self.file_new_button.clicked.connect(MainWindow.action_new_document_triggered)
        self.export_button.clicked.connect(MainWindow.action_export_image_triggered)
        self.undo_button.clicked.connect(MainWindow.action_undo_triggered)
        self.redo_button.clicked.connect(MainWindow.action_redo_triggered)
        self.actionReset_Settings_2.triggered.connect(MainWindow.action_reset_settings)
        self.actionModel_Manager_3.triggered.connect(MainWindow.action_show_model_manager)
        self.drawingpad_import.triggered.connect(MainWindow.import_drawingpad_image)
        self.drawingpad_export.triggered.connect(MainWindow.export_drawingpad_image)
        self.controlnet_import.triggered.connect(MainWindow.import_controlnet_image)
        self.controlnet_export.triggered.connect(MainWindow.export_controlnet_image)
        self.enable_controlnet.toggled.connect(MainWindow.action_controlnet_toggled)
        self.actionClear_Memory.triggered.connect(MainWindow.action_clear_memory)
        self.actionSafety_Checker.toggled.connect(MainWindow.action_toggle_nsfw_filter_triggered)
        self.outpaint_export.triggered.connect(MainWindow.action_outpaint_export)
        self.outpaint_enabled.toggled.connect(MainWindow.action_outpaint_toggled)
        self.outpaint_import.triggered.connect(MainWindow.action_outpaint_import)
        self.actionRun_setup_wizard_2.triggered.connect(MainWindow.action_run_setup_wizard_clicked)
        self.toggle_active_grid_area_button.toggled.connect(MainWindow.action_toggle_active_grid_area)
        self.toggle_select_button.toggled.connect(MainWindow.action_toggle_select)
        self.toggle_brush_button.toggled.connect(MainWindow.action_toggle_brush)
        self.toggle_eraser_button.toggled.connect(MainWindow.action_toggle_eraser)
        self.toggle_grid_button.toggled.connect(MainWindow.action_toggle_grid)
        self.focus_button.clicked.connect(MainWindow.action_center_clicked)
        self.sd_toggle_button.toggled.connect(MainWindow.action_image_generator_toggled)
        self.controlnet_toggle_button.toggled.connect(MainWindow.action_controlnet_toggled)
        self.tts_button.toggled.connect(MainWindow.tts_button_toggled)
        self.v2t_button.toggled.connect(MainWindow.v2t_button_toggled)
        self.llm_button.toggled.connect(MainWindow.action_toggle_llm)
        self.actionStats.triggered.connect(MainWindow.action_stats_triggered)
        self.actionSettings.triggered.connect(MainWindow.action_show_settings)
        self.settings_button.clicked.connect(MainWindow.action_show_settings)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"AI Runner", None))
        self.actionNew.setText(QCoreApplication.translate("MainWindow", u"New", None))
#if QT_CONFIG(shortcut)
        self.actionNew.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.actionImport.setText(QCoreApplication.translate("MainWindow", u"Import image", None))
#if QT_CONFIG(shortcut)
        self.actionImport.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+I", None))
#endif // QT_CONFIG(shortcut)
        self.actionExport.setText(QCoreApplication.translate("MainWindow", u"Export image", None))
#if QT_CONFIG(shortcut)
        self.actionExport.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+E", None))
#endif // QT_CONFIG(shortcut)
        self.actionCopy.setText(QCoreApplication.translate("MainWindow", u"Copy", None))
#if QT_CONFIG(shortcut)
        self.actionCopy.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+C", None))
#endif // QT_CONFIG(shortcut)
        self.actionPaste.setText(QCoreApplication.translate("MainWindow", u"Paste", None))
#if QT_CONFIG(shortcut)
        self.actionPaste.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+V", None))
#endif // QT_CONFIG(shortcut)
        self.actionUndo.setText(QCoreApplication.translate("MainWindow", u"Undo", None))
#if QT_CONFIG(tooltip)
        self.actionUndo.setToolTip(QCoreApplication.translate("MainWindow", u"Undo", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.actionUndo.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(shortcut)
        self.actionUndo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Z", None))
#endif // QT_CONFIG(shortcut)
        self.actionRedo.setText(QCoreApplication.translate("MainWindow", u"Redo", None))
#if QT_CONFIG(shortcut)
        self.actionRedo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Y", None))
#endif // QT_CONFIG(shortcut)
        self.actionGrid.setText(QCoreApplication.translate("MainWindow", u"Grid", None))
#if QT_CONFIG(tooltip)
        self.actionGrid.setToolTip(QCoreApplication.translate("MainWindow", u"Grid settings", None))
#endif // QT_CONFIG(tooltip)
        self.actionPreferences.setText(QCoreApplication.translate("MainWindow", u"Path Preferences", None))
#if QT_CONFIG(tooltip)
        self.actionPreferences.setToolTip(QCoreApplication.translate("MainWindow", u"Modify model path and more", None))
#endif // QT_CONFIG(tooltip)
        self.actionCanvas_color.setText(QCoreApplication.translate("MainWindow", u"Canvas color", None))
#if QT_CONFIG(tooltip)
        self.actionCanvas_color.setToolTip(QCoreApplication.translate("MainWindow", u"Change the color of the canvas", None))
#endif // QT_CONFIG(tooltip)
        self.actionReset_Settings.setText(QCoreApplication.translate("MainWindow", u"Reset Settings to Default", None))
#if QT_CONFIG(tooltip)
        self.actionReset_Settings.setToolTip(QCoreApplication.translate("MainWindow", u"Reset all settings to default", None))
#endif // QT_CONFIG(tooltip)
        self.actionResize_on_Paste.setText(QCoreApplication.translate("MainWindow", u"Resize on Import", None))
#if QT_CONFIG(tooltip)
        self.actionResize_on_Paste.setToolTip(QCoreApplication.translate("MainWindow", u"Resize the image to active grid area when importing", None))
#endif // QT_CONFIG(tooltip)
        self.actionMemory.setText(QCoreApplication.translate("MainWindow", u"Memory", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.actionCheck_for_updates.setText(QCoreApplication.translate("MainWindow", u"Check for updates", None))
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.actionView.setText(QCoreApplication.translate("MainWindow", u"View", None))
        self.actionAdvanced.setText(QCoreApplication.translate("MainWindow", u"Memory Preferences", None))
#if QT_CONFIG(tooltip)
        self.actionAdvanced.setToolTip(QCoreApplication.translate("MainWindow", u"Change memory settings", None))
#endif // QT_CONFIG(tooltip)
        self.actionGaussian_Blur.setText(QCoreApplication.translate("MainWindow", u"Gaussian Blur", None))
        self.actionBox_Blur.setText(QCoreApplication.translate("MainWindow", u"Box Blur", None))
        self.actionUnsharp_Mask.setText(QCoreApplication.translate("MainWindow", u"Unsharp Mask", None))
        self.actionPixel_Art.setText(QCoreApplication.translate("MainWindow", u"Pixel Art", None))
        self.actionInvert.setText(QCoreApplication.translate("MainWindow", u"Invert", None))
#if QT_CONFIG(shortcut)
        self.actionInvert.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+I", None))
#endif // QT_CONFIG(shortcut)
        self.actionSaturation.setText(QCoreApplication.translate("MainWindow", u"Saturation", None))
        self.actionColor_Balance.setText(QCoreApplication.translate("MainWindow", u"Color Balance", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
#if QT_CONFIG(shortcut)
        self.actionSave.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionLoad.setText(QCoreApplication.translate("MainWindow", u"Open", None))
#if QT_CONFIG(shortcut)
        self.actionLoad.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionQuit.setText(QCoreApplication.translate("MainWindow", u"Quit", None))
#if QT_CONFIG(shortcut)
        self.actionQuit.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
        self.actionPixel_Art_2.setText(QCoreApplication.translate("MainWindow", u"Pixel Art", None))
        self.actionBug_report.setText(QCoreApplication.translate("MainWindow", u"Bug report", None))
        self.actionReport_vulnerability.setText(QCoreApplication.translate("MainWindow", u"Report vulnerability", None))
        self.actionDiscord.setText(QCoreApplication.translate("MainWindow", u"Discord", None))
        self.actionExtensions.setText(QCoreApplication.translate("MainWindow", u"Extensions", None))
#if QT_CONFIG(tooltip)
        self.actionExtensions.setToolTip(QCoreApplication.translate("MainWindow", u"Install, update and delete extensions", None))
#endif // QT_CONFIG(tooltip)
        self.actionShow_image_preview.setText(QCoreApplication.translate("MainWindow", u"Show image preview", None))
        self.actionImage_to_new_layer.setText(QCoreApplication.translate("MainWindow", u"Image to new layer", None))
#if QT_CONFIG(tooltip)
        self.actionImage_to_new_layer.setToolTip(QCoreApplication.translate("MainWindow", u"Send generated images to new layer", None))
#endif // QT_CONFIG(tooltip)
        self.actionAuto_export_images.setText(QCoreApplication.translate("MainWindow", u"Auto export images", None))
#if QT_CONFIG(tooltip)
        self.actionAuto_export_images.setToolTip(QCoreApplication.translate("MainWindow", u"Automatically export newly generated images to a folder", None))
#endif // QT_CONFIG(tooltip)
        self.actionImage_export_settings.setText(QCoreApplication.translate("MainWindow", u"Import / export preferences", None))
        self.actionCheck_for_latest_version_on_startup.setText(QCoreApplication.translate("MainWindow", u"Check for latest version on startup", None))
        self.actionModel_Merger.setText(QCoreApplication.translate("MainWindow", u"Model Merger", None))
        self.actionSaturation_Filter.setText(QCoreApplication.translate("MainWindow", u"Saturation", None))
        self.actionColor_Balance_2.setText(QCoreApplication.translate("MainWindow", u"Color Balance", None))
        self.actionRGB_Noise.setText(QCoreApplication.translate("MainWindow", u"RGB Noise", None))
        self.actionGaussian_Blur_2.setText(QCoreApplication.translate("MainWindow", u"Gaussian Blur", None))
        self.actionBox_Blur_2.setText(QCoreApplication.translate("MainWindow", u"Box Blur", None))
        self.actionRotate_90_clockwise.setText(QCoreApplication.translate("MainWindow", u"Rotate 90\u00b0 clockwise", None))
#if QT_CONFIG(shortcut)
        self.actionRotate_90_clockwise.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+R", None))
#endif // QT_CONFIG(shortcut)
        self.actionRotate_90_counter_clockwise.setText(QCoreApplication.translate("MainWindow", u"Rotate 90\u00b0 counter clockwise", None))
#if QT_CONFIG(shortcut)
        self.actionRotate_90_counter_clockwise.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+R", None))
#endif // QT_CONFIG(shortcut)
        self.actionSave_prompt.setText(QCoreApplication.translate("MainWindow", u"Save prompt", None))
        self.actionShow_Active_Image_Area.setText(QCoreApplication.translate("MainWindow", u"Show Active Image Area", None))
        self.actionImage_Interpolation.setText(QCoreApplication.translate("MainWindow", u"Image Interpolation", None))
        self.actionImage_interpolation.setText(QCoreApplication.translate("MainWindow", u"Image Interpolation", None))
        self.actionFilm.setText(QCoreApplication.translate("MainWindow", u"Film", None))
#if QT_CONFIG(shortcut)
        self.actionFilm.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+F", None))
#endif // QT_CONFIG(shortcut)
        self.actionDeterministic_generation.setText(QCoreApplication.translate("MainWindow", u"Deterministic generator", None))
        self.actionDark_mode.setText(QCoreApplication.translate("MainWindow", u"Dark mode", None))
        self.actionConsole_window.setText(QCoreApplication.translate("MainWindow", u"Console window", None))
        self.actionPrompt_Browser.setText(QCoreApplication.translate("MainWindow", u"Prompt browser", None))
        self.actionClear_all_prompts.setText(QCoreApplication.translate("MainWindow", u"Clear all prompts", None))
#if QT_CONFIG(tooltip)
        self.actionClear_all_prompts.setToolTip(QCoreApplication.translate("MainWindow", u"Remove text from all prompts and negative prompts", None))
#endif // QT_CONFIG(tooltip)
        self.actionUndo_2.setText(QCoreApplication.translate("MainWindow", u"Undo", None))
#if QT_CONFIG(shortcut)
        self.actionUndo_2.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Z", None))
#endif // QT_CONFIG(shortcut)
        self.actionRedo_2.setText(QCoreApplication.translate("MainWindow", u"Redo", None))
#if QT_CONFIG(shortcut)
        self.actionRedo_2.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Y", None))
#endif // QT_CONFIG(shortcut)
        self.actionCut.setText(QCoreApplication.translate("MainWindow", u"Cut", None))
#if QT_CONFIG(shortcut)
        self.actionCut.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+X", None))
#endif // QT_CONFIG(shortcut)
        self.actionHalftone.setText(QCoreApplication.translate("MainWindow", u"Halftone", None))
        self.actionQuick_Export.setText(QCoreApplication.translate("MainWindow", u"Fast Export", None))
#if QT_CONFIG(shortcut)
        self.actionQuick_Export.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+E", None))
#endif // QT_CONFIG(shortcut)
        self.actionRegistration_error.setText(QCoreApplication.translate("MainWindow", u"Registration error", None))
        self.actionHuggingface_Cache_manager.setText(QCoreApplication.translate("MainWindow", u"Browse Huggingface Cache", None))
        self.actionModel_Manager.setText(QCoreApplication.translate("MainWindow", u"Model Manager", None))
        self.actionModel_Manager_2.setText(QCoreApplication.translate("MainWindow", u"Model Manager", None))
        self.actionControlNet.setText(QCoreApplication.translate("MainWindow", u"ControlNet", None))
        self.actionPrompt_Builder.setText(QCoreApplication.translate("MainWindow", u"Prompt Builder", None))
        self.actionEmbeddings.setText(QCoreApplication.translate("MainWindow", u"Embeddings", None))
        self.actionLoRA.setText(QCoreApplication.translate("MainWindow", u"LoRA", None))
        self.actionPen.setText(QCoreApplication.translate("MainWindow", u"Pen", None))
        self.actionStableDiffusion.setText(QCoreApplication.translate("MainWindow", u"Stable Diffusion", None))
        self.actionKandinsky.setText(QCoreApplication.translate("MainWindow", u"Kandinsky", None))
        self.actionShap_E.setText(QCoreApplication.translate("MainWindow", u"Shap-E", None))
        self.actionRun_setup_wizard.setText(QCoreApplication.translate("MainWindow", u"Run setup wizard", None))
        self.actionBrowse_AI_Runner_Path.setText(QCoreApplication.translate("MainWindow", u"Browse AI Runner Path", None))
        self.actionBrowse_Images_Path.setText(QCoreApplication.translate("MainWindow", u"Browse Images Path", None))
        self.actionBrowse_Images_Path_2.setText(QCoreApplication.translate("MainWindow", u"Browse Images", None))
        self.actionBrowse_Gifs_Path.setText(QCoreApplication.translate("MainWindow", u"Browse GIFs", None))
        self.actionTxt2img_Img2img_Models.setText(QCoreApplication.translate("MainWindow", u"Txt2img / Img2img", None))
        self.actionInpaint_Outpaint_Models.setText(QCoreApplication.translate("MainWindow", u"Inpaint / Outpaint", None))
        self.actionActive_Grid.setText(QCoreApplication.translate("MainWindow", u"Active Grid", None))
        self.actionDeterministic_Batches.setText(QCoreApplication.translate("MainWindow", u"Deterministic Batches", None))
        self.actionStandard_Batches.setText(QCoreApplication.translate("MainWindow", u"Standard Batches", None))
        self.actionLLM_beta.setText(QCoreApplication.translate("MainWindow", u"LLM (beta)", None))
        self.actionReset_Settings_2.setText(QCoreApplication.translate("MainWindow", u"Reset Settings", None))
        self.actionImage_Browser.setText(QCoreApplication.translate("MainWindow", u"Image Browser", None))
        self.actionModel_Manager_3.setText(QCoreApplication.translate("MainWindow", u"Model Manager", None))
        self.actionImport_input_image.setText(QCoreApplication.translate("MainWindow", u"Import input image", None))
        self.actionExport_input_image.setText(QCoreApplication.translate("MainWindow", u"Export input image", None))
        self.actionImport_2.setText(QCoreApplication.translate("MainWindow", u"Import image", None))
        self.actionExport_image.setText(QCoreApplication.translate("MainWindow", u"Export image", None))
        self.actionImport_Image.setText(QCoreApplication.translate("MainWindow", u"Import Image", None))
        self.actionExport_Image.setText(QCoreApplication.translate("MainWindow", u"Export Image", None))
        self.actionImport_3.setText(QCoreApplication.translate("MainWindow", u"Import", None))
        self.actionExport_2.setText(QCoreApplication.translate("MainWindow", u"Export", None))
        self.controlnet_import.setText(QCoreApplication.translate("MainWindow", u"Import Image", None))
        self.controlnet_export.setText(QCoreApplication.translate("MainWindow", u"Export Image", None))
        self.drawingpad_import.setText(QCoreApplication.translate("MainWindow", u"Import Image", None))
        self.drawingpad_export.setText(QCoreApplication.translate("MainWindow", u"Export Image", None))
        self.actionGenerate_while_drawing.setText(QCoreApplication.translate("MainWindow", u"Generate while drawing", None))
        self.actionOverlay_input_image.setText(QCoreApplication.translate("MainWindow", u"Overlay input image", None))
        self.enable_controlnet.setText(QCoreApplication.translate("MainWindow", u"Enabled", None))
        self.actionUnload_LLm.setText(QCoreApplication.translate("MainWindow", u"Unload LLM", None))
        self.actionUnload_Image_model.setText(QCoreApplication.translate("MainWindow", u"Unload Image model", None))
        self.actionClear_Memory.setText(QCoreApplication.translate("MainWindow", u"Clear Memory", None))
        self.actionSafety_Checker.setText(QCoreApplication.translate("MainWindow", u"Safety Checker", None))
        self.outpaint_import.setText(QCoreApplication.translate("MainWindow", u"Import", None))
        self.outpaint_export.setText(QCoreApplication.translate("MainWindow", u"Export", None))
        self.outpaint_enabled.setText(QCoreApplication.translate("MainWindow", u"Enabled", None))
        self.actionModel_Manager_4.setText(QCoreApplication.translate("MainWindow", u"Model Manager", None))
        self.actionRun_setup_wizard_2.setText(QCoreApplication.translate("MainWindow", u"Run Setup Wizard", None))
        self.actionStats.setText(QCoreApplication.translate("MainWindow", u"Stats", None))
        self.actionSettings.setText(QCoreApplication.translate("MainWindow", u"Preferences", None))
#if QT_CONFIG(tooltip)
        self.undo_button.setToolTip(QCoreApplication.translate("MainWindow", u"Undo", None))
#endif // QT_CONFIG(tooltip)
        self.undo_button.setText("")
#if QT_CONFIG(tooltip)
        self.redo_button.setToolTip(QCoreApplication.translate("MainWindow", u"Redo", None))
#endif // QT_CONFIG(tooltip)
        self.redo_button.setText("")
#if QT_CONFIG(tooltip)
        self.file_new_button.setToolTip(QCoreApplication.translate("MainWindow", u"New", None))
#endif // QT_CONFIG(tooltip)
        self.file_new_button.setText("")
#if QT_CONFIG(tooltip)
        self.export_button.setToolTip(QCoreApplication.translate("MainWindow", u"Export Image", None))
#endif // QT_CONFIG(tooltip)
        self.export_button.setText("")
#if QT_CONFIG(tooltip)
        self.toggle_active_grid_area_button.setToolTip(QCoreApplication.translate("MainWindow", u"Active grid area selection tool", None))
#endif // QT_CONFIG(tooltip)
        self.toggle_active_grid_area_button.setText("")
        self.toggle_select_button.setText("")
#if QT_CONFIG(tooltip)
        self.toggle_brush_button.setToolTip(QCoreApplication.translate("MainWindow", u"Pen tool", None))
#endif // QT_CONFIG(tooltip)
        self.toggle_brush_button.setText("")
#if QT_CONFIG(tooltip)
        self.toggle_eraser_button.setToolTip(QCoreApplication.translate("MainWindow", u"Eraser tool", None))
#endif // QT_CONFIG(tooltip)
        self.toggle_eraser_button.setText("")
#if QT_CONFIG(tooltip)
        self.toggle_grid_button.setToolTip(QCoreApplication.translate("MainWindow", u"Toggle Grid", None))
#endif // QT_CONFIG(tooltip)
        self.toggle_grid_button.setText("")
#if QT_CONFIG(tooltip)
        self.focus_button.setToolTip(QCoreApplication.translate("MainWindow", u"Recenter canvas", None))
#endif // QT_CONFIG(tooltip)
        self.focus_button.setText("")
#if QT_CONFIG(tooltip)
        self.ai_button.setToolTip(QCoreApplication.translate("MainWindow", u"Toggle AI Mode", None))
#endif // QT_CONFIG(tooltip)
        self.ai_button.setText("")
#if QT_CONFIG(tooltip)
        self.sd_toggle_button.setToolTip(QCoreApplication.translate("MainWindow", u"Toggle Image Generator", None))
#endif // QT_CONFIG(tooltip)
        self.sd_toggle_button.setText("")
#if QT_CONFIG(tooltip)
        self.controlnet_toggle_button.setToolTip(QCoreApplication.translate("MainWindow", u"Toggle Controlnet", None))
#endif // QT_CONFIG(tooltip)
        self.controlnet_toggle_button.setText("")
        self.llm_button.setText("")
#if QT_CONFIG(tooltip)
        self.tts_button.setToolTip(QCoreApplication.translate("MainWindow", u"Toggle Text-to-Speech", None))
#endif // QT_CONFIG(tooltip)
        self.tts_button.setText("")
#if QT_CONFIG(tooltip)
        self.v2t_button.setToolTip(QCoreApplication.translate("MainWindow", u"Toggle Speech-to-Text", None))
#endif // QT_CONFIG(tooltip)
        self.v2t_button.setText("")
#if QT_CONFIG(tooltip)
        self.settings_button.setToolTip(QCoreApplication.translate("MainWindow", u"AI Runner Settings", None))
#endif // QT_CONFIG(tooltip)
        self.settings_button.setText("")
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.menuFilters.setTitle(QCoreApplication.translate("MainWindow", u"Filters", None))
        self.menuAbout.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.menuImage.setTitle(QCoreApplication.translate("MainWindow", u"Canvas", None))
        self.menuCanvas_Image.setTitle(QCoreApplication.translate("MainWindow", u"Main", None))
        self.menuDrawingpad.setTitle(QCoreApplication.translate("MainWindow", u"Input", None))
        self.menuControlnet.setTitle(QCoreApplication.translate("MainWindow", u"Controlnet", None))
        self.menuOutpaint.setTitle(QCoreApplication.translate("MainWindow", u"Outpaint", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
        self.menuTools.setTitle(QCoreApplication.translate("MainWindow", u"Tools", None))
    # retranslateUi

