# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.6.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGridLayout, QHBoxLayout,
    QMainWindow, QMenu, QMenuBar, QPushButton,
    QScrollArea, QSizePolicy, QSpacerItem, QSplitter,
    QStatusBar, QTabWidget, QVBoxLayout, QWidget)

from airunner.widgets.active_grid_settings.active_grid_settings_widget import ActiveGridSettingsWidget
from airunner.widgets.brush.brush_container_widget import BrushContainerWidget
from airunner.widgets.canvas.canvas_widget import CanvasWidget
from airunner.widgets.generator_form.generator_form_widget import GeneratorForm
from airunner.widgets.llm.llm_settings_widget import LLMSettingsWidget
from airunner.widgets.model_manager.model_manager_widget import ModelManagerWidget
from airunner.widgets.stablediffusion.stable_diffusion_settings_widget import StableDiffusionSettingsWidget
from airunner.widgets.upscale.upscale_widget import UpscaleWidget
import airunner.resources_light_rc
import airunner.resources_dark_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1123, 903)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(0, 0))
        font = QFont()
        font.setPointSize(8)
        MainWindow.setFont(font)
        icon = QIcon()
        icon.addFile(u":/icons/icon_256.png", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(u"")
        self.actionNew = QAction(MainWindow)
        self.actionNew.setObjectName(u"actionNew")
        self.actionImport = QAction(MainWindow)
        self.actionImport.setObjectName(u"actionImport")
        self.actionExport = QAction(MainWindow)
        self.actionExport.setObjectName(u"actionExport")
        self.actionCopy = QAction(MainWindow)
        self.actionCopy.setObjectName(u"actionCopy")
        self.actionPaste = QAction(MainWindow)
        self.actionPaste.setObjectName(u"actionPaste")
        self.actionUndo = QAction(MainWindow)
        self.actionUndo.setObjectName(u"actionUndo")
        icon1 = QIcon()
        icon1.addFile(u"../../../../../../../../../../../../../../.designer/src/icons/007-undo.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionUndo.setIcon(icon1)
        self.actionRedo = QAction(MainWindow)
        self.actionRedo.setObjectName(u"actionRedo")
        icon2 = QIcon()
        icon2.addFile(u"../../../../../../../../../../../../../../.designer/src/icons/008-redo.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionRedo.setIcon(icon2)
        self.actionGrid = QAction(MainWindow)
        self.actionGrid.setObjectName(u"actionGrid")
        self.actionPreferences = QAction(MainWindow)
        self.actionPreferences.setObjectName(u"actionPreferences")
        self.actionCanvas_color = QAction(MainWindow)
        self.actionCanvas_color.setObjectName(u"actionCanvas_color")
        self.actionReset_Settings = QAction(MainWindow)
        self.actionReset_Settings.setObjectName(u"actionReset_Settings")
        self.actionResize_on_Paste = QAction(MainWindow)
        self.actionResize_on_Paste.setObjectName(u"actionResize_on_Paste")
        self.actionResize_on_Paste.setCheckable(True)
        self.actionMemory = QAction(MainWindow)
        self.actionMemory.setObjectName(u"actionMemory")
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionCheck_for_updates = QAction(MainWindow)
        self.actionCheck_for_updates.setObjectName(u"actionCheck_for_updates")
        self.actionOpen = QAction(MainWindow)
        self.actionOpen.setObjectName(u"actionOpen")
        self.actionView = QAction(MainWindow)
        self.actionView.setObjectName(u"actionView")
        self.actionAdvanced = QAction(MainWindow)
        self.actionAdvanced.setObjectName(u"actionAdvanced")
        self.actionGaussian_Blur = QAction(MainWindow)
        self.actionGaussian_Blur.setObjectName(u"actionGaussian_Blur")
        self.actionGaussian_Blur.setEnabled(True)
        self.actionBox_Blur = QAction(MainWindow)
        self.actionBox_Blur.setObjectName(u"actionBox_Blur")
        self.actionUnsharp_Mask = QAction(MainWindow)
        self.actionUnsharp_Mask.setObjectName(u"actionUnsharp_Mask")
        self.actionPixel_Art = QAction(MainWindow)
        self.actionPixel_Art.setObjectName(u"actionPixel_Art")
        self.actionPixel_Art.setVisible(True)
        self.actionInvert = QAction(MainWindow)
        self.actionInvert.setObjectName(u"actionInvert")
        self.actionSaturation = QAction(MainWindow)
        self.actionSaturation.setObjectName(u"actionSaturation")
        self.actionSaturation.setVisible(True)
        self.actionColor_Balance = QAction(MainWindow)
        self.actionColor_Balance.setObjectName(u"actionColor_Balance")
        self.actionColor_Balance.setCheckable(False)
        self.actionColor_Balance.setEnabled(True)
        self.actionColor_Balance.setVisible(True)
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        self.actionLoad = QAction(MainWindow)
        self.actionLoad.setObjectName(u"actionLoad")
        self.actionQuit = QAction(MainWindow)
        self.actionQuit.setObjectName(u"actionQuit")
        self.actionPixel_Art_2 = QAction(MainWindow)
        self.actionPixel_Art_2.setObjectName(u"actionPixel_Art_2")
        self.actionBug_report = QAction(MainWindow)
        self.actionBug_report.setObjectName(u"actionBug_report")
        self.actionReport_vulnerability = QAction(MainWindow)
        self.actionReport_vulnerability.setObjectName(u"actionReport_vulnerability")
        self.actionDiscord = QAction(MainWindow)
        self.actionDiscord.setObjectName(u"actionDiscord")
        self.actionExtensions = QAction(MainWindow)
        self.actionExtensions.setObjectName(u"actionExtensions")
        self.actionShow_image_preview = QAction(MainWindow)
        self.actionShow_image_preview.setObjectName(u"actionShow_image_preview")
        self.actionShow_image_preview.setCheckable(True)
        self.actionImage_to_new_layer = QAction(MainWindow)
        self.actionImage_to_new_layer.setObjectName(u"actionImage_to_new_layer")
        self.actionImage_to_new_layer.setCheckable(True)
        self.actionAuto_export_images = QAction(MainWindow)
        self.actionAuto_export_images.setObjectName(u"actionAuto_export_images")
        self.actionAuto_export_images.setCheckable(True)
        self.actionImage_export_settings = QAction(MainWindow)
        self.actionImage_export_settings.setObjectName(u"actionImage_export_settings")
        self.actionCheck_for_latest_version_on_startup = QAction(MainWindow)
        self.actionCheck_for_latest_version_on_startup.setObjectName(u"actionCheck_for_latest_version_on_startup")
        self.actionCheck_for_latest_version_on_startup.setCheckable(True)
        self.actionModel_Merger = QAction(MainWindow)
        self.actionModel_Merger.setObjectName(u"actionModel_Merger")
        self.actionSaturation_Filter = QAction(MainWindow)
        self.actionSaturation_Filter.setObjectName(u"actionSaturation_Filter")
        self.actionColor_Balance_2 = QAction(MainWindow)
        self.actionColor_Balance_2.setObjectName(u"actionColor_Balance_2")
        self.actionRGB_Noise = QAction(MainWindow)
        self.actionRGB_Noise.setObjectName(u"actionRGB_Noise")
        self.actionGaussian_Blur_2 = QAction(MainWindow)
        self.actionGaussian_Blur_2.setObjectName(u"actionGaussian_Blur_2")
        self.actionBox_Blur_2 = QAction(MainWindow)
        self.actionBox_Blur_2.setObjectName(u"actionBox_Blur_2")
        self.actionRotate_90_clockwise = QAction(MainWindow)
        self.actionRotate_90_clockwise.setObjectName(u"actionRotate_90_clockwise")
        self.actionRotate_90_counter_clockwise = QAction(MainWindow)
        self.actionRotate_90_counter_clockwise.setObjectName(u"actionRotate_90_counter_clockwise")
        self.actionSave_prompt = QAction(MainWindow)
        self.actionSave_prompt.setObjectName(u"actionSave_prompt")
        self.actionShow_Active_Image_Area = QAction(MainWindow)
        self.actionShow_Active_Image_Area.setObjectName(u"actionShow_Active_Image_Area")
        self.actionShow_Active_Image_Area.setCheckable(True)
        self.actionImage_Interpolation = QAction(MainWindow)
        self.actionImage_Interpolation.setObjectName(u"actionImage_Interpolation")
        self.actionImage_interpolation = QAction(MainWindow)
        self.actionImage_interpolation.setObjectName(u"actionImage_interpolation")
        self.actionFilm = QAction(MainWindow)
        self.actionFilm.setObjectName(u"actionFilm")
        self.actionDeterministic_generation = QAction(MainWindow)
        self.actionDeterministic_generation.setObjectName(u"actionDeterministic_generation")
        self.actionDark_mode = QAction(MainWindow)
        self.actionDark_mode.setObjectName(u"actionDark_mode")
        self.actionDark_mode.setCheckable(True)
        self.actionConsole_window = QAction(MainWindow)
        self.actionConsole_window.setObjectName(u"actionConsole_window")
        self.actionSettings = QAction(MainWindow)
        self.actionSettings.setObjectName(u"actionSettings")
        self.actionPrompt_Browser = QAction(MainWindow)
        self.actionPrompt_Browser.setObjectName(u"actionPrompt_Browser")
        self.actionClear_all_prompts = QAction(MainWindow)
        self.actionClear_all_prompts.setObjectName(u"actionClear_all_prompts")
        self.actionUndo_2 = QAction(MainWindow)
        self.actionUndo_2.setObjectName(u"actionUndo_2")
        self.actionUndo_2.setIcon(icon1)
        self.actionRedo_2 = QAction(MainWindow)
        self.actionRedo_2.setObjectName(u"actionRedo_2")
        self.actionRedo_2.setIcon(icon2)
        self.actionCut = QAction(MainWindow)
        self.actionCut.setObjectName(u"actionCut")
        self.actionHalftone = QAction(MainWindow)
        self.actionHalftone.setObjectName(u"actionHalftone")
        self.actionQuick_Export = QAction(MainWindow)
        self.actionQuick_Export.setObjectName(u"actionQuick_Export")
        self.actionRegistration_error = QAction(MainWindow)
        self.actionRegistration_error.setObjectName(u"actionRegistration_error")
        self.actionHuggingface_Cache_manager = QAction(MainWindow)
        self.actionHuggingface_Cache_manager.setObjectName(u"actionHuggingface_Cache_manager")
        self.actionModel_Manager = QAction(MainWindow)
        self.actionModel_Manager.setObjectName(u"actionModel_Manager")
        self.actionModel_Manager_2 = QAction(MainWindow)
        self.actionModel_Manager_2.setObjectName(u"actionModel_Manager_2")
        self.actionControlNet = QAction(MainWindow)
        self.actionControlNet.setObjectName(u"actionControlNet")
        self.actionPrompt_Builder = QAction(MainWindow)
        self.actionPrompt_Builder.setObjectName(u"actionPrompt_Builder")
        self.actionEmbeddings = QAction(MainWindow)
        self.actionEmbeddings.setObjectName(u"actionEmbeddings")
        self.actionLoRA = QAction(MainWindow)
        self.actionLoRA.setObjectName(u"actionLoRA")
        self.actionPen = QAction(MainWindow)
        self.actionPen.setObjectName(u"actionPen")
        self.actionStableDiffusion = QAction(MainWindow)
        self.actionStableDiffusion.setObjectName(u"actionStableDiffusion")
        self.actionKandinsky = QAction(MainWindow)
        self.actionKandinsky.setObjectName(u"actionKandinsky")
        self.actionShap_E = QAction(MainWindow)
        self.actionShap_E.setObjectName(u"actionShap_E")
        self.actionRun_setup_wizard = QAction(MainWindow)
        self.actionRun_setup_wizard.setObjectName(u"actionRun_setup_wizard")
        self.actionBrowse_AI_Runner_Path = QAction(MainWindow)
        self.actionBrowse_AI_Runner_Path.setObjectName(u"actionBrowse_AI_Runner_Path")
        self.actionBrowse_Images_Path = QAction(MainWindow)
        self.actionBrowse_Images_Path.setObjectName(u"actionBrowse_Images_Path")
        self.actionBrowse_Images_Path_2 = QAction(MainWindow)
        self.actionBrowse_Images_Path_2.setObjectName(u"actionBrowse_Images_Path_2")
        self.actionBrowse_Videos_Path = QAction(MainWindow)
        self.actionBrowse_Videos_Path.setObjectName(u"actionBrowse_Videos_Path")
        self.actionBrowse_Gifs_Path = QAction(MainWindow)
        self.actionBrowse_Gifs_Path.setObjectName(u"actionBrowse_Gifs_Path")
        self.actionTxt2img_Img2img_Models = QAction(MainWindow)
        self.actionTxt2img_Img2img_Models.setObjectName(u"actionTxt2img_Img2img_Models")
        self.actionInpaint_Outpaint_Models = QAction(MainWindow)
        self.actionInpaint_Outpaint_Models.setObjectName(u"actionInpaint_Outpaint_Models")
        self.actionDepth2img_Models = QAction(MainWindow)
        self.actionDepth2img_Models.setObjectName(u"actionDepth2img_Models")
        self.actionPix2pix = QAction(MainWindow)
        self.actionPix2pix.setObjectName(u"actionPix2pix")
        self.actionUpscale = QAction(MainWindow)
        self.actionUpscale.setObjectName(u"actionUpscale")
        self.actionSuperresolution = QAction(MainWindow)
        self.actionSuperresolution.setObjectName(u"actionSuperresolution")
        self.actionTxt2vid = QAction(MainWindow)
        self.actionTxt2vid.setObjectName(u"actionTxt2vid")
        self.actionActive_Grid = QAction(MainWindow)
        self.actionActive_Grid.setObjectName(u"actionActive_Grid")
        self.actionDeterministic_Batches = QAction(MainWindow)
        self.actionDeterministic_Batches.setObjectName(u"actionDeterministic_Batches")
        self.actionStandard_Batches = QAction(MainWindow)
        self.actionStandard_Batches.setObjectName(u"actionStandard_Batches")
        self.actionLLM_beta = QAction(MainWindow)
        self.actionLLM_beta.setObjectName(u"actionLLM_beta")
        self.actionReset_Settings_2 = QAction(MainWindow)
        self.actionReset_Settings_2.setObjectName(u"actionReset_Settings_2")
        self.actionImage_Browser = QAction(MainWindow)
        self.actionImage_Browser.setObjectName(u"actionImage_Browser")
        self.actionModel_Manager_3 = QAction(MainWindow)
        self.actionModel_Manager_3.setObjectName(u"actionModel_Manager_3")
        self.actionImport_input_image = QAction(MainWindow)
        self.actionImport_input_image.setObjectName(u"actionImport_input_image")
        self.actionExport_input_image = QAction(MainWindow)
        self.actionExport_input_image.setObjectName(u"actionExport_input_image")
        self.actionImport_2 = QAction(MainWindow)
        self.actionImport_2.setObjectName(u"actionImport_2")
        self.actionExport_image = QAction(MainWindow)
        self.actionExport_image.setObjectName(u"actionExport_image")
        self.actionImport_Image = QAction(MainWindow)
        self.actionImport_Image.setObjectName(u"actionImport_Image")
        self.actionExport_Image = QAction(MainWindow)
        self.actionExport_Image.setObjectName(u"actionExport_Image")
        self.actionImport_3 = QAction(MainWindow)
        self.actionImport_3.setObjectName(u"actionImport_3")
        self.actionExport_2 = QAction(MainWindow)
        self.actionExport_2.setObjectName(u"actionExport_2")
        self.controlnet_import = QAction(MainWindow)
        self.controlnet_import.setObjectName(u"controlnet_import")
        self.controlnet_export = QAction(MainWindow)
        self.controlnet_export.setObjectName(u"controlnet_export")
        self.drawingpad_import = QAction(MainWindow)
        self.drawingpad_import.setObjectName(u"drawingpad_import")
        self.drawingpad_export = QAction(MainWindow)
        self.drawingpad_export.setObjectName(u"drawingpad_export")
        self.actionGenerate_while_drawing = QAction(MainWindow)
        self.actionGenerate_while_drawing.setObjectName(u"actionGenerate_while_drawing")
        self.actionGenerate_while_drawing.setCheckable(True)
        self.actionOverlay_input_image = QAction(MainWindow)
        self.actionOverlay_input_image.setObjectName(u"actionOverlay_input_image")
        self.actionOverlay_input_image.setCheckable(True)
        self.enable_controlnet = QAction(MainWindow)
        self.enable_controlnet.setObjectName(u"enable_controlnet")
        self.enable_controlnet.setCheckable(True)
        self.actionUnload_LLm = QAction(MainWindow)
        self.actionUnload_LLm.setObjectName(u"actionUnload_LLm")
        self.actionUnload_Image_model = QAction(MainWindow)
        self.actionUnload_Image_model.setObjectName(u"actionUnload_Image_model")
        self.actionClear_Memory = QAction(MainWindow)
        self.actionClear_Memory.setObjectName(u"actionClear_Memory")
        self.actionSafety_Checker = QAction(MainWindow)
        self.actionSafety_Checker.setObjectName(u"actionSafety_Checker")
        self.actionSafety_Checker.setCheckable(True)
        self.actionSafety_Checker.setChecked(False)
        self.outpaint_import = QAction(MainWindow)
        self.outpaint_import.setObjectName(u"outpaint_import")
        self.outpaint_export = QAction(MainWindow)
        self.outpaint_export.setObjectName(u"outpaint_export")
        self.outpaint_enabled = QAction(MainWindow)
        self.outpaint_enabled.setObjectName(u"outpaint_enabled")
        self.outpaint_enabled.setCheckable(True)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setEnabled(True)
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.MinimumExpanding)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy1)
        self.centralwidget.setMinimumSize(QSize(0, 0))
        self.centralwidget.setLayoutDirection(Qt.LeftToRight)
        self.gridLayout_3 = QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.gridLayout_3.setContentsMargins(1, 0, 1, 0)
        self.header_widget = QFrame(self.centralwidget)
        self.header_widget.setObjectName(u"header_widget")
        self.header_widget.setEnabled(True)
        self.header_widget.setMaximumSize(QSize(16777215, 48))
        self.header_widget.setFrameShape(QFrame.Panel)
        self.header_widget.setFrameShadow(QFrame.Raised)
        self.horizontalLayout = QHBoxLayout(self.header_widget)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.scrollArea_3 = QScrollArea(self.header_widget)
        self.scrollArea_3.setObjectName(u"scrollArea_3")
        self.scrollArea_3.setFrameShape(QFrame.NoFrame)
        self.scrollArea_3.setFrameShadow(QFrame.Sunken)
        self.scrollArea_3.setMidLineWidth(0)
        self.scrollArea_3.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.scrollArea_3.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollAreaWidgetContents_3 = QWidget()
        self.scrollAreaWidgetContents_3.setObjectName(u"scrollAreaWidgetContents_3")
        self.scrollAreaWidgetContents_3.setGeometry(QRect(0, 0, 1119, 46))
        self.horizontalLayout_2 = QHBoxLayout(self.scrollAreaWidgetContents_3)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.text_generator_header_tools = QFrame(self.scrollAreaWidgetContents_3)
        self.text_generator_header_tools.setObjectName(u"text_generator_header_tools")
        self.text_generator_header_tools.setFrameShape(QFrame.StyledPanel)
        self.text_generator_header_tools.setFrameShadow(QFrame.Raised)
        self.horizontalLayout_5 = QHBoxLayout(self.text_generator_header_tools)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)

        self.horizontalLayout_2.addWidget(self.text_generator_header_tools)

        self.image_generator_header_tools = QFrame(self.scrollAreaWidgetContents_3)
        self.image_generator_header_tools.setObjectName(u"image_generator_header_tools")
        self.image_generator_header_tools.setFrameShape(QFrame.NoFrame)
        self.image_generator_header_tools.setFrameShadow(QFrame.Sunken)
        self.horizontalLayout_4 = QHBoxLayout(self.image_generator_header_tools)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.image_generator_header_tool_buttons = QWidget(self.image_generator_header_tools)
        self.image_generator_header_tool_buttons.setObjectName(u"image_generator_header_tool_buttons")
        self.horizontalLayout_3 = QHBoxLayout(self.image_generator_header_tool_buttons)
        self.horizontalLayout_3.setSpacing(6)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(6, 0, 6, 0)
        self.file_new_button = QPushButton(self.image_generator_header_tool_buttons)
        self.file_new_button.setObjectName(u"file_new_button")
        self.file_new_button.setMinimumSize(QSize(36, 36))
        self.file_new_button.setMaximumSize(QSize(36, 36))
        self.file_new_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon3 = QIcon()
        iconThemeName = u"document-new"
        if QIcon.hasThemeIcon(iconThemeName):
            icon3 = QIcon.fromTheme(iconThemeName)
        else:
            icon3.addFile(u"../../../../../../../../../../../../../../.designer/backup", QSize(), QIcon.Normal, QIcon.Off)

        self.file_new_button.setIcon(icon3)
        self.file_new_button.setIconSize(QSize(24, 24))
        self.file_new_button.setFlat(True)

        self.horizontalLayout_3.addWidget(self.file_new_button)

        self.open_button = QPushButton(self.image_generator_header_tool_buttons)
        self.open_button.setObjectName(u"open_button")
        self.open_button.setMinimumSize(QSize(36, 36))
        self.open_button.setMaximumSize(QSize(36, 36))
        self.open_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon4 = QIcon()
        iconThemeName = u"document-open"
        if QIcon.hasThemeIcon(iconThemeName):
            icon4 = QIcon.fromTheme(iconThemeName)
        else:
            icon4.addFile(u"../../../../../../../../../../../../../../src/icons/034-folder.png", QSize(), QIcon.Normal, QIcon.Off)

        self.open_button.setIcon(icon4)
        self.open_button.setIconSize(QSize(24, 24))
        self.open_button.setFlat(True)

        self.horizontalLayout_3.addWidget(self.open_button)

        self.save_button = QPushButton(self.image_generator_header_tool_buttons)
        self.save_button.setObjectName(u"save_button")
        self.save_button.setMinimumSize(QSize(36, 36))
        self.save_button.setMaximumSize(QSize(36, 36))
        self.save_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon5 = QIcon()
        iconThemeName = u"document-save"
        if QIcon.hasThemeIcon(iconThemeName):
            icon5 = QIcon.fromTheme(iconThemeName)
        else:
            icon5.addFile(u"../../../../../../../../../../../../../../src/icons/033-diskette.png", QSize(), QIcon.Normal, QIcon.Off)

        self.save_button.setIcon(icon5)
        self.save_button.setIconSize(QSize(24, 24))
        self.save_button.setFlat(True)

        self.horizontalLayout_3.addWidget(self.save_button)

        self.export_button = QPushButton(self.image_generator_header_tool_buttons)
        self.export_button.setObjectName(u"export_button")
        self.export_button.setMinimumSize(QSize(36, 36))
        self.export_button.setMaximumSize(QSize(36, 36))
        self.export_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon6 = QIcon()
        iconThemeName = u"document-send"
        if QIcon.hasThemeIcon(iconThemeName):
            icon6 = QIcon.fromTheme(iconThemeName)
        else:
            icon6.addFile(u"../../../../../../../../../../../../../../src/icons/export.png", QSize(), QIcon.Normal, QIcon.Off)

        self.export_button.setIcon(icon6)
        self.export_button.setIconSize(QSize(24, 24))
        self.export_button.setFlat(True)

        self.horizontalLayout_3.addWidget(self.export_button)

        self.line_2 = QFrame(self.image_generator_header_tool_buttons)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setFrameShape(QFrame.VLine)
        self.line_2.setFrameShadow(QFrame.Sunken)

        self.horizontalLayout_3.addWidget(self.line_2)

        self.undo_button = QPushButton(self.image_generator_header_tool_buttons)
        self.undo_button.setObjectName(u"undo_button")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.undo_button.sizePolicy().hasHeightForWidth())
        self.undo_button.setSizePolicy(sizePolicy2)
        self.undo_button.setMinimumSize(QSize(36, 36))
        self.undo_button.setMaximumSize(QSize(36, 36))
        self.undo_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.undo_button.setStyleSheet(u"border-color: rgb(61, 56, 70);")
        icon7 = QIcon()
        iconThemeName = u"edit-undo"
        if QIcon.hasThemeIcon(iconThemeName):
            icon7 = QIcon.fromTheme(iconThemeName)
        else:
            icon7.addFile(u"../../../../../../../../../../../../../../.designer/backup", QSize(), QIcon.Normal, QIcon.Off)

        self.undo_button.setIcon(icon7)
        self.undo_button.setIconSize(QSize(24, 24))
        self.undo_button.setFlat(True)

        self.horizontalLayout_3.addWidget(self.undo_button)

        self.redo_button = QPushButton(self.image_generator_header_tool_buttons)
        self.redo_button.setObjectName(u"redo_button")
        sizePolicy2.setHeightForWidth(self.redo_button.sizePolicy().hasHeightForWidth())
        self.redo_button.setSizePolicy(sizePolicy2)
        self.redo_button.setMinimumSize(QSize(36, 36))
        self.redo_button.setMaximumSize(QSize(36, 36))
        self.redo_button.setCursor(QCursor(Qt.PointingHandCursor))
        self.redo_button.setStyleSheet(u"border-color: rgb(61, 56, 70);")
        icon8 = QIcon()
        iconThemeName = u"edit-redo"
        if QIcon.hasThemeIcon(iconThemeName):
            icon8 = QIcon.fromTheme(iconThemeName)
        else:
            icon8.addFile(u"../../../../../../../../../../../../../../src/icons/008-redo.png", QSize(), QIcon.Normal, QIcon.Off)

        self.redo_button.setIcon(icon8)
        self.redo_button.setIconSize(QSize(24, 24))
        self.redo_button.setFlat(True)

        self.horizontalLayout_3.addWidget(self.redo_button)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_3.addItem(self.horizontalSpacer)


        self.horizontalLayout_4.addWidget(self.image_generator_header_tool_buttons)


        self.horizontalLayout_2.addWidget(self.image_generator_header_tools)

        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)

        self.horizontalLayout.addWidget(self.scrollArea_3)


        self.gridLayout_3.addWidget(self.header_widget, 0, 0, 1, 1)

        self.mode_tab_widget = QTabWidget(self.centralwidget)
        self.mode_tab_widget.setObjectName(u"mode_tab_widget")
        self.mode_tab_widget.setAutoFillBackground(False)
        self.mode_tab_widget.setStyleSheet(u"QTabWidget#mode_tab_widget::pane { border: 0; background: transparent; }")
        self.mode_tab_widget.setTabShape(QTabWidget.Rounded)
        self.mode_tab_widget.setTabBarAutoHide(False)
        self.art = QWidget()
        self.art.setObjectName(u"art")
        self.gridLayout_6 = QGridLayout(self.art)
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.content_splitter = QSplitter(self.art)
        self.content_splitter.setObjectName(u"content_splitter")
        self.content_splitter.setOrientation(Qt.Horizontal)
        self.generator_widget = GeneratorForm(self.content_splitter)
        self.generator_widget.setObjectName(u"generator_widget")
        self.content_splitter.addWidget(self.generator_widget)
        self.canvas_widget = QWidget(self.content_splitter)
        self.canvas_widget.setObjectName(u"canvas_widget")
        self.canvas_widget.setMinimumSize(QSize(512, 0))
        self.gridLayout_5 = QGridLayout(self.canvas_widget)
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.center_tab = QTabWidget(self.canvas_widget)
        self.center_tab.setObjectName(u"center_tab")
        self.center_tab.setStyleSheet(u"")
        self.canvas_tab = QWidget()
        self.canvas_tab.setObjectName(u"canvas_tab")
        self.gridLayout_4 = QGridLayout(self.canvas_tab)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.canvas_widget_2 = CanvasWidget(self.canvas_tab)
        self.canvas_widget_2.setObjectName(u"canvas_widget_2")
        sizePolicy1.setHeightForWidth(self.canvas_widget_2.sizePolicy().hasHeightForWidth())
        self.canvas_widget_2.setSizePolicy(sizePolicy1)
        self.canvas_widget_2.setMinimumSize(QSize(0, 0))
        self.canvas_widget_2.setMaximumSize(QSize(16777215, 16777215))
        self.canvas_widget_2.setCursor(QCursor(Qt.ArrowCursor))
        self.canvas_widget_2.setAcceptDrops(True)

        self.gridLayout_4.addWidget(self.canvas_widget_2, 0, 0, 1, 1)

        self.center_tab.addTab(self.canvas_tab, "")
        self.model_manager_tab = QWidget()
        self.model_manager_tab.setObjectName(u"model_manager_tab")
        self.gridLayout_7 = QGridLayout(self.model_manager_tab)
        self.gridLayout_7.setObjectName(u"gridLayout_7")
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.model_manager = ModelManagerWidget(self.model_manager_tab)
        self.model_manager.setObjectName(u"model_manager")

        self.gridLayout_7.addWidget(self.model_manager, 0, 0, 1, 1)

        self.center_tab.addTab(self.model_manager_tab, "")

        self.gridLayout_5.addWidget(self.center_tab, 0, 0, 1, 1)

        self.content_splitter.addWidget(self.canvas_widget)
        self.scrollArea = QScrollArea(self.content_splitter)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setMaximumSize(QSize(16777215, 16777215))
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 347, 756))
        self.gridLayout = QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.splitter = QSplitter(self.scrollAreaWidgetContents)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setMaximumSize(QSize(16777215, 16777215))
        self.splitter.setOrientation(Qt.Vertical)
        self.tool_tab_widget = QTabWidget(self.splitter)
        self.tool_tab_widget.setObjectName(u"tool_tab_widget")
        self.tool_tab_widget.setMinimumSize(QSize(0, 0))
        self.tool_tab_widget.setMaximumSize(QSize(16777215, 16777215))
        self.tool_tab_widget.setAcceptDrops(False)
        self.tab_pen = QWidget()
        self.tab_pen.setObjectName(u"tab_pen")
        self.gridLayout_8 = QGridLayout(self.tab_pen)
        self.gridLayout_8.setObjectName(u"gridLayout_8")
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.brush_container_widget = BrushContainerWidget(self.tab_pen)
        self.brush_container_widget.setObjectName(u"brush_container_widget")

        self.gridLayout_8.addWidget(self.brush_container_widget, 0, 0, 1, 1)

        self.tool_tab_widget.addTab(self.tab_pen, "")
        self.tab_active_grid = QWidget()
        self.tab_active_grid.setObjectName(u"tab_active_grid")
        self.gridLayout_12 = QGridLayout(self.tab_active_grid)
        self.gridLayout_12.setObjectName(u"gridLayout_12")
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.active_grid_settings_widget = ActiveGridSettingsWidget(self.tab_active_grid)
        self.active_grid_settings_widget.setObjectName(u"active_grid_settings_widget")

        self.gridLayout_12.addWidget(self.active_grid_settings_widget, 0, 0, 1, 1)

        self.tool_tab_widget.addTab(self.tab_active_grid, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.gridLayout_10 = QGridLayout(self.tab_2)
        self.gridLayout_10.setObjectName(u"gridLayout_10")
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.upscale_widget = UpscaleWidget(self.tab_2)
        self.upscale_widget.setObjectName(u"upscale_widget")

        self.gridLayout_10.addWidget(self.upscale_widget, 0, 0, 1, 1)

        self.tool_tab_widget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.gridLayout_11 = QGridLayout(self.tab_3)
        self.gridLayout_11.setObjectName(u"gridLayout_11")
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.widget = StableDiffusionSettingsWidget(self.tab_3)
        self.widget.setObjectName(u"widget")

        self.gridLayout_11.addWidget(self.widget, 0, 0, 1, 1)

        self.tool_tab_widget.addTab(self.tab_3, "")
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.gridLayout_2 = QGridLayout(self.tab)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.llm_preferences_widget = LLMSettingsWidget(self.tab)
        self.llm_preferences_widget.setObjectName(u"llm_preferences_widget")

        self.gridLayout_2.addWidget(self.llm_preferences_widget, 0, 0, 1, 1)

        self.tool_tab_widget.addTab(self.tab, "")
        self.splitter.addWidget(self.tool_tab_widget)

        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.content_splitter.addWidget(self.scrollArea)

        self.gridLayout_6.addWidget(self.content_splitter, 0, 0, 1, 1)

        self.button_menu = QFrame(self.art)
        self.button_menu.setObjectName(u"button_menu")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Preferred)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.button_menu.sizePolicy().hasHeightForWidth())
        self.button_menu.setSizePolicy(sizePolicy3)
        self.button_menu.setMinimumSize(QSize(0, 0))
        self.button_menu.setMaximumSize(QSize(65, 16777215))
        self.button_menu.setFrameShape(QFrame.NoFrame)
        self.button_menu.setFrameShadow(QFrame.Raised)
        self.verticalLayout = QVBoxLayout(self.button_menu)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(4, 9, 4, 9)
        self.toggle_active_grid_area_button = QPushButton(self.button_menu)
        self.toggle_active_grid_area_button.setObjectName(u"toggle_active_grid_area_button")
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.Maximum, QSizePolicy.Policy.MinimumExpanding)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.toggle_active_grid_area_button.sizePolicy().hasHeightForWidth())
        self.toggle_active_grid_area_button.setSizePolicy(sizePolicy4)
        self.toggle_active_grid_area_button.setMinimumSize(QSize(50, 45))
        self.toggle_active_grid_area_button.setMaximumSize(QSize(50, 45))
        self.toggle_active_grid_area_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon9 = QIcon()
        icon9.addFile(u":/icons/light/object-selected-icon.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.toggle_active_grid_area_button.setIcon(icon9)
        self.toggle_active_grid_area_button.setIconSize(QSize(18, 18))
        self.toggle_active_grid_area_button.setCheckable(True)
        self.toggle_active_grid_area_button.setFlat(True)

        self.verticalLayout.addWidget(self.toggle_active_grid_area_button)

        self.toggle_select_button = QPushButton(self.button_menu)
        self.toggle_select_button.setObjectName(u"toggle_select_button")
        sizePolicy4.setHeightForWidth(self.toggle_select_button.sizePolicy().hasHeightForWidth())
        self.toggle_select_button.setSizePolicy(sizePolicy4)
        self.toggle_select_button.setMinimumSize(QSize(50, 45))
        self.toggle_select_button.setMaximumSize(QSize(50, 45))
        icon10 = QIcon()
        icon10.addFile(u":/icons/light/select-svgrepo-com.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.toggle_select_button.setIcon(icon10)
        self.toggle_select_button.setIconSize(QSize(20, 20))
        self.toggle_select_button.setCheckable(True)
        self.toggle_select_button.setFlat(True)

        self.verticalLayout.addWidget(self.toggle_select_button)

        self.line_7 = QFrame(self.button_menu)
        self.line_7.setObjectName(u"line_7")
        self.line_7.setFrameShape(QFrame.HLine)
        self.line_7.setFrameShadow(QFrame.Sunken)

        self.verticalLayout.addWidget(self.line_7)

        self.toggle_brush_button = QPushButton(self.button_menu)
        self.toggle_brush_button.setObjectName(u"toggle_brush_button")
        sizePolicy4.setHeightForWidth(self.toggle_brush_button.sizePolicy().hasHeightForWidth())
        self.toggle_brush_button.setSizePolicy(sizePolicy4)
        self.toggle_brush_button.setMinimumSize(QSize(50, 45))
        self.toggle_brush_button.setMaximumSize(QSize(50, 45))
        self.toggle_brush_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon11 = QIcon()
        icon11.addFile(u":/icons/light/pencil-icon.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.toggle_brush_button.setIcon(icon11)
        self.toggle_brush_button.setIconSize(QSize(18, 18))
        self.toggle_brush_button.setCheckable(True)
        self.toggle_brush_button.setFlat(True)

        self.verticalLayout.addWidget(self.toggle_brush_button)

        self.toggle_eraser_button = QPushButton(self.button_menu)
        self.toggle_eraser_button.setObjectName(u"toggle_eraser_button")
        sizePolicy4.setHeightForWidth(self.toggle_eraser_button.sizePolicy().hasHeightForWidth())
        self.toggle_eraser_button.setSizePolicy(sizePolicy4)
        self.toggle_eraser_button.setMinimumSize(QSize(50, 45))
        self.toggle_eraser_button.setMaximumSize(QSize(50, 45))
        self.toggle_eraser_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon12 = QIcon()
        icon12.addFile(u":/icons/light/eraser-icon.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.toggle_eraser_button.setIcon(icon12)
        self.toggle_eraser_button.setIconSize(QSize(18, 18))
        self.toggle_eraser_button.setCheckable(True)
        self.toggle_eraser_button.setFlat(True)

        self.verticalLayout.addWidget(self.toggle_eraser_button)

        self.line = QFrame(self.button_menu)
        self.line.setObjectName(u"line")
        sizePolicy5 = QSizePolicy(QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.Fixed)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy5)
        self.line.setFrameShape(QFrame.HLine)
        self.line.setFrameShadow(QFrame.Sunken)

        self.verticalLayout.addWidget(self.line)

        self.toggle_grid_button = QPushButton(self.button_menu)
        self.toggle_grid_button.setObjectName(u"toggle_grid_button")
        sizePolicy4.setHeightForWidth(self.toggle_grid_button.sizePolicy().hasHeightForWidth())
        self.toggle_grid_button.setSizePolicy(sizePolicy4)
        self.toggle_grid_button.setMinimumSize(QSize(50, 45))
        self.toggle_grid_button.setMaximumSize(QSize(50, 45))
        self.toggle_grid_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon13 = QIcon()
        icon13.addFile(u":/icons/light/frame-grid-icon.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.toggle_grid_button.setIcon(icon13)
        self.toggle_grid_button.setIconSize(QSize(18, 18))
        self.toggle_grid_button.setCheckable(True)
        self.toggle_grid_button.setFlat(True)

        self.verticalLayout.addWidget(self.toggle_grid_button)

        self.focus_button = QPushButton(self.button_menu)
        self.focus_button.setObjectName(u"focus_button")
        sizePolicy4.setHeightForWidth(self.focus_button.sizePolicy().hasHeightForWidth())
        self.focus_button.setSizePolicy(sizePolicy4)
        self.focus_button.setMinimumSize(QSize(50, 45))
        self.focus_button.setMaximumSize(QSize(50, 45))
        self.focus_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon14 = QIcon()
        icon14.addFile(u":/icons/light/circle-center-icon.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.focus_button.setIcon(icon14)
        self.focus_button.setIconSize(QSize(18, 18))
        self.focus_button.setFlat(True)

        self.verticalLayout.addWidget(self.focus_button)

        self.line_4 = QFrame(self.button_menu)
        self.line_4.setObjectName(u"line_4")
        sizePolicy5.setHeightForWidth(self.line_4.sizePolicy().hasHeightForWidth())
        self.line_4.setSizePolicy(sizePolicy5)
        self.line_4.setFrameShape(QFrame.HLine)
        self.line_4.setFrameShadow(QFrame.Sunken)

        self.verticalLayout.addWidget(self.line_4)

        self.ai_button = QPushButton(self.button_menu)
        self.ai_button.setObjectName(u"ai_button")
        self.ai_button.setMinimumSize(QSize(50, 45))
        self.ai_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon15 = QIcon()
        icon15.addFile(u":/icons/light/artificial-intelligence-ai-chip-icon.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.ai_button.setIcon(icon15)
        self.ai_button.setIconSize(QSize(18, 20))
        self.ai_button.setCheckable(True)
        self.ai_button.setFlat(True)

        self.verticalLayout.addWidget(self.ai_button)

        self.line_3 = QFrame(self.button_menu)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setFrameShape(QFrame.HLine)
        self.line_3.setFrameShadow(QFrame.Sunken)

        self.verticalLayout.addWidget(self.line_3)

        self.model_manager_button = QPushButton(self.button_menu)
        self.model_manager_button.setObjectName(u"model_manager_button")
        sizePolicy4.setHeightForWidth(self.model_manager_button.sizePolicy().hasHeightForWidth())
        self.model_manager_button.setSizePolicy(sizePolicy4)
        self.model_manager_button.setMinimumSize(QSize(50, 45))
        self.model_manager_button.setMaximumSize(QSize(50, 45))
        self.model_manager_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon16 = QIcon()
        icon16.addFile(u":/icons/light/tech-icon.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.model_manager_button.setIcon(icon16)
        self.model_manager_button.setIconSize(QSize(18, 18))
        self.model_manager_button.setCheckable(True)
        self.model_manager_button.setFlat(True)

        self.verticalLayout.addWidget(self.model_manager_button)

        self.line_5 = QFrame(self.button_menu)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setFrameShape(QFrame.HLine)
        self.line_5.setFrameShadow(QFrame.Sunken)

        self.verticalLayout.addWidget(self.line_5)

        self.settings_button = QPushButton(self.button_menu)
        self.settings_button.setObjectName(u"settings_button")
        sizePolicy4.setHeightForWidth(self.settings_button.sizePolicy().hasHeightForWidth())
        self.settings_button.setSizePolicy(sizePolicy4)
        self.settings_button.setMinimumSize(QSize(50, 45))
        self.settings_button.setMaximumSize(QSize(50, 45))
        self.settings_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon17 = QIcon()
        icon17.addFile(u":/icons/light/setting-line-icon.svg", QSize(), QIcon.Normal, QIcon.Off)
        self.settings_button.setIcon(icon17)
        self.settings_button.setIconSize(QSize(18, 18))
        self.settings_button.setFlat(True)

        self.verticalLayout.addWidget(self.settings_button)

        self.line_8 = QFrame(self.button_menu)
        self.line_8.setObjectName(u"line_8")
        self.line_8.setFrameShape(QFrame.HLine)
        self.line_8.setFrameShadow(QFrame.Sunken)

        self.verticalLayout.addWidget(self.line_8)

        self.tts_button = QPushButton(self.button_menu)
        self.tts_button.setObjectName(u"tts_button")
        self.tts_button.setMinimumSize(QSize(50, 45))
        self.tts_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon18 = QIcon(QIcon.fromTheme(u"audio-volume-high"))
        self.tts_button.setIcon(icon18)
        self.tts_button.setIconSize(QSize(32, 32))
        self.tts_button.setCheckable(True)
        self.tts_button.setFlat(True)

        self.verticalLayout.addWidget(self.tts_button)

        self.v2t_button = QPushButton(self.button_menu)
        self.v2t_button.setObjectName(u"v2t_button")
        self.v2t_button.setMinimumSize(QSize(50, 45))
        self.v2t_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon19 = QIcon(QIcon.fromTheme(u"audio-input-microphone"))
        self.v2t_button.setIcon(icon19)
        self.v2t_button.setIconSize(QSize(18, 18))
        self.v2t_button.setCheckable(True)
        self.v2t_button.setFlat(True)

        self.verticalLayout.addWidget(self.v2t_button)

        self.ocr_button = QPushButton(self.button_menu)
        self.ocr_button.setObjectName(u"ocr_button")
        self.ocr_button.setMinimumSize(QSize(50, 45))
        self.ocr_button.setCursor(QCursor(Qt.PointingHandCursor))
        icon20 = QIcon(QIcon.fromTheme(u"camera-web"))
        self.ocr_button.setIcon(icon20)
        self.ocr_button.setIconSize(QSize(16, 16))
        self.ocr_button.setCheckable(True)
        self.ocr_button.setFlat(True)

        self.verticalLayout.addWidget(self.ocr_button)

        self.verticalSpacer = QSpacerItem(20, 10, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout.addItem(self.verticalSpacer)


        self.gridLayout_6.addWidget(self.button_menu, 0, 1, 1, 1)

        self.mode_tab_widget.addTab(self.art, "")

        self.gridLayout_3.addWidget(self.mode_tab_widget, 1, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1123, 22))
        font1 = QFont()
        font1.setPointSize(11)
        self.menubar.setFont(font1)
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuFilters = QMenu(self.menubar)
        self.menuFilters.setObjectName(u"menuFilters")
        self.menuAbout = QMenu(self.menubar)
        self.menuAbout.setObjectName(u"menuAbout")
        self.menuAbout.setTearOffEnabled(False)
        self.menuImage = QMenu(self.menubar)
        self.menuImage.setObjectName(u"menuImage")
        self.menuCanvas_Image = QMenu(self.menuImage)
        self.menuCanvas_Image.setObjectName(u"menuCanvas_Image")
        self.menuDrawingpad = QMenu(self.menuImage)
        self.menuDrawingpad.setObjectName(u"menuDrawingpad")
        self.menuControlnet = QMenu(self.menuImage)
        self.menuControlnet.setObjectName(u"menuControlnet")
        self.menuOutpaint = QMenu(self.menuImage)
        self.menuOutpaint.setObjectName(u"menuOutpaint")
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        self.menuBrowse_Models_Path = QMenu(self.menuView)
        self.menuBrowse_Models_Path.setObjectName(u"menuBrowse_Models_Path")
        self.menuTools = QMenu(self.menubar)
        self.menuTools.setObjectName(u"menuTools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuImage.menuAction())
        self.menubar.addAction(self.menuFilters.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuFile.addAction(self.actionReset_Settings_2)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionUndo)
        self.menuEdit.addAction(self.actionRedo)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionRotate_90_clockwise)
        self.menuEdit.addAction(self.actionRotate_90_counter_clockwise)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionClear_all_prompts)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionSettings)
        self.menuFilters.addSeparator()
        self.menuFilters.addAction(self.actionInvert)
        self.menuFilters.addAction(self.actionFilm)
        self.menuAbout.addAction(self.actionAbout)
        self.menuAbout.addAction(self.actionBug_report)
        self.menuAbout.addAction(self.actionReport_vulnerability)
        self.menuAbout.addAction(self.actionDiscord)
        self.menuImage.addSeparator()
        self.menuImage.addAction(self.menuCanvas_Image.menuAction())
        self.menuImage.addAction(self.menuDrawingpad.menuAction())
        self.menuImage.addAction(self.menuControlnet.menuAction())
        self.menuImage.addAction(self.menuOutpaint.menuAction())
        self.menuImage.addSeparator()
        self.menuImage.addAction(self.actionGenerate_while_drawing)
        self.menuCanvas_Image.addAction(self.actionImport)
        self.menuCanvas_Image.addAction(self.actionExport)
        self.menuDrawingpad.addAction(self.drawingpad_import)
        self.menuDrawingpad.addAction(self.drawingpad_export)
        self.menuDrawingpad.addSeparator()
        self.menuDrawingpad.addAction(self.actionOverlay_input_image)
        self.menuControlnet.addAction(self.controlnet_import)
        self.menuControlnet.addAction(self.controlnet_export)
        self.menuControlnet.addSeparator()
        self.menuControlnet.addAction(self.enable_controlnet)
        self.menuOutpaint.addAction(self.outpaint_import)
        self.menuOutpaint.addAction(self.outpaint_export)
        self.menuOutpaint.addAction(self.outpaint_enabled)
        self.menuView.addAction(self.actionPrompt_Browser)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionHuggingface_Cache_manager)
        self.menuView.addAction(self.actionBrowse_AI_Runner_Path)
        self.menuView.addAction(self.menuBrowse_Models_Path.menuAction())
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionBrowse_Images_Path_2)
        self.menuView.addSeparator()
        self.menuBrowse_Models_Path.addAction(self.actionTxt2img_Img2img_Models)
        self.menuBrowse_Models_Path.addAction(self.actionInpaint_Outpaint_Models)
        self.menuBrowse_Models_Path.addAction(self.actionDepth2img_Models)
        self.menuBrowse_Models_Path.addAction(self.actionPix2pix)
        self.menuBrowse_Models_Path.addAction(self.actionUpscale)
        self.menuBrowse_Models_Path.addAction(self.actionTxt2vid)
        self.menuTools.addAction(self.actionModel_Manager_3)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionUnload_Image_model)
        self.menuTools.addAction(self.actionUnload_LLm)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionClear_Memory)
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionSafety_Checker)

        self.retranslateUi(MainWindow)
        self.actionHuggingface_Cache_manager.triggered.connect(MainWindow.action_show_hf_cache_manager)
        self.actionModel_Merger.triggered.connect(MainWindow.action_show_model_merger_window)
        self.actionAbout.triggered.connect(MainWindow.action_show_about_window)
        self.actionControlNet.triggered.connect(MainWindow.action_show_controlnet)
        self.actionEmbeddings.triggered.connect(MainWindow.action_show_embeddings)
        self.actionLoRA.triggered.connect(MainWindow.action_show_lora)
        self.actionPen.triggered.connect(MainWindow.action_show_pen)
        self.actionExport.triggered.connect(MainWindow.action_export_image_triggered)
        self.actionNew.triggered.connect(MainWindow.action_new_document_triggered)
        self.actionImport.triggered.connect(MainWindow.action_import_image_triggered)
        self.actionQuit.triggered.connect(MainWindow.action_quit_triggered)
        self.actionPaste.triggered.connect(MainWindow.action_paste_image_triggered)
        self.actionCopy.triggered.connect(MainWindow.action_copy_image_triggered)
        self.actionCut.triggered.connect(MainWindow.action_cut_image_triggered)
        self.actionRotate_90_clockwise.triggered.connect(MainWindow.action_rotate_90_clockwise_triggered)
        self.actionRotate_90_counter_clockwise.triggered.connect(MainWindow.action_rotate_90_counterclockwise_triggered)
        self.actionPrompt_Browser.triggered.connect(MainWindow.action_show_prompt_browser_triggered)
        self.actionClear_all_prompts.triggered.connect(MainWindow.action_clear_all_prompts_triggered)
        self.actionSettings.triggered.connect(MainWindow.action_show_settings)
        self.actionBrowse_AI_Runner_Path.triggered.connect(MainWindow.action_triggered_browse_ai_runner_path)
        self.actionBrowse_Images_Path_2.triggered.connect(MainWindow.action_show_images_path)
        self.actionBrowse_Videos_Path.triggered.connect(MainWindow.action_show_videos_path)
        self.actionTxt2img_Img2img_Models.triggered.connect(MainWindow.action_show_model_path_txt2img)
        self.actionDepth2img_Models.triggered.connect(MainWindow.action_show_model_path_depth2img)
        self.actionInpaint_Outpaint_Models.triggered.connect(MainWindow.action_show_model_path_inpaint)
        self.actionPix2pix.triggered.connect(MainWindow.action_show_model_path_pix2pix)
        self.actionUpscale.triggered.connect(MainWindow.action_show_model_path_upscale)
        self.actionTxt2vid.triggered.connect(MainWindow.action_show_model_path_txt2vid)
        self.actionActive_Grid.triggered.connect(MainWindow.action_show_active_grid)
        self.actionModel_Manager_2.triggered.connect(MainWindow.action_show_model_manager)
        self.actionLLM_beta.triggered.connect(MainWindow.action_show_llm)
        self.settings_button.clicked.connect(MainWindow.action_show_settings)
        self.toggle_grid_button.toggled.connect(MainWindow.action_toggle_grid)
        self.toggle_active_grid_area_button.toggled.connect(MainWindow.action_toggle_active_grid_area)
        self.toggle_eraser_button.toggled.connect(MainWindow.action_toggle_eraser)
        self.toggle_brush_button.toggled.connect(MainWindow.action_toggle_brush)
        self.actionBug_report.triggered.connect(MainWindow.action_open_bug_report)
        self.actionDiscord.triggered.connect(MainWindow.action_open_discord)
        self.actionReport_vulnerability.triggered.connect(MainWindow.action_open_vulnerability_report)
        self.focus_button.clicked.connect(MainWindow.action_center_clicked)
        self.ai_button.toggled.connect(MainWindow.action_ai_toggled)
        self.file_new_button.clicked.connect(MainWindow.action_new_document_triggered)
        self.export_button.clicked.connect(MainWindow.action_export_image_triggered)
        self.undo_button.clicked.connect(MainWindow.action_undo_triggered)
        self.redo_button.clicked.connect(MainWindow.action_redo_triggered)
        self.model_manager_button.toggled.connect(MainWindow.model_manager_toggled)
        self.actionStableDiffusion.triggered.connect(MainWindow.action_show_stablediffusion)
        self.tts_button.toggled.connect(MainWindow.tts_button_toggled)
        self.v2t_button.toggled.connect(MainWindow.v2t_button_toggled)
        self.ocr_button.toggled.connect(MainWindow.ocr_button_toggled)
        self.actionReset_Settings_2.triggered.connect(MainWindow.action_reset_settings)
        self.toggle_select_button.toggled.connect(MainWindow.action_toggle_select)
        self.actionModel_Manager_3.triggered.connect(MainWindow.action_show_model_manager)
        self.drawingpad_import.triggered.connect(MainWindow.import_drawingpad_image)
        self.drawingpad_export.triggered.connect(MainWindow.export_drawingpad_image)
        self.controlnet_import.triggered.connect(MainWindow.import_controlnet_image)
        self.controlnet_export.triggered.connect(MainWindow.export_controlnet_image)
        self.enable_controlnet.toggled.connect(MainWindow.action_toggle_controlnet)
        self.actionUnload_LLm.triggered.connect(MainWindow.action_unload_llm)
        self.actionUnload_Image_model.triggered.connect(MainWindow.action_unload_sd)
        self.actionClear_Memory.triggered.connect(MainWindow.action_clear_memory)
        self.actionSafety_Checker.toggled.connect(MainWindow.action_toggle_nsfw_filter_triggered)
        self.outpaint_export.triggered.connect(MainWindow.action_outpaint_export)
        self.outpaint_enabled.toggled.connect(MainWindow.action_outpaint_toggled)
        self.outpaint_import.triggered.connect(MainWindow.action_outpaint_import)

        self.mode_tab_widget.setCurrentIndex(0)
        self.center_tab.setCurrentIndex(0)
        self.tool_tab_widget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"AI Runner", None))
        self.actionNew.setText(QCoreApplication.translate("MainWindow", u"New", None))
#if QT_CONFIG(shortcut)
        self.actionNew.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+N", None))
#endif // QT_CONFIG(shortcut)
        self.actionImport.setText(QCoreApplication.translate("MainWindow", u"Import image", None))
#if QT_CONFIG(shortcut)
        self.actionImport.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+I", None))
#endif // QT_CONFIG(shortcut)
        self.actionExport.setText(QCoreApplication.translate("MainWindow", u"Export image", None))
#if QT_CONFIG(shortcut)
        self.actionExport.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+E", None))
#endif // QT_CONFIG(shortcut)
        self.actionCopy.setText(QCoreApplication.translate("MainWindow", u"Copy", None))
#if QT_CONFIG(shortcut)
        self.actionCopy.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+C", None))
#endif // QT_CONFIG(shortcut)
        self.actionPaste.setText(QCoreApplication.translate("MainWindow", u"Paste", None))
#if QT_CONFIG(shortcut)
        self.actionPaste.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+V", None))
#endif // QT_CONFIG(shortcut)
        self.actionUndo.setText(QCoreApplication.translate("MainWindow", u"Undo", None))
#if QT_CONFIG(tooltip)
        self.actionUndo.setToolTip(QCoreApplication.translate("MainWindow", u"Undo", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(whatsthis)
        self.actionUndo.setWhatsThis("")
#endif // QT_CONFIG(whatsthis)
#if QT_CONFIG(shortcut)
        self.actionUndo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Z", None))
#endif // QT_CONFIG(shortcut)
        self.actionRedo.setText(QCoreApplication.translate("MainWindow", u"Redo", None))
#if QT_CONFIG(shortcut)
        self.actionRedo.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Y", None))
#endif // QT_CONFIG(shortcut)
        self.actionGrid.setText(QCoreApplication.translate("MainWindow", u"Grid", None))
#if QT_CONFIG(tooltip)
        self.actionGrid.setToolTip(QCoreApplication.translate("MainWindow", u"Grid settings", None))
#endif // QT_CONFIG(tooltip)
        self.actionPreferences.setText(QCoreApplication.translate("MainWindow", u"Path Preferences", None))
#if QT_CONFIG(tooltip)
        self.actionPreferences.setToolTip(QCoreApplication.translate("MainWindow", u"Modify model path and more", None))
#endif // QT_CONFIG(tooltip)
        self.actionCanvas_color.setText(QCoreApplication.translate("MainWindow", u"Canvas color", None))
#if QT_CONFIG(tooltip)
        self.actionCanvas_color.setToolTip(QCoreApplication.translate("MainWindow", u"Change the color of the canvas", None))
#endif // QT_CONFIG(tooltip)
        self.actionReset_Settings.setText(QCoreApplication.translate("MainWindow", u"Reset Settings to Default", None))
#if QT_CONFIG(tooltip)
        self.actionReset_Settings.setToolTip(QCoreApplication.translate("MainWindow", u"Reset all settings to default", None))
#endif // QT_CONFIG(tooltip)
        self.actionResize_on_Paste.setText(QCoreApplication.translate("MainWindow", u"Resize on Import", None))
#if QT_CONFIG(tooltip)
        self.actionResize_on_Paste.setToolTip(QCoreApplication.translate("MainWindow", u"Resize the image to active grid area when importing", None))
#endif // QT_CONFIG(tooltip)
        self.actionMemory.setText(QCoreApplication.translate("MainWindow", u"Memory", None))
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.actionCheck_for_updates.setText(QCoreApplication.translate("MainWindow", u"Check for updates", None))
        self.actionOpen.setText(QCoreApplication.translate("MainWindow", u"Open", None))
        self.actionView.setText(QCoreApplication.translate("MainWindow", u"View", None))
        self.actionAdvanced.setText(QCoreApplication.translate("MainWindow", u"Memory Preferences", None))
#if QT_CONFIG(tooltip)
        self.actionAdvanced.setToolTip(QCoreApplication.translate("MainWindow", u"Change memory settings", None))
#endif // QT_CONFIG(tooltip)
        self.actionGaussian_Blur.setText(QCoreApplication.translate("MainWindow", u"Gaussian Blur", None))
        self.actionBox_Blur.setText(QCoreApplication.translate("MainWindow", u"Box Blur", None))
        self.actionUnsharp_Mask.setText(QCoreApplication.translate("MainWindow", u"Unsharp Mask", None))
        self.actionPixel_Art.setText(QCoreApplication.translate("MainWindow", u"Pixel Art", None))
        self.actionInvert.setText(QCoreApplication.translate("MainWindow", u"Invert", None))
        self.actionSaturation.setText(QCoreApplication.translate("MainWindow", u"Saturation", None))
        self.actionColor_Balance.setText(QCoreApplication.translate("MainWindow", u"Color Balance", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
#if QT_CONFIG(shortcut)
        self.actionSave.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
#endif // QT_CONFIG(shortcut)
        self.actionLoad.setText(QCoreApplication.translate("MainWindow", u"Open", None))
#if QT_CONFIG(shortcut)
        self.actionLoad.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+O", None))
#endif // QT_CONFIG(shortcut)
        self.actionQuit.setText(QCoreApplication.translate("MainWindow", u"Quit", None))
#if QT_CONFIG(shortcut)
        self.actionQuit.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
        self.actionPixel_Art_2.setText(QCoreApplication.translate("MainWindow", u"Pixel Art", None))
        self.actionBug_report.setText(QCoreApplication.translate("MainWindow", u"Bug report", None))
        self.actionReport_vulnerability.setText(QCoreApplication.translate("MainWindow", u"Report vulnerability", None))
        self.actionDiscord.setText(QCoreApplication.translate("MainWindow", u"Discord", None))
        self.actionExtensions.setText(QCoreApplication.translate("MainWindow", u"Extensions", None))
#if QT_CONFIG(tooltip)
        self.actionExtensions.setToolTip(QCoreApplication.translate("MainWindow", u"Install, update and delete extensions", None))
#endif // QT_CONFIG(tooltip)
        self.actionShow_image_preview.setText(QCoreApplication.translate("MainWindow", u"Show image preview", None))
        self.actionImage_to_new_layer.setText(QCoreApplication.translate("MainWindow", u"Image to new layer", None))
#if QT_CONFIG(tooltip)
        self.actionImage_to_new_layer.setToolTip(QCoreApplication.translate("MainWindow", u"Send generated images to new layer", None))
#endif // QT_CONFIG(tooltip)
        self.actionAuto_export_images.setText(QCoreApplication.translate("MainWindow", u"Auto export images", None))
#if QT_CONFIG(tooltip)
        self.actionAuto_export_images.setToolTip(QCoreApplication.translate("MainWindow", u"Automatically export newly generated images to a folder", None))
#endif // QT_CONFIG(tooltip)
        self.actionImage_export_settings.setText(QCoreApplication.translate("MainWindow", u"Import / export preferences", None))
        self.actionCheck_for_latest_version_on_startup.setText(QCoreApplication.translate("MainWindow", u"Check for latest version on startup", None))
        self.actionModel_Merger.setText(QCoreApplication.translate("MainWindow", u"Model Merger", None))
        self.actionSaturation_Filter.setText(QCoreApplication.translate("MainWindow", u"Saturation", None))
        self.actionColor_Balance_2.setText(QCoreApplication.translate("MainWindow", u"Color Balance", None))
        self.actionRGB_Noise.setText(QCoreApplication.translate("MainWindow", u"RGB Noise", None))
        self.actionGaussian_Blur_2.setText(QCoreApplication.translate("MainWindow", u"Gaussian Blur", None))
        self.actionBox_Blur_2.setText(QCoreApplication.translate("MainWindow", u"Box Blur", None))
        self.actionRotate_90_clockwise.setText(QCoreApplication.translate("MainWindow", u"Rotate 90\u00b0 clockwise", None))
#if QT_CONFIG(shortcut)
        self.actionRotate_90_clockwise.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+R", None))
#endif // QT_CONFIG(shortcut)
        self.actionRotate_90_counter_clockwise.setText(QCoreApplication.translate("MainWindow", u"Rotate 90\u00b0 counter clockwise", None))
#if QT_CONFIG(shortcut)
        self.actionRotate_90_counter_clockwise.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+R", None))
#endif // QT_CONFIG(shortcut)
        self.actionSave_prompt.setText(QCoreApplication.translate("MainWindow", u"Save prompt", None))
        self.actionShow_Active_Image_Area.setText(QCoreApplication.translate("MainWindow", u"Show Active Image Area", None))
        self.actionImage_Interpolation.setText(QCoreApplication.translate("MainWindow", u"Image Interpolation", None))
        self.actionImage_interpolation.setText(QCoreApplication.translate("MainWindow", u"Image Interpolation", None))
        self.actionFilm.setText(QCoreApplication.translate("MainWindow", u"Film", None))
        self.actionDeterministic_generation.setText(QCoreApplication.translate("MainWindow", u"Deterministic generator", None))
        self.actionDark_mode.setText(QCoreApplication.translate("MainWindow", u"Dark mode", None))
        self.actionConsole_window.setText(QCoreApplication.translate("MainWindow", u"Console window", None))
        self.actionSettings.setText(QCoreApplication.translate("MainWindow", u"Preferences", None))
        self.actionPrompt_Browser.setText(QCoreApplication.translate("MainWindow", u"Prompt browser", None))
        self.actionClear_all_prompts.setText(QCoreApplication.translate("MainWindow", u"Clear all prompts", None))
#if QT_CONFIG(tooltip)
        self.actionClear_all_prompts.setToolTip(QCoreApplication.translate("MainWindow", u"Remove text from all prompts and negative prompts", None))
#endif // QT_CONFIG(tooltip)
        self.actionUndo_2.setText(QCoreApplication.translate("MainWindow", u"Undo", None))
#if QT_CONFIG(shortcut)
        self.actionUndo_2.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Z", None))
#endif // QT_CONFIG(shortcut)
        self.actionRedo_2.setText(QCoreApplication.translate("MainWindow", u"Redo", None))
#if QT_CONFIG(shortcut)
        self.actionRedo_2.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Y", None))
#endif // QT_CONFIG(shortcut)
        self.actionCut.setText(QCoreApplication.translate("MainWindow", u"Cut", None))
#if QT_CONFIG(shortcut)
        self.actionCut.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+X", None))
#endif // QT_CONFIG(shortcut)
        self.actionHalftone.setText(QCoreApplication.translate("MainWindow", u"Halftone", None))
        self.actionQuick_Export.setText(QCoreApplication.translate("MainWindow", u"Fast Export", None))
#if QT_CONFIG(shortcut)
        self.actionQuick_Export.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Shift+E", None))
#endif // QT_CONFIG(shortcut)
        self.actionRegistration_error.setText(QCoreApplication.translate("MainWindow", u"Registration error", None))
        self.actionHuggingface_Cache_manager.setText(QCoreApplication.translate("MainWindow", u"Browse Huggingface Cache", None))
        self.actionModel_Manager.setText(QCoreApplication.translate("MainWindow", u"Model Manager", None))
        self.actionModel_Manager_2.setText(QCoreApplication.translate("MainWindow", u"Model Manager", None))
        self.actionControlNet.setText(QCoreApplication.translate("MainWindow", u"ControlNet", None))
        self.actionPrompt_Builder.setText(QCoreApplication.translate("MainWindow", u"Prompt Builder", None))
        self.actionEmbeddings.setText(QCoreApplication.translate("MainWindow", u"Embeddings", None))
        self.actionLoRA.setText(QCoreApplication.translate("MainWindow", u"LoRA", None))
        self.actionPen.setText(QCoreApplication.translate("MainWindow", u"Pen", None))
        self.actionStableDiffusion.setText(QCoreApplication.translate("MainWindow", u"Stable Diffusion", None))
        self.actionKandinsky.setText(QCoreApplication.translate("MainWindow", u"Kandinsky", None))
        self.actionShap_E.setText(QCoreApplication.translate("MainWindow", u"Shap-E", None))
        self.actionRun_setup_wizard.setText(QCoreApplication.translate("MainWindow", u"Run setup wizard", None))
        self.actionBrowse_AI_Runner_Path.setText(QCoreApplication.translate("MainWindow", u"Browse AI Runner Path", None))
        self.actionBrowse_Images_Path.setText(QCoreApplication.translate("MainWindow", u"Browse Images Path", None))
        self.actionBrowse_Images_Path_2.setText(QCoreApplication.translate("MainWindow", u"Browse Images", None))
        self.actionBrowse_Videos_Path.setText(QCoreApplication.translate("MainWindow", u"Browse Videos", None))
        self.actionBrowse_Gifs_Path.setText(QCoreApplication.translate("MainWindow", u"Browse GIFs", None))
        self.actionTxt2img_Img2img_Models.setText(QCoreApplication.translate("MainWindow", u"Txt2img / Img2img", None))
        self.actionInpaint_Outpaint_Models.setText(QCoreApplication.translate("MainWindow", u"Inpaint / Outpaint", None))
        self.actionDepth2img_Models.setText(QCoreApplication.translate("MainWindow", u"Depth2img", None))
        self.actionPix2pix.setText(QCoreApplication.translate("MainWindow", u"Pix2pix", None))
        self.actionUpscale.setText(QCoreApplication.translate("MainWindow", u"Upscale", None))
        self.actionSuperresolution.setText(QCoreApplication.translate("MainWindow", u"Superresolution", None))
        self.actionTxt2vid.setText(QCoreApplication.translate("MainWindow", u"Txt2vid", None))
        self.actionActive_Grid.setText(QCoreApplication.translate("MainWindow", u"Active Grid", None))
        self.actionDeterministic_Batches.setText(QCoreApplication.translate("MainWindow", u"Deterministic Batches", None))
        self.actionStandard_Batches.setText(QCoreApplication.translate("MainWindow", u"Standard Batches", None))
        self.actionLLM_beta.setText(QCoreApplication.translate("MainWindow", u"LLM (beta)", None))
        self.actionReset_Settings_2.setText(QCoreApplication.translate("MainWindow", u"Reset Settings", None))
        self.actionImage_Browser.setText(QCoreApplication.translate("MainWindow", u"Image Browser", None))
        self.actionModel_Manager_3.setText(QCoreApplication.translate("MainWindow", u"Model Manager", None))
        self.actionImport_input_image.setText(QCoreApplication.translate("MainWindow", u"Import input image", None))
        self.actionExport_input_image.setText(QCoreApplication.translate("MainWindow", u"Export input image", None))
        self.actionImport_2.setText(QCoreApplication.translate("MainWindow", u"Import image", None))
        self.actionExport_image.setText(QCoreApplication.translate("MainWindow", u"Export image", None))
        self.actionImport_Image.setText(QCoreApplication.translate("MainWindow", u"Import Image", None))
        self.actionExport_Image.setText(QCoreApplication.translate("MainWindow", u"Export Image", None))
        self.actionImport_3.setText(QCoreApplication.translate("MainWindow", u"Import", None))
        self.actionExport_2.setText(QCoreApplication.translate("MainWindow", u"Export", None))
        self.controlnet_import.setText(QCoreApplication.translate("MainWindow", u"Import Image", None))
        self.controlnet_export.setText(QCoreApplication.translate("MainWindow", u"Export Image", None))
        self.drawingpad_import.setText(QCoreApplication.translate("MainWindow", u"Import Image", None))
        self.drawingpad_export.setText(QCoreApplication.translate("MainWindow", u"Export Image", None))
        self.actionGenerate_while_drawing.setText(QCoreApplication.translate("MainWindow", u"Generate while drawing", None))
        self.actionOverlay_input_image.setText(QCoreApplication.translate("MainWindow", u"Overlay input image", None))
        self.enable_controlnet.setText(QCoreApplication.translate("MainWindow", u"Enabled", None))
        self.actionUnload_LLm.setText(QCoreApplication.translate("MainWindow", u"Unload LLM", None))
        self.actionUnload_Image_model.setText(QCoreApplication.translate("MainWindow", u"Unload Image model", None))
        self.actionClear_Memory.setText(QCoreApplication.translate("MainWindow", u"Clear Memory", None))
        self.actionSafety_Checker.setText(QCoreApplication.translate("MainWindow", u"Safety Checker", None))
        self.outpaint_import.setText(QCoreApplication.translate("MainWindow", u"Import", None))
        self.outpaint_export.setText(QCoreApplication.translate("MainWindow", u"Export", None))
        self.outpaint_enabled.setText(QCoreApplication.translate("MainWindow", u"Enabled", None))
#if QT_CONFIG(tooltip)
        self.file_new_button.setToolTip(QCoreApplication.translate("MainWindow", u"New", None))
#endif // QT_CONFIG(tooltip)
        self.file_new_button.setText("")
#if QT_CONFIG(tooltip)
        self.open_button.setToolTip(QCoreApplication.translate("MainWindow", u"Open", None))
#endif // QT_CONFIG(tooltip)
        self.open_button.setText("")
#if QT_CONFIG(tooltip)
        self.save_button.setToolTip(QCoreApplication.translate("MainWindow", u"Save", None))
#endif // QT_CONFIG(tooltip)
        self.save_button.setText("")
#if QT_CONFIG(tooltip)
        self.export_button.setToolTip(QCoreApplication.translate("MainWindow", u"Export Image", None))
#endif // QT_CONFIG(tooltip)
        self.export_button.setText("")
#if QT_CONFIG(tooltip)
        self.undo_button.setToolTip(QCoreApplication.translate("MainWindow", u"Undo", None))
#endif // QT_CONFIG(tooltip)
        self.undo_button.setText("")
#if QT_CONFIG(tooltip)
        self.redo_button.setToolTip(QCoreApplication.translate("MainWindow", u"Redo", None))
#endif // QT_CONFIG(tooltip)
        self.redo_button.setText("")
        self.center_tab.setTabText(self.center_tab.indexOf(self.canvas_tab), QCoreApplication.translate("MainWindow", u"Canvas", None))
        self.center_tab.setTabText(self.center_tab.indexOf(self.model_manager_tab), QCoreApplication.translate("MainWindow", u"Model Manager", None))
        self.tool_tab_widget.setTabText(self.tool_tab_widget.indexOf(self.tab_pen), QCoreApplication.translate("MainWindow", u"Pen", None))
        self.tool_tab_widget.setTabText(self.tool_tab_widget.indexOf(self.tab_active_grid), QCoreApplication.translate("MainWindow", u"Active Grid", None))
        self.tool_tab_widget.setTabText(self.tool_tab_widget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Upscale", None))
        self.tool_tab_widget.setTabText(self.tool_tab_widget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"StableDiffusion", None))
        self.tool_tab_widget.setTabText(self.tool_tab_widget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"LLM", None))
#if QT_CONFIG(tooltip)
        self.toggle_active_grid_area_button.setToolTip(QCoreApplication.translate("MainWindow", u"Active grid area selection tool", None))
#endif // QT_CONFIG(tooltip)
        self.toggle_active_grid_area_button.setText("")
        self.toggle_select_button.setText("")
#if QT_CONFIG(tooltip)
        self.toggle_brush_button.setToolTip(QCoreApplication.translate("MainWindow", u"Pen tool", None))
#endif // QT_CONFIG(tooltip)
        self.toggle_brush_button.setText("")
#if QT_CONFIG(tooltip)
        self.toggle_eraser_button.setToolTip(QCoreApplication.translate("MainWindow", u"Eraser tool", None))
#endif // QT_CONFIG(tooltip)
        self.toggle_eraser_button.setText("")
#if QT_CONFIG(tooltip)
        self.toggle_grid_button.setToolTip(QCoreApplication.translate("MainWindow", u"Toggle Grid", None))
#endif // QT_CONFIG(tooltip)
        self.toggle_grid_button.setText("")
#if QT_CONFIG(tooltip)
        self.focus_button.setToolTip(QCoreApplication.translate("MainWindow", u"Recenter canvas", None))
#endif // QT_CONFIG(tooltip)
        self.focus_button.setText("")
#if QT_CONFIG(tooltip)
        self.ai_button.setToolTip(QCoreApplication.translate("MainWindow", u"Toggle AI Mode", None))
#endif // QT_CONFIG(tooltip)
        self.ai_button.setText("")
#if QT_CONFIG(tooltip)
        self.model_manager_button.setToolTip(QCoreApplication.translate("MainWindow", u"Model manager", None))
#endif // QT_CONFIG(tooltip)
        self.model_manager_button.setText("")
#if QT_CONFIG(tooltip)
        self.settings_button.setToolTip(QCoreApplication.translate("MainWindow", u"AI Runner Settings", None))
#endif // QT_CONFIG(tooltip)
        self.settings_button.setText("")
#if QT_CONFIG(tooltip)
        self.tts_button.setToolTip(QCoreApplication.translate("MainWindow", u"Toggle Text to Speech", None))
#endif // QT_CONFIG(tooltip)
        self.tts_button.setText("")
#if QT_CONFIG(tooltip)
        self.v2t_button.setToolTip(QCoreApplication.translate("MainWindow", u"Toggle Speech To Text", None))
#endif // QT_CONFIG(tooltip)
        self.v2t_button.setText("")
#if QT_CONFIG(tooltip)
        self.ocr_button.setToolTip(QCoreApplication.translate("MainWindow", u"Toggle Vision", None))
#endif // QT_CONFIG(tooltip)
        self.ocr_button.setText("")
        self.mode_tab_widget.setTabText(self.mode_tab_widget.indexOf(self.art), QCoreApplication.translate("MainWindow", u"Image Generation", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.menuFilters.setTitle(QCoreApplication.translate("MainWindow", u"Filters", None))
        self.menuAbout.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.menuImage.setTitle(QCoreApplication.translate("MainWindow", u"Canvas", None))
        self.menuCanvas_Image.setTitle(QCoreApplication.translate("MainWindow", u"Main", None))
        self.menuDrawingpad.setTitle(QCoreApplication.translate("MainWindow", u"Input", None))
        self.menuControlnet.setTitle(QCoreApplication.translate("MainWindow", u"Controlnet", None))
        self.menuOutpaint.setTitle(QCoreApplication.translate("MainWindow", u"Outpaint", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
        self.menuBrowse_Models_Path.setTitle(QCoreApplication.translate("MainWindow", u"Browse Models Paths", None))
        self.menuTools.setTitle(QCoreApplication.translate("MainWindow", u"Tools", None))
    # retranslateUi

