# Form implementation generated from reading ui file '/home/joe/Projects/imagetopixel/airunner/src/airunner/widgets/generated_image/templates/generated_image.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(283, 328)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(17, 0, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 1)
        self.image_container = QtWidgets.QLabel(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_container.sizePolicy().hasHeightForWidth())
        self.image_container.setSizePolicy(sizePolicy)
        self.image_container.setMinimumSize(QtCore.QSize(256, 256))
        self.image_container.setMaximumSize(QtCore.QSize(256, 256))
        self.image_container.setText("")
        self.image_container.setObjectName("image_container")
        self.gridLayout.addWidget(self.image_container, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.to_canvas_button = QtWidgets.QPushButton(Form)
        self.to_canvas_button.setObjectName("to_canvas_button")
        self.horizontalLayout.addWidget(self.to_canvas_button)
        self.export_button = QtWidgets.QPushButton(Form)
        self.export_button.setObjectName("export_button")
        self.horizontalLayout.addWidget(self.export_button)
        self.delete_button = QtWidgets.QPushButton(Form)
        self.delete_button.setObjectName("delete_button")
        self.horizontalLayout.addWidget(self.delete_button)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.slot_combobox = QtWidgets.QComboBox(Form)
        self.slot_combobox.setObjectName("slot_combobox")
        self.horizontalLayout_2.addWidget(self.slot_combobox)
        self.to_slot_button = QtWidgets.QPushButton(Form)
        self.to_slot_button.setObjectName("to_slot_button")
        self.horizontalLayout_2.addWidget(self.to_slot_button)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.to_canvas_button.setText(_translate("Form", "Send to canvas"))
        self.export_button.setText(_translate("Form", "Export"))
        self.delete_button.setText(_translate("Form", "Delete"))
        self.to_slot_button.setText(_translate("Form", "Send to slot"))
