from sqlalchemy import Column, Boolean, String, Integer, Float
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()


class AppSettings(Base):
    __tablename__ = 'settings'

    id = Column(Integer, primary_key=True)
    nsfw_filter = Column(Boolean, default=True)
    allow_hf_downloads = Column(Boolean)
    pixel_mode = Column(Boolean)
    canvas_color = Column(String, default="#000000")
    paste_at_working_size = Column(Boolean)
    outpaint_on_paste = Column(Boolean)
    fast_load_last_session = Column(Boolean)
    available_embeddings = Column(String, default="")
    do_settings_reset = Column(Boolean)
    dark_mode_enabled = Column(Boolean)
    resize_on_paste = Column(Boolean)
    image_to_new_layer = Column(Boolean)
    hf_api_key = Column(String, default="")
    is_maximized = Column(Boolean, default=False)
    latest_version_check = Column(Boolean, default=False)
    force_reset = Column(Boolean, default=False)
    show_active_image_area = Column(Boolean, default=False)
    bottom_splitter_sizes = Column(String, default="0,0")
    main_splitter_sizes = Column(String, default="-1,-1,-1")

    # grid settings
    line_color = Column(String, default="#111111")
    line_width = Column(Integer, default=1)
    line_stipple = Column(Boolean, default=True)
    size = Column(Integer, default=64)
    show_grid = Column(Boolean, default=True)
    snap_to_grid = Column(Boolean, default=True)

    # image export settings
    auto_export_images = Column(Boolean)
    image_export_type = Column(String, default="png")
    image_export_metadata_prompt = Column(Boolean)
    image_export_metadata_negative_prompt = Column(Boolean)
    image_export_metadata_scale = Column(Boolean)
    image_export_metadata_seed = Column(Boolean)
    image_export_metadata_steps = Column(Boolean)
    image_export_metadata_ddim_eta = Column(Boolean)
    image_export_metadata_iterations = Column(Boolean)
    image_export_metadata_samples = Column(Boolean)
    image_export_metadata_model = Column(Boolean)
    image_export_metadata_model_branch = Column(Boolean)
    image_export_metadata_scheduler = Column(Boolean)
    export_metadata = Column(Boolean)
    import_metadata = Column(Boolean)

    # memory settings
    use_last_channels = Column(Boolean, default=True)
    use_enable_sequential_cpu_offload = Column(Boolean, default=False)
    use_attention_slicing = Column(Boolean, default=False)
    use_tf32 = Column(Boolean, default=False)
    use_cudnn_benchmark = Column(Boolean, default=True)
    use_enable_vae_slicing = Column(Boolean, default=True)
    use_tiled_vae = Column(Boolean, default=True)
    enable_model_cpu_offload = Column(Boolean, default=False)
    use_accelerated_transformers = Column(Boolean, default=True)
    use_torch_compile = Column(Boolean, default=False)

    # prompt builder settings
    use_prompt_builder_checkbox = Column(Boolean, default=False)
    auto_prompt_weight = Column(Float, default=0.5)
    auto_negative_prompt_weight = Column(Float, default=0.5)
    negative_auto_prompt_weight = Column(Float, default=0.5)
    prompt_generator_advanced = Column(Boolean, default=False)
    prompt_generator_category_a = Column(String, default="")
    prompt_generator_category_b = Column(String, default="")
    prompt_blend_type = Column(Integer, default=0)
    prompt_generator_prompt_a = Column(String, default="")
    prompt_generator_weighted_values_a = Column(JSON, default={})
    prompt_generator_prompt_color_a = Column(String, default="")
    prompt_generator_prompt_genre_a = Column(String, default="")
    prompt_generator_prompt_style_a = Column(String, default="")
    prompt_generator_prefix_a = Column(String, default="")
    prompt_generator_suffix_a = Column(String, default="")
    negative_prompt_generator_prefix_a = Column(String, default="")
    negative_prompt_generator_suffix_a = Column(String, default="")
    prompt_generator_prompt_b = Column(String, default="")
    prompt_generator_weighted_values_b = Column(JSON, default={})
    prompt_generator_prompt_color_b = Column(String, default="")
    prompt_generator_prompt_genre_b = Column(String, default="")
    prompt_generator_prompt_style_b = Column(String, default="")
    prompt_generator_prefix_b = Column(String, default="")
    prompt_generator_suffix_b = Column(String, default="")
    negative_prompt_generator_prefix_b = Column(String, default="")
    negative_prompt_generator_suffix_b = Column(String, default="")

    # tool settings
    primary_color = Column(String, default="#ffffff")
    secondary_color = Column(String, default="#000000")
    working_width = Column(Integer, default=512)
    working_height = Column(Integer, default=512)

    # path settings
    model_base_path = Column(String, default="")
    depth2img_model_path = Column(String, default="")
    pix2pix_model_path = Column(String, default="")
    outpaint_model_path = Column(String, default="")
    upscale_model_path = Column(String, default="")
    txt2vid_model_path = Column(String, default="")
    embeddings_path = Column(String, default="")
    lora_path = Column(String, default="")
    video_path = Column(String, default="")
    image_path = Column(String, default="")
    gif_path = Column(String, default="")

    # filter settings
    color_balance_filter_cyan_red = Column(Integer, default=0)
    color_balance_filter_magenta_green = Column(Integer, default=0)
    color_balance_filter_yellow_blue = Column(Integer, default=0)