# Form implementation generated from reading ui file '/home/joe/Projects/imagetopixel/airunner/src/airunner/../../src/airunner/widgets/gif/templates/gif_widget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_gif_widget(object):
    def setupUi(self, gif_widget):
        gif_widget.setObjectName("gif_widget")
        gif_widget.resize(274, 321)
        self.gridLayout = QtWidgets.QGridLayout(gif_widget)
        self.gridLayout.setObjectName("gridLayout")
        self.gif_frame = QtWidgets.QFrame(parent=gif_widget)
        self.gif_frame.setMinimumSize(QtCore.QSize(256, 256))
        self.gif_frame.setMaximumSize(QtCore.QSize(256, 256))
        self.gif_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.gif_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.gif_frame.setObjectName("gif_frame")
        self.gridLayout.addWidget(self.gif_frame, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(parent=gif_widget)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 1, 0, 1, 1)

        self.retranslateUi(gif_widget)
        self.pushButton.clicked.connect(gif_widget.delete_gif) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(gif_widget)

    def retranslateUi(self, gif_widget):
        _translate = QtCore.QCoreApplication.translate
        gif_widget.setWindowTitle(_translate("gif_widget", "Form"))
        self.pushButton.setText(_translate("gif_widget", "Delete"))
