# Form implementation generated from reading ui file '/home/joe/Projects/imagetopixel/airunner/src/airunner/widgets/paths/templates/path.ui'
#
# Created by: PyQt6 UI code generator 6.2.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_path_widget(object):
    def setupUi(self, path_widget):
        path_widget.setObjectName("path_widget")
        path_widget.resize(452, 94)
        self.gridLayout = QtWidgets.QGridLayout(path_widget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontal_line = QtWidgets.QFrame(path_widget)
        self.horizontal_line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.horizontal_line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.horizontal_line.setObjectName("horizontal_line")
        self.gridLayout.addWidget(self.horizontal_line, 4, 0, 1, 1)
        self.title_label = QtWidgets.QLabel(path_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.title_label.setFont(font)
        self.title_label.setObjectName("title_label")
        self.gridLayout.addWidget(self.title_label, 1, 0, 1, 1)
        self.description_label = QtWidgets.QLabel(path_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.description_label.setFont(font)
        self.description_label.setObjectName("description_label")
        self.gridLayout.addWidget(self.description_label, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.path = QtWidgets.QLineEdit(path_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.path.setFont(font)
        self.path.setObjectName("path")
        self.horizontalLayout.addWidget(self.path)
        self.browse_button = QtWidgets.QPushButton(path_widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.browse_button.setFont(font)
        self.browse_button.setObjectName("browse_button")
        self.horizontalLayout.addWidget(self.browse_button)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 1)

        self.retranslateUi(path_widget)
        self.path.textChanged['QString'].connect(path_widget.action_path_changed) # type: ignore
        self.browse_button.clicked.connect(path_widget.action_button_clicked) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(path_widget)

    def retranslateUi(self, path_widget):
        _translate = QtCore.QCoreApplication.translate
        path_widget.setWindowTitle(_translate("path_widget", "Form"))
        self.title_label.setText(_translate("path_widget", "Title"))
        self.description_label.setText(_translate("path_widget", "Description"))
        self.browse_button.setText(_translate("path_widget", "Browse"))
