# Form implementation generated from reading ui file '/home/joe/Projects/imagetopixel/airunner/src/airunner/pyqt/layer.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LayerWidget(object):
    def setupUi(self, LayerWidget):
        LayerWidget.setObjectName("LayerWidget")
        LayerWidget.resize(220, 116)
        self.gridLayout_2 = QtWidgets.QGridLayout(LayerWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.frame = QtWidgets.QFrame(parent=LayerWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(200, 0))
        self.frame.setStyleSheet("border-color: rgb(51, 209, 122);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.layer_name = QtWidgets.QLabel(parent=self.frame)
        self.layer_name.setStyleSheet("border-color: rgba(0, 0, 0, 0);")
        self.layer_name.setObjectName("layer_name")
        self.horizontalLayout_3.addWidget(self.layer_name)
        self.visible_button = QtWidgets.QPushButton(parent=self.frame)
        self.visible_button.setMaximumSize(QtCore.QSize(32, 32))
        self.visible_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/src/icons/eye-off.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon.addPixmap(QtGui.QPixmap("/home/joe/Projects/imagetopixel/airunner/src/airunner/pyqt/../src/icons/eye.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        icon.addPixmap(QtGui.QPixmap(":/icons/src/icons/eye.png"), QtGui.QIcon.Mode.Active, QtGui.QIcon.State.On)
        self.visible_button.setIcon(icon)
        self.visible_button.setCheckable(True)
        self.visible_button.setObjectName("visible_button")
        self.horizontalLayout_3.addWidget(self.visible_button)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.opacity_slider = QtWidgets.QSlider(parent=LayerWidget)
        self.opacity_slider.setMaximum(100)
        self.opacity_slider.setProperty("value", 100)
        self.opacity_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.opacity_slider.setObjectName("opacity_slider")
        self.horizontalLayout_2.addWidget(self.opacity_slider)
        self.opacity_spinbox = QtWidgets.QDoubleSpinBox(parent=LayerWidget)
        self.opacity_spinbox.setMaximum(1.0)
        self.opacity_spinbox.setSingleStep(0.01)
        self.opacity_spinbox.setProperty("value", 1.0)
        self.opacity_spinbox.setObjectName("opacity_spinbox")
        self.horizontalLayout_2.addWidget(self.opacity_spinbox)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=LayerWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(LayerWidget)
        QtCore.QMetaObject.connectSlotsByName(LayerWidget)

    def retranslateUi(self, LayerWidget):
        _translate = QtCore.QCoreApplication.translate
        LayerWidget.setWindowTitle(_translate("LayerWidget", "Form"))
        self.layer_name.setText(_translate("LayerWidget", "Layer 1"))
        self.label.setText(_translate("LayerWidget", "Opacity"))
