# Form implementation generated from reading ui file '/home/joe/Projects/imagetopixel/airunner/src/airunner/pyqt/lora.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(378, 108)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.trigger_word = QtWidgets.QLineEdit(parent=Form)
        self.trigger_word.setObjectName("trigger_word")
        self.gridLayout.addWidget(self.trigger_word, 4, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.scaleSlider = QtWidgets.QSlider(parent=Form)
        self.scaleSlider.setMaximum(100)
        self.scaleSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.scaleSlider.setObjectName("scaleSlider")
        self.horizontalLayout.addWidget(self.scaleSlider)
        self.scaleSpinBox = QtWidgets.QDoubleSpinBox(parent=Form)
        self.scaleSpinBox.setMaximum(1.0)
        self.scaleSpinBox.setSingleStep(0.01)
        self.scaleSpinBox.setObjectName("scaleSpinBox")
        self.horizontalLayout.addWidget(self.scaleSpinBox)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.enabledCheckbox = QtWidgets.QCheckBox(parent=Form)
        self.enabledCheckbox.setObjectName("enabledCheckbox")
        self.gridLayout.addWidget(self.enabledCheckbox, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.trigger_word.setToolTip(_translate("Form", "<html><head/><body><p>Some LoRA require a trigger word to activate.</p><p>Make a note here for your records.</p></body></html>"))
        self.trigger_word.setPlaceholderText(_translate("Form", "Trigger word"))
        self.enabledCheckbox.setText(_translate("Form", "Some specific lora"))
