# Form implementation generated from reading ui file '/home/joe/Projects/imagetopixel/airunner/src/airunner/../../src/airunner/widgets/standard_image/templates/standard_image_widget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_standard_image_widget(object):
    def setupUi(self, standard_image_widget):
        standard_image_widget.setObjectName("standard_image_widget")
        standard_image_widget.resize(1049, 783)
        self.formLayout = QtWidgets.QFormLayout(standard_image_widget)
        self.formLayout.setObjectName("formLayout")
        self.image_frame = QtWidgets.QFrame(parent=standard_image_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image_frame.sizePolicy().hasHeightForWidth())
        self.image_frame.setSizePolicy(sizePolicy)
        self.image_frame.setMinimumSize(QtCore.QSize(512, 512))
        self.image_frame.setMaximumSize(QtCore.QSize(512, 512))
        self.image_frame.setAcceptDrops(True)
        self.image_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.image_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.image_frame.setObjectName("image_frame")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.image_frame)
        self.tableWidget = QtWidgets.QTableWidget(parent=standard_image_widget)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.tableWidget.setAutoScroll(False)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 1, item)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setVisible(False)
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.tableWidget)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.formLayout.setItem(1, QtWidgets.QFormLayout.ItemRole.FieldRole, spacerItem)

        self.retranslateUi(standard_image_widget)
        QtCore.QMetaObject.connectSlotsByName(standard_image_widget)

    def retranslateUi(self, standard_image_widget):
        _translate = QtCore.QCoreApplication.translate
        standard_image_widget.setWindowTitle(_translate("standard_image_widget", "Form"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("standard_image_widget", "New Row"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("standard_image_widget", "Key"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("standard_image_widget", "Value"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        self.tableWidget.setSortingEnabled(__sortingEnabled)
