# Form implementation generated from reading ui file '/home/joe/Projects/imagetopixel/airunner/src/airunner/../../src/airunner/widgets/brush/brush_widget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_brush_widget(object):
    def setupUi(self, brush_widget):
        brush_widget.setObjectName("brush_widget")
        brush_widget.resize(400, 161)
        self.gridLayout = QtWidgets.QGridLayout(brush_widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_4 = QtWidgets.QGroupBox(parent=brush_widget)
        self.groupBox_4.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_3.setContentsMargins(6, 9, 6, 6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.primary_color_button = QtWidgets.QToolButton(parent=self.groupBox_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.primary_color_button.sizePolicy().hasHeightForWidth())
        self.primary_color_button.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.primary_color_button.setFont(font)
        self.primary_color_button.setText("")
        self.primary_color_button.setObjectName("primary_color_button")
        self.gridLayout_3.addWidget(self.primary_color_button, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_4, 0, 0, 1, 1)

        self.retranslateUi(brush_widget)
        QtCore.QMetaObject.connectSlotsByName(brush_widget)

    def retranslateUi(self, brush_widget):
        _translate = QtCore.QCoreApplication.translate
        brush_widget.setWindowTitle(_translate("brush_widget", "Form"))
        self.groupBox_4.setTitle(_translate("brush_widget", "Brush color"))
