# Form implementation generated from reading ui file '/home/joe/Projects/imagetopixel/airunner/src/airunner/../../src/airunner/widgets/image/templates/image_widget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_image_widget(object):
    def setupUi(self, image_widget):
        image_widget.setObjectName("image_widget")
        image_widget.resize(326, 204)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(image_widget.sizePolicy().hasHeightForWidth())
        image_widget.setSizePolicy(sizePolicy)
        image_widget.setMinimumSize(QtCore.QSize(0, 0))
        image_widget.setMaximumSize(QtCore.QSize(326, 16777215))
        self.gridLayout = QtWidgets.QGridLayout(image_widget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.image_frame = QtWidgets.QFrame(parent=image_widget)
        self.image_frame.setMinimumSize(QtCore.QSize(128, 128))
        self.image_frame.setMaximumSize(QtCore.QSize(128, 128))
        self.image_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.image_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.image_frame.setObjectName("image_frame")
        self.verticalLayout_3.addWidget(self.image_frame)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_2 = QtWidgets.QPushButton(parent=image_widget)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(parent=image_widget)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(parent=image_widget)
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.pushButton = QtWidgets.QPushButton(parent=image_widget)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon = QtGui.QIcon.fromTheme("user-trash")
        self.pushButton.setIcon(icon)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.permanently_delete_2 = QtWidgets.QWidget(parent=image_widget)
        self.permanently_delete_2.setObjectName("permanently_delete_2")
        self.permanently_delete = QtWidgets.QGridLayout(self.permanently_delete_2)
        self.permanently_delete.setObjectName("permanently_delete")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.permanently_delete_2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.permanently_delete.addWidget(self.pushButton_5, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.permanently_delete_2)
        self.label.setObjectName("label")
        self.permanently_delete.addWidget(self.label, 0, 0, 1, 2)
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.permanently_delete_2)
        self.pushButton_6.setObjectName("pushButton_6")
        self.permanently_delete.addWidget(self.pushButton_6, 1, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.permanently_delete_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.retranslateUi(image_widget)
        self.pushButton.clicked.connect(image_widget.confirm_delete) # type: ignore
        self.pushButton_2.clicked.connect(image_widget.send_image_to_grid) # type: ignore
        self.pushButton_3.clicked.connect(image_widget.generate_similar) # type: ignore
        self.pushButton_4.clicked.connect(image_widget.generate_variant) # type: ignore
        self.pushButton_5.clicked.connect(image_widget.delete_image) # type: ignore
        self.pushButton_6.clicked.connect(image_widget.cancel_delete) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(image_widget)

    def retranslateUi(self, image_widget):
        _translate = QtCore.QCoreApplication.translate
        image_widget.setWindowTitle(_translate("image_widget", "Form"))
        self.pushButton_2.setText(_translate("image_widget", "Load Image"))
        self.pushButton_3.setText(_translate("image_widget", "Generate Similar"))
        self.pushButton_4.setText(_translate("image_widget", "Generate Variant"))
        self.pushButton.setToolTip(_translate("image_widget", "Delete image"))
        self.pushButton.setText(_translate("image_widget", "Delete"))
        self.pushButton_5.setText(_translate("image_widget", "Yes"))
        self.label.setText(_translate("image_widget", "Permanently delete?"))
        self.pushButton_6.setText(_translate("image_widget", "No"))
