# Form implementation generated from reading ui file '/home/joe/Projects/imagetopixel/airunner/src/airunner/../../src/airunner/widgets/image/templates/image_widget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_image_widget(object):
    def setupUi(self, image_widget):
        image_widget.setObjectName("image_widget")
        image_widget.resize(303, 258)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(image_widget.sizePolicy().hasHeightForWidth())
        image_widget.setSizePolicy(sizePolicy)
        image_widget.setMinimumSize(QtCore.QSize(0, 0))
        image_widget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.gridLayout = QtWidgets.QGridLayout(image_widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_3 = QtWidgets.QPushButton(parent=image_widget)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 1, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(parent=image_widget)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 3, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(parent=image_widget)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 4, 0, 1, 1)
        self.image_frame = QtWidgets.QFrame(parent=image_widget)
        self.image_frame.setMinimumSize(QtCore.QSize(128, 128))
        self.image_frame.setMaximumSize(QtCore.QSize(128, 128))
        self.image_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.image_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.image_frame.setObjectName("image_frame")
        self.gridLayout.addWidget(self.image_frame, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(parent=image_widget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 2, 0, 1, 1)

        self.retranslateUi(image_widget)
        self.pushButton.clicked.connect(image_widget.delete_image) # type: ignore
        self.pushButton_2.clicked.connect(image_widget.send_image_to_grid) # type: ignore
        self.pushButton_3.clicked.connect(image_widget.generate_similar) # type: ignore
        self.pushButton_4.clicked.connect(image_widget.generate_variant) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(image_widget)

    def retranslateUi(self, image_widget):
        _translate = QtCore.QCoreApplication.translate
        image_widget.setWindowTitle(_translate("image_widget", "Form"))
        self.pushButton_3.setText(_translate("image_widget", "Generate Similar"))
        self.pushButton.setText(_translate("image_widget", "Delete"))
        self.pushButton_2.setText(_translate("image_widget", "To Canvas"))
        self.pushButton_4.setText(_translate("image_widget", "Generate Variant"))
