# Form implementation generated from reading ui file '/home/joe/Projects/imagetopixel/airunner/src/airunner/../../src/airunner/widgets/image/templates/image_widget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_image_widget(object):
    def setupUi(self, image_widget):
        image_widget.setObjectName("image_widget")
        image_widget.resize(552, 346)
        self.gridLayout = QtWidgets.QGridLayout(image_widget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.image_frame = QtWidgets.QFrame(parent=image_widget)
        self.image_frame.setMinimumSize(QtCore.QSize(256, 256))
        self.image_frame.setMaximumSize(QtCore.QSize(256, 256))
        self.image_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.image_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.image_frame.setObjectName("image_frame")
        self.verticalLayout_2.addWidget(self.image_frame)
        self.pushButton = QtWidgets.QPushButton(parent=image_widget)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(parent=image_widget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.prompt = QtWidgets.QPlainTextEdit(parent=image_widget)
        self.prompt.setObjectName("prompt")
        self.verticalLayout.addWidget(self.prompt)
        self.negative_prompt = QtWidgets.QPlainTextEdit(parent=image_widget)
        self.negative_prompt.setObjectName("negative_prompt")
        self.verticalLayout.addWidget(self.negative_prompt)
        self.label = QtWidgets.QLabel(parent=image_widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(parent=image_widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 2, 2)

        self.retranslateUi(image_widget)
        self.pushButton.clicked.connect(image_widget.delete_image) # type: ignore
        self.pushButton_2.clicked.connect(image_widget.send_image_to_grid) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(image_widget)

    def retranslateUi(self, image_widget):
        _translate = QtCore.QCoreApplication.translate
        image_widget.setWindowTitle(_translate("image_widget", "Form"))
        self.pushButton.setText(_translate("image_widget", "Delete"))
        self.pushButton_2.setText(_translate("image_widget", "To Canvas"))
        self.label.setText(_translate("image_widget", "TextLabel"))
        self.label_2.setText(_translate("image_widget", "TextLabel"))
