"""removes is_maximized from database

Revision ID: 01c4eeefa7ba
Revises: d943e9f93c8f
Create Date: 2024-01-11 10:31:19.611695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01c4eeefa7ba'
down_revision: Union[str, None] = 'd943e9f93c8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'is_maximized')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('is_maximized', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
