"""Adds prompt_template to LLMGenerator

Revision ID: 08728ca819b8
Revises: 7c1b15cade9b
Create Date: 2024-01-08 13:46:24.790611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08728ca819b8'
down_revision: Union[str, None] = '7c1b15cade9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_generator', sa.Column('prompt_template', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_generator', 'prompt_template')
    # ### end Alembic commands ###
