"""removes shapegif

Revision ID: 08fb52568b41
Revises: 58c8ac9b9bc2
Create Date: 2023-12-31 07:20:30.109276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08fb52568b41'
down_revision: Union[str, None] = '58c8ac9b9bc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('path_settings', 'gif_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('path_settings', sa.Column('gif_path', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
