"""Add name and is_bot columns to messages table

Revision ID: 092e6840c1f0
Revises: ec10bc30fcf6
Create Date: 2024-09-18 12:07:26.117745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '092e6840c1f0'
down_revision: Union[str, None] = 'ec10bc30fcf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('name', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('is_bot', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'is_bot')
    op.drop_column('messages', 'name')
    # ### end Alembic commands ###
