"""removed unload_unused_models and move_unused_model_to_cpu

Revision ID: 0d6cd68b9c33
Revises: ed3f10d80965
Create Date: 2024-01-11 11:08:33.202984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d6cd68b9c33'
down_revision: Union[str, None] = 'ed3f10d80965'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'move_unused_model_to_cpu')
    op.drop_column('settings', 'unload_unused_model')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('unload_unused_model', sa.BOOLEAN(), nullable=True))
    op.add_column('settings', sa.Column('move_unused_model_to_cpu', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
