"""removes metadata settings from db

Revision ID: 117faf097f7d
Revises: 83be186bd388
Create Date: 2024-01-11 20:33:23.178200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '117faf097f7d'
down_revision: Union[str, None] = '83be186bd388'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metadata_settings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metadata_settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('image_export_metadata_prompt', sa.BOOLEAN(), nullable=True),
    sa.Column('image_export_metadata_negative_prompt', sa.BOOLEAN(), nullable=True),
    sa.Column('image_export_metadata_scale', sa.BOOLEAN(), nullable=True),
    sa.Column('image_export_metadata_seed', sa.BOOLEAN(), nullable=True),
    sa.Column('image_export_metadata_latents_seed', sa.BOOLEAN(), nullable=True),
    sa.Column('image_export_metadata_steps', sa.BOOLEAN(), nullable=True),
    sa.Column('image_export_metadata_ddim_eta', sa.BOOLEAN(), nullable=True),
    sa.Column('image_export_metadata_iterations', sa.BOOLEAN(), nullable=True),
    sa.Column('image_export_metadata_samples', sa.BOOLEAN(), nullable=True),
    sa.Column('image_export_metadata_model', sa.BOOLEAN(), nullable=True),
    sa.Column('image_export_metadata_model_branch', sa.BOOLEAN(), nullable=True),
    sa.Column('image_export_metadata_scheduler', sa.BOOLEAN(), nullable=True),
    sa.Column('export_metadata', sa.BOOLEAN(), nullable=True),
    sa.Column('import_metadata', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
