"""Removed line color from gridsettings

Revision ID: 118a3a9885a8
Revises: b925a36da48e
Create Date: 2024-01-11 09:22:28.231725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '118a3a9885a8'
down_revision: Union[str, None] = 'b925a36da48e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('grid_settings', 'line_color')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grid_settings', sa.Column('line_color', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
