"""removes enable advanced mode from db

Revision ID: 1d37c77854a9
Revises: fd93eaadcbcc
Create Date: 2024-01-11 10:45:28.205245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d37c77854a9'
down_revision: Union[str, None] = 'fd93eaadcbcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'enable_advanced_mode')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('enable_advanced_mode', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
