"""remove rate and volume from speech t5 settings

Revision ID: 1de875096dfc
Revises: f447116b8b54
Create Date: 2025-02-23 08:45:09.519557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '1de875096dfc'
down_revision: Union[str, None] = 'f447116b8b54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_column('speech_t5_settings', 'rate')
    except sa.exc.OperationalError as e:
        print("Error adding column: ", e)

    try:
        op.drop_column('speech_t5_settings', 'volume')
    except sa.exc.OperationalError as e:
        print("Error adding column: ", e)
    # ### end Alembic commands

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('speech_t5_settings', sa.Column('volume', sqlite.FLOAT(), nullable=True))
    op.add_column('speech_t5_settings', sa.Column('rate', sa.INTEGER(), nullable=True))
    # ### end Alembic commands
