"""removes llmgenerator from db

Revision ID: 221d769fae66
Revises: 94307d270d0a
Create Date: 2024-01-12 15:36:20.453019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '221d769fae66'
down_revision: Union[str, None] = '94307d270d0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('llm_generator')
    op.drop_constraint(None, 'llm_model_version', type_='foreignkey')
    op.drop_column('llm_model_version', 'generator_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_model_version', sa.Column('generator_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'llm_model_version', 'llm_generator', ['generator_id'], ['id'])
    op.create_table('llm_generator',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('username', sa.VARCHAR(), nullable=True),
    sa.Column('botname', sa.VARCHAR(), nullable=True),
    sa.Column('message_type', sa.VARCHAR(), nullable=True),
    sa.Column('bot_personality', sa.VARCHAR(), nullable=True),
    sa.Column('override_parameters', sa.BOOLEAN(), nullable=True),
    sa.Column('prompt_template', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
