"""removes active_image_editor_section from db

Revision ID: 269aad196660
Revises: 1d37c77854a9
Create Date: 2024-01-11 10:46:12.995550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '269aad196660'
down_revision: Union[str, None] = '1d37c77854a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'active_image_editor_section')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('active_image_editor_section', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
