"""Added generator_settings_override_id to settings

Revision ID: 28d612bd908c
Revises: 1bbf5fc3748c
Create Date: 2024-01-01 15:34:54.674668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28d612bd908c'
down_revision: Union[str, None] = '1bbf5fc3748c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table("brushes") as batch_op:
        #batch_op.drop_constraint('generator_setting_id', type_='foreignkey')
        batch_op.drop_column('generator_setting_id')

    with op.batch_alter_table("generator_settings") as batch_op:
        #batch_op.drop_constraint('settings_id', type_='foreignkey')
        batch_op.drop_column('settings_id')

    with op.batch_alter_table("settings") as batch_op:
        batch_op.create_foreign_key('settings_id', 'generator_settings', ['generator_settings_override_id'], ['id'])
        batch_op.drop_column('current_section_shape')
        batch_op.drop_column('current_version_kandinsky')
        batch_op.drop_column('current_section_kandinsky')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('current_section_kandinsky', sa.VARCHAR(), nullable=True))
    op.add_column('settings', sa.Column('current_version_kandinsky', sa.VARCHAR(), nullable=True))
    op.add_column('settings', sa.Column('current_section_shape', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'settings', type_='foreignkey')
    op.add_column('generator_settings', sa.Column('settings_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'generator_settings', 'settings', ['settings_id'], ['id'])
    op.add_column('brushes', sa.Column('generator_setting_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'brushes', 'prompt_generator_settings', ['generator_setting_id'], ['id'])
    # ### end Alembic commands ###
