"""modifies llm prompt template

Revision ID: 2b7c183ddd5b
Revises: 117faf097f7d
Create Date: 2024-01-12 14:30:52.983176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b7c183ddd5b'
down_revision: Union[str, None] = '117faf097f7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_prompt_templates', sa.Column('system_instructions', sa.String(), nullable=True))
    op.add_column('llm_prompt_templates', sa.Column('format', sa.String(), nullable=True))
    op.add_column('llm_prompt_templates', sa.Column('llm_category', sa.String(), nullable=True))
    op.drop_column('llm_prompt_templates', 'template')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_prompt_templates', sa.Column('template', sa.VARCHAR(), nullable=True))
    op.drop_column('llm_prompt_templates', 'llm_category')
    op.drop_column('llm_prompt_templates', 'format')
    op.drop_column('llm_prompt_templates', 'system_instructions')
    # ### end Alembic commands ###
