"""removes more settings

Revision ID: 2c32e2454920
Revises: 57d375ea5f33
Create Date: 2024-01-11 10:09:12.527872

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c32e2454920'
down_revision: Union[str, None] = '57d375ea5f33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'allow_online_mode')
    op.drop_column('settings', 'nsfw_filter')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('nsfw_filter', sa.BOOLEAN(), nullable=True))
    op.add_column('settings', sa.Column('allow_online_mode', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
