"""removes current_llm_generator from db

Revision ID: 3c255b9005a8
Revises: 269aad196660
Create Date: 2024-01-11 10:47:33.317575

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c255b9005a8'
down_revision: Union[str, None] = '269aad196660'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'current_llm_generator')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('current_llm_generator', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
