"""removes latest_version_check from database

Revision ID: 428c40a8d424
Revises: ff0580453da8
Create Date: 2024-01-11 10:17:02.783259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '428c40a8d424'
down_revision: Union[str, None] = 'ff0580453da8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'latest_version_check')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('latest_version_check', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
