"""removes allow_hf_downloads from settings model

Revision ID: 43e754e6e2fb
Revises: b0c0214f0527
Create Date: 2024-01-11 10:15:03.981817

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43e754e6e2fb'
down_revision: Union[str, None] = 'b0c0214f0527'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'allow_hf_downloads')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('allow_hf_downloads', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
