"""removed GridSettings model

Revision ID: 57d375ea5f33
Revises: 118a3a9885a8
Create Date: 2024-01-11 09:27:36.837554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from alembic import op
import sqlalchemy as sa
from alembic.operations import Operations, MigrateOperation


# revision identifiers, used by Alembic.
revision: str = '57d375ea5f33'
down_revision: Union[str, None] = '118a3a9885a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grid_settings')
    op.drop_constraint(None, 'settings', type_='foreignkey')
    op.drop_column('settings', 'grid_settings_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('grid_settings_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'settings', 'grid_settings', ['grid_settings_id'], ['id'])
    op.create_table('grid_settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('snap_to_grid', sa.BOOLEAN(), nullable=True),
    sa.Column('cell_size', sa.INTEGER(), nullable=True),
    sa.Column('canvas_color', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
