"""removed current tab and current_section_stablediffusion

Revision ID: 57e8272faf46
Revises: 01c4eeefa7ba
Create Date: 2024-01-11 10:36:37.696480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57e8272faf46'
down_revision: Union[str, None] = '01c4eeefa7ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'current_tab')
    op.drop_column('settings', 'current_section_stablediffusion')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('current_section_stablediffusion', sa.VARCHAR(), nullable=True))
    op.add_column('settings', sa.Column('current_tab', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
