"""Added upscale settings to standard image widget

Revision ID: 58c8ac9b9bc2
Revises: b614791e6186
Create Date: 2023-12-30 12:07:12.998684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58c8ac9b9bc2'
down_revision: Union[str, None] = 'b614791e6186'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('standard_image_widget_settings', sa.Column('upscale_model', sa.String(), nullable=True))
    op.add_column('standard_image_widget_settings', sa.Column('face_enhance', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('standard_image_widget_settings', 'face_enhance')
    op.drop_column('standard_image_widget_settings', 'upscale_model')
    # ### end Alembic commands ###
