"""add chat_store_key column to Conversation table

Revision ID: 6579bf48ed83
Revises: c2c5d4cd4b80
Create Date: 2025-02-14 02:05:31.854218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '6579bf48ed83'
down_revision: Union[str, None] = 'c2c5d4cd4b80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.add_column('conversations', sa.Column('key', sa.String(), nullable=True))
    except sa.exc.OperationalError as e:
        print("Error adding column key:", e)
    try:
        op.add_column('conversations', sa.Column('value', sa.JSON(), nullable=True))
    except sa.exc.OperationalError as e:
        print("Error adding column key:", e)
    # ### end Alembic commands ###
    

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'key')
    op.drop_column('converations', 'value')
    # ### end Alembic commands ###
