"""Adds summary column to conversations table

Revision ID: 6c6cf295a892
Revises: f3d84a9d5049
Create Date: 2025-02-19 02:33:21.496409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '6c6cf295a892'
down_revision: Union[str, None] = 'f3d84a9d5049'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('conversations', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('conversations', sa.Column('user_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('conversations', 'summary')
    op.drop_column('conversations', 'user_data')
    # ### end Alembic commands ###