"""Adds version to embedding and lora tables

Revision ID: 6d98d892995f
Revises: 55c1dff62eba
Create Date: 2024-01-09 14:40:48.810380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d98d892995f'
down_revision: Union[str, None] = '55c1dff62eba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embeddings', sa.Column('version', sa.String(), nullable=True))
    op.add_column('loras', sa.Column('version', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loras', 'version')
    op.drop_column('embeddings', 'version')
    # ### end Alembic commands ###
