"""removes auto_export_images from database

Revision ID: 7cb7442e21e2
Revises: 5a85469cc534
Create Date: 2024-01-11 10:22:31.373514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cb7442e21e2'
down_revision: Union[str, None] = '5a85469cc534'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'auto_export_images')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('auto_export_images', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
