"""removes llm generator setting from db

Revision ID: 83be186bd388
Revises: ca640e5c9d6d
Create Date: 2024-01-11 16:39:24.547116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83be186bd388'
down_revision: Union[str, None] = 'ca640e5c9d6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('llm_generator_settings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('llm_generator_settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('top_p', sa.INTEGER(), nullable=True),
    sa.Column('max_length', sa.INTEGER(), nullable=True),
    sa.Column('repetition_penalty', sa.INTEGER(), nullable=True),
    sa.Column('min_length', sa.INTEGER(), nullable=True),
    sa.Column('length_penalty', sa.INTEGER(), nullable=True),
    sa.Column('num_beams', sa.INTEGER(), nullable=True),
    sa.Column('ngram_size', sa.INTEGER(), nullable=True),
    sa.Column('temperature', sa.INTEGER(), nullable=True),
    sa.Column('sequences', sa.INTEGER(), nullable=True),
    sa.Column('top_k', sa.INTEGER(), nullable=True),
    sa.Column('seed', sa.INTEGER(), nullable=True),
    sa.Column('do_sample', sa.BOOLEAN(), nullable=True),
    sa.Column('eta_cutoff', sa.INTEGER(), nullable=True),
    sa.Column('early_stopping', sa.BOOLEAN(), nullable=True),
    sa.Column('random_seed', sa.BOOLEAN(), nullable=True),
    sa.Column('model_version', sa.VARCHAR(), nullable=True),
    sa.Column('generator_id', sa.INTEGER(), nullable=True),
    sa.Column('dtype', sa.VARCHAR(), nullable=True),
    sa.Column('use_gpu', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['generator_id'], ['llm_generator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
