"""removes mode from db

Revision ID: 83ea7eadcc1d
Revises: 57e8272faf46
Create Date: 2024-01-11 10:40:27.133961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83ea7eadcc1d'
down_revision: Union[str, None] = '57e8272faf46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'mode')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('mode', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
