"""Added version columns to settings

Revision ID: 895b98717b37
Revises: 89850b937fff
Create Date: 2023-12-30 06:10:58.315055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '895b98717b37'
down_revision: Union[str, None] = '89850b937fff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('current_version_stablediffusion', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('current_version_kandinsky', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'current_version_kandinsky')
    op.drop_column('settings', 'current_version_stablediffusion')
    # ### end Alembic commands ###
