"""adds template column to prompt template

Revision ID: 94307d270d0a
Revises: 2b7c183ddd5b
Create Date: 2024-01-12 14:32:21.202489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94307d270d0a'
down_revision: Union[str, None] = '2b7c183ddd5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_prompt_templates', sa.Column('template', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_prompt_templates', 'template')
    # ### end Alembic commands ###
