"""removes hf_username from db

Revision ID: a8c8d93fd5c2
Revises: 83ea7eadcc1d
Create Date: 2024-01-11 10:41:19.887341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8c8d93fd5c2'
down_revision: Union[str, None] = '83ea7eadcc1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'hf_username')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('hf_username', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
