"""removes dark_mode_enabled from settings model

Revision ID: b0c0214f0527
Revises: 2c32e2454920
Create Date: 2024-01-11 10:13:57.612364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0c0214f0527'
down_revision: Union[str, None] = '2c32e2454920'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'dark_mode_enabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('dark_mode_enabled', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
