"""removes DeterministicSettings

Revision ID: b153c5371421
Revises: 28cefd93be12
Create Date: 2024-01-11 12:50:09.824442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b153c5371421'
down_revision: Union[str, None] = '28cefd93be12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deterministic_settings')
    op.drop_table('generator_settings')
    op.drop_constraint(None, 'brushes', type_='foreignkey')
    op.drop_column('brushes', 'generator_setting_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('brushes', sa.Column('generator_setting_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'brushes', 'generator_settings', ['generator_setting_id'], ['id'])
    op.create_table('generator_settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('section', sa.VARCHAR(), nullable=True),
    sa.Column('generator_name', sa.VARCHAR(), nullable=True),
    sa.Column('prompt', sa.VARCHAR(), nullable=True),
    sa.Column('negative_prompt', sa.VARCHAR(), nullable=True),
    sa.Column('steps', sa.INTEGER(), nullable=True),
    sa.Column('ddim_eta', sa.FLOAT(), nullable=True),
    sa.Column('height', sa.INTEGER(), nullable=True),
    sa.Column('width', sa.INTEGER(), nullable=True),
    sa.Column('scale', sa.INTEGER(), nullable=True),
    sa.Column('seed', sa.INTEGER(), nullable=True),
    sa.Column('latents_seed', sa.INTEGER(), nullable=True),
    sa.Column('random_seed', sa.BOOLEAN(), nullable=True),
    sa.Column('random_latents_seed', sa.BOOLEAN(), nullable=True),
    sa.Column('model', sa.VARCHAR(), nullable=True),
    sa.Column('scheduler', sa.VARCHAR(), nullable=True),
    sa.Column('prompt_triggers', sa.VARCHAR(), nullable=True),
    sa.Column('strength', sa.INTEGER(), nullable=True),
    sa.Column('image_guidance_scale', sa.INTEGER(), nullable=True),
    sa.Column('n_samples', sa.INTEGER(), nullable=True),
    sa.Column('controlnet', sa.VARCHAR(), nullable=True),
    sa.Column('enable_controlnet', sa.BOOLEAN(), nullable=True),
    sa.Column('enable_input_image', sa.BOOLEAN(), nullable=True),
    sa.Column('controlnet_guidance_scale', sa.INTEGER(), nullable=True),
    sa.Column('clip_skip', sa.INTEGER(), nullable=True),
    sa.Column('variation', sa.BOOLEAN(), nullable=True),
    sa.Column('input_image_use_imported_image', sa.BOOLEAN(), nullable=True),
    sa.Column('input_image_use_grid_image', sa.BOOLEAN(), nullable=True),
    sa.Column('input_image_recycle_grid_image', sa.BOOLEAN(), nullable=True),
    sa.Column('input_image_mask_use_input_image', sa.BOOLEAN(), nullable=True),
    sa.Column('input_image_mask_use_imported_image', sa.BOOLEAN(), nullable=True),
    sa.Column('controlnet_input_image_link_to_input_image', sa.BOOLEAN(), nullable=True),
    sa.Column('controlnet_input_image_use_imported_image', sa.BOOLEAN(), nullable=True),
    sa.Column('controlnet_use_grid_image', sa.BOOLEAN(), nullable=True),
    sa.Column('controlnet_recycle_grid_image', sa.BOOLEAN(), nullable=True),
    sa.Column('controlnet_mask_link_input_image', sa.BOOLEAN(), nullable=True),
    sa.Column('controlnet_mask_use_imported_image', sa.BOOLEAN(), nullable=True),
    sa.Column('use_prompt_builder', sa.BOOLEAN(), nullable=True),
    sa.Column('active_grid_border_color', sa.VARCHAR(), nullable=True),
    sa.Column('active_grid_fill_color', sa.VARCHAR(), nullable=True),
    sa.Column('version', sa.VARCHAR(), nullable=True),
    sa.Column('is_preset', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deterministic_settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('batch_size', sa.INTEGER(), nullable=True),
    sa.Column('style', sa.VARCHAR(), nullable=True),
    sa.Column('seed', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
