"""Removed show grid from gridsettings

Revision ID: b43466380c79
Revises: e388413af0a7
Create Date: 2024-01-11 08:42:16.031470

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b43466380c79'
down_revision: Union[str, None] = 'e388413af0a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('active_tab')
    op.drop_column('grid_settings', 'show_grid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('grid_settings', sa.Column('show_grid', sa.BOOLEAN(), nullable=True))
    op.create_table('active_tab',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('panel', sa.VARCHAR(), nullable=True),
    sa.Column('active_tab', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
