"""Added standard image widget settings

Revision ID: b614791e6186
Revises: 895b98717b37
Create Date: 2023-12-30 07:36:31.905401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b614791e6186'
down_revision: Union[str, None] = '895b98717b37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('standard_image_widget_settings',
    sa.Column('image_similarity', sa.Integer(), nullable=True),
    sa.Column('controlnet', sa.String(), nullable=True),
    sa.Column('prompt', sa.String(), nullable=True),
    sa.Column('negative_prompt', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('settings', 'image_similarity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('image_similarity', sa.INTEGER(), nullable=True))
    op.drop_table('standard_image_widget_settings')
    # ### end Alembic commands ###
