"""Removed ai_mode

Revision ID: bbc0bfcbbd37
Revises: b212b571ca3d
Create Date: 2024-01-11 07:50:10.247185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbc0bfcbbd37'
down_revision: Union[str, None] = 'b212b571ca3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'ai_mode')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('ai_mode', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
