"""Removes prompt generator

Revision ID: bc6ff97b7e60
Revises: 1aa0b181a56e
Create Date: 2024-01-10 12:55:01.403042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'bc6ff97b7e60'
down_revision: Union[str, None] = '1aa0b181a56e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prompt_generator_settings')
    op.drop_table('prompt_builder')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_builder',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.Column('auto_prompt_weight', sa.FLOAT(), nullable=True),
    sa.Column('text_prompt_weight', sa.FLOAT(), nullable=True),
    sa.Column('negative_auto_prompt_weight', sa.FLOAT(), nullable=True),
    sa.Column('negative_text_prompt_weight', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_generator_settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('settings_id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('advanced_mode', sa.BOOLEAN(), nullable=True),
    sa.Column('category', sa.VARCHAR(), nullable=True),
    sa.Column('prompt_blend_type', sa.INTEGER(), nullable=True),
    sa.Column('prompt', sa.VARCHAR(), nullable=True),
    sa.Column('weighted_values', sqlite.JSON(), nullable=True),
    sa.Column('prompt_genre', sa.VARCHAR(), nullable=True),
    sa.Column('prompt_color', sa.VARCHAR(), nullable=True),
    sa.Column('prompt_style', sa.VARCHAR(), nullable=True),
    sa.Column('prefix', sa.VARCHAR(), nullable=True),
    sa.Column('suffix', sa.VARCHAR(), nullable=True),
    sa.Column('negative_prefix', sa.VARCHAR(), nullable=True),
    sa.Column('negative_suffix', sa.VARCHAR(), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.Column('auto_prompt_weight', sa.FLOAT(), nullable=True),
    sa.Column('text_prompt_weight', sa.FLOAT(), nullable=True),
    sa.Column('negative_auto_prompt_weight', sa.FLOAT(), nullable=True),
    sa.Column('negative_text_prompt_weight', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['settings_id'], ['settings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
