"""removed working width from db

Revision ID: c3fe2868537d
Revises: fe409e30df6a
Create Date: 2024-01-11 11:01:22.538602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3fe2868537d'
down_revision: Union[str, None] = 'fe409e30df6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'working_width')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('working_width', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
