"""removes image_export_type from database

Revision ID: c7a88be92174
Revises: 7cb7442e21e2
Create Date: 2024-01-11 10:24:45.906649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7a88be92174'
down_revision: Union[str, None] = '7cb7442e21e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'image_export_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('image_export_type', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
