"""add knowledge tables

Revision ID: d926f5d4c702
Revises: 533e97f2b74c
Create Date: 2025-10-23 10:54:43.200123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'd926f5d4c702'
down_revision: Union[str, None] = '533e97f2b74c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fine_tuned_models')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fine_tuned_models',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('date_added', sa.DATETIME(), nullable=True),
    sa.Column('last_trained', sa.DATETIME(), nullable=True),
    sa.Column('files_used', sqlite.JSON(), nullable=True),
    sa.Column('settings', sqlite.JSON(), nullable=True),
    sa.Column('tags', sqlite.JSON(), nullable=True),
    sa.Column('adapter_path', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_fine_tuned_models_name')
    )
    # ### end Alembic commands ###