"""removes use_interpolation from db

Revision ID: d943e9f93c8f
Revises: 8ca608a5cbb2
Create Date: 2024-01-11 10:30:29.618307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd943e9f93c8f'
down_revision: Union[str, None] = '8ca608a5cbb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'use_interpolation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('use_interpolation', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
