"""Removes Document from db

Revision ID: fb0badd5a574
Revises: 221d769fae66
Create Date: 2024-01-14 08:31:30.583482

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb0badd5a574'
down_revision: Union[str, None] = '221d769fae66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_table('documents')
    except Exception as e:
        print(e)
    try:
        op.drop_table('standard_image_widget_settings')
    except Exception as e:
        print(e)

    try:
        op.drop_constraint(None, 'layers', type_='foreignkey')
    except Exception as e:
        print(e)

    try:
        op.drop_column('layers', 'document_id')
    except Exception as e:
        print(e)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('layers', sa.Column('document_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'layers', 'documents', ['document_id'], ['id'])
    op.create_table('standard_image_widget_settings',
    sa.Column('image_similarity', sa.INTEGER(), nullable=True),
    sa.Column('controlnet', sa.VARCHAR(), nullable=True),
    sa.Column('prompt', sa.VARCHAR(), nullable=True),
    sa.Column('negative_prompt', sa.VARCHAR(), nullable=True),
    sa.Column('upscale_model', sa.VARCHAR(), nullable=True),
    sa.Column('face_enhance', sa.BOOLEAN(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
