"""removes hf keys from db

Revision ID: fd93eaadcbcc
Revises: a8c8d93fd5c2
Create Date: 2024-01-11 10:42:32.443537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd93eaadcbcc'
down_revision: Union[str, None] = 'a8c8d93fd5c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'working_height')
    op.drop_column('settings', 'hf_api_key_read_key')
    op.drop_column('settings', 'hf_api_key_write_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('hf_api_key_write_key', sa.VARCHAR(), nullable=True))
    op.add_column('settings', sa.Column('hf_api_key_read_key', sa.VARCHAR(), nullable=True))
    op.add_column('settings', sa.Column('working_height', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
