"""removes current_image_generator from db

Revision ID: fe409e30df6a
Revises: 3c255b9005a8
Create Date: 2024-01-11 10:49:10.544066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe409e30df6a'
down_revision: Union[str, None] = '3c255b9005a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'current_image_generator')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('current_image_generator', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
