"""removes image_to_new_layer from settings model

Revision ID: ff0580453da8
Revises: 43e754e6e2fb
Create Date: 2024-01-11 10:16:15.720617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff0580453da8'
down_revision: Union[str, None] = '43e754e6e2fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'image_to_new_layer')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('image_to_new_layer', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
