# Form implementation generated from reading ui file '/home/joe/Projects/imagetopixel/airunner/src/airunner/widgets/layers/templates/layer_image_widget.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_layer_image_widget(object):
    def setupUi(self, layer_image_widget):
        layer_image_widget.setObjectName("layer_image_widget")
        layer_image_widget.resize(325, 56)
        self.gridLayout = QtWidgets.QGridLayout(layer_image_widget)
        self.gridLayout.setObjectName("gridLayout")
        self.visible_button = QtWidgets.QPushButton(parent=layer_image_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.visible_button.sizePolicy().hasHeightForWidth())
        self.visible_button.setSizePolicy(sizePolicy)
        self.visible_button.setMinimumSize(QtCore.QSize(38, 38))
        self.visible_button.setMaximumSize(QtCore.QSize(38, 38))
        self.visible_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/dark/eye-look-icon.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.visible_button.setIcon(icon)
        self.visible_button.setCheckable(True)
        self.visible_button.setFlat(True)
        self.visible_button.setObjectName("visible_button")
        self.gridLayout.addWidget(self.visible_button, 0, 0, 1, 1)
        self.thumbnail = QtWidgets.QLabel(parent=layer_image_widget)
        self.thumbnail.setMinimumSize(QtCore.QSize(38, 38))
        self.thumbnail.setMaximumSize(QtCore.QSize(38, 38))
        self.thumbnail.setText("")
        self.thumbnail.setObjectName("thumbnail")
        self.gridLayout.addWidget(self.thumbnail, 0, 1, 1, 1)
        self.opacity_slider = SliderWidget(parent=layer_image_widget)
        self.opacity_slider.setObjectName("opacity_slider")
        self.gridLayout.addWidget(self.opacity_slider, 0, 2, 1, 1)

        self.retranslateUi(layer_image_widget)
        self.visible_button.toggled['bool'].connect(layer_image_widget.action_clicked_button_toggle_image_visibility) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(layer_image_widget)

    def retranslateUi(self, layer_image_widget):
        _translate = QtCore.QCoreApplication.translate
        layer_image_widget.setWindowTitle(_translate("layer_image_widget", "Form"))
from airunner.widgets.slider.slider_widget import SliderWidget
