# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.9.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGridLayout, QMainWindow,
    QMenu, QMenuBar, QPushButton, QSizePolicy,
    QSpacerItem, QSplitter, QStatusBar, QTabWidget,
    QVBoxLayout, QWidget)

from airunner.components.llm.gui.widgets.generator_form.generator_form_widget import GeneratorForm
import airunner.feather_rc

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1074, 760)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.MinimumExpanding, QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QSize(0, 0))
        font = QFont()
        font.setPointSize(8)
        MainWindow.setFont(font)
        icon = QIcon()
        icon.addFile(u":/icons/icon_256.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet(u"")
        self.actionCopy = QAction(MainWindow)
        self.actionCopy.setObjectName(u"actionCopy")
        icon1 = QIcon()
        icon1.addFile(u":/light/icons/feather/light/copy.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionCopy.setIcon(icon1)
        self.actionPaste = QAction(MainWindow)
        self.actionPaste.setObjectName(u"actionPaste")
        icon2 = QIcon()
        icon2.addFile(u":/light/icons/feather/light/clipboard.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionPaste.setIcon(icon2)
        self.actionAbout = QAction(MainWindow)
        self.actionAbout.setObjectName(u"actionAbout")
        self.actionQuit = QAction(MainWindow)
        self.actionQuit.setObjectName(u"actionQuit")
        icon3 = QIcon()
        icon3.addFile(u":/light/icons/feather/light/x-circle.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionQuit.setIcon(icon3)
        self.actionBug_report = QAction(MainWindow)
        self.actionBug_report.setObjectName(u"actionBug_report")
        icon4 = QIcon()
        icon4.addFile(u":/light/icons/feather/light/external-link.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionBug_report.setIcon(icon4)
        self.actionReport_vulnerability = QAction(MainWindow)
        self.actionReport_vulnerability.setObjectName(u"actionReport_vulnerability")
        self.actionReport_vulnerability.setIcon(icon4)
        self.actionPrompt_Browser = QAction(MainWindow)
        self.actionPrompt_Browser.setObjectName(u"actionPrompt_Browser")
        icon5 = QIcon()
        icon5.addFile(u":/light/icons/feather/light/book-open.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionPrompt_Browser.setIcon(icon5)
        self.actionClear_all_prompts = QAction(MainWindow)
        self.actionClear_all_prompts.setObjectName(u"actionClear_all_prompts")
        icon6 = QIcon()
        icon6.addFile(u":/light/icons/feather/light/delete.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionClear_all_prompts.setIcon(icon6)
        self.actionCut = QAction(MainWindow)
        self.actionCut.setObjectName(u"actionCut")
        icon7 = QIcon()
        icon7.addFile(u":/light/icons/feather/light/scissors.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionCut.setIcon(icon7)
        self.actionBrowse_AI_Runner_Path = QAction(MainWindow)
        self.actionBrowse_AI_Runner_Path.setObjectName(u"actionBrowse_AI_Runner_Path")
        icon8 = QIcon()
        icon8.addFile(u":/light/icons/feather/light/folder.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionBrowse_AI_Runner_Path.setIcon(icon8)
        self.actionBrowse_Images_Path_2 = QAction(MainWindow)
        self.actionBrowse_Images_Path_2.setObjectName(u"actionBrowse_Images_Path_2")
        self.actionBrowse_Images_Path_2.setIcon(icon8)
        self.actionReset_Settings_2 = QAction(MainWindow)
        self.actionReset_Settings_2.setObjectName(u"actionReset_Settings_2")
        icon9 = QIcon()
        icon9.addFile(u":/light/icons/feather/light/refresh-cw.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionReset_Settings_2.setIcon(icon9)
        self.actionSafety_Checker = QAction(MainWindow)
        self.actionSafety_Checker.setObjectName(u"actionSafety_Checker")
        self.actionSafety_Checker.setCheckable(True)
        self.actionSafety_Checker.setChecked(False)
        icon10 = QIcon()
        icon10.addFile(u":/light/icons/feather/light/slash.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionSafety_Checker.setIcon(icon10)
        self.actionRun_setup_wizard_2 = QAction(MainWindow)
        self.actionRun_setup_wizard_2.setObjectName(u"actionRun_setup_wizard_2")
        icon11 = QIcon()
        icon11.addFile(u":/light/icons/feather/light/zap.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionRun_setup_wizard_2.setIcon(icon11)
        self.actionSettings = QAction(MainWindow)
        self.actionSettings.setObjectName(u"actionSettings")
        icon12 = QIcon()
        icon12.addFile(u":/light/icons/feather/light/settings.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionSettings.setIcon(icon12)
        self.actionToggle_LLM = QAction(MainWindow)
        self.actionToggle_LLM.setObjectName(u"actionToggle_LLM")
        self.actionToggle_LLM.setCheckable(True)
        self.actionToggle_LLM.setChecked(False)
        icon13 = QIcon()
        icon13.addFile(u":/light/icons/feather/light/cpu.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionToggle_LLM.setIcon(icon13)
        self.actionToggle_Text_to_Speech = QAction(MainWindow)
        self.actionToggle_Text_to_Speech.setObjectName(u"actionToggle_Text_to_Speech")
        self.actionToggle_Text_to_Speech.setCheckable(True)
        icon14 = QIcon()
        icon14.addFile(u":/light/icons/feather/light/speaker.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionToggle_Text_to_Speech.setIcon(icon14)
        self.actionToggle_Speech_to_Text = QAction(MainWindow)
        self.actionToggle_Speech_to_Text.setObjectName(u"actionToggle_Speech_to_Text")
        self.actionToggle_Speech_to_Text.setCheckable(True)
        icon15 = QIcon()
        icon15.addFile(u":/light/icons/feather/light/mic.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionToggle_Speech_to_Text.setIcon(icon15)
        self.actionToggle_Stable_Diffusion = QAction(MainWindow)
        self.actionToggle_Stable_Diffusion.setObjectName(u"actionToggle_Stable_Diffusion")
        self.actionToggle_Stable_Diffusion.setCheckable(True)
        icon16 = QIcon()
        icon16.addFile(u":/light/icons/feather/light/image.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionToggle_Stable_Diffusion.setIcon(icon16)
        self.artActionNew = QAction(MainWindow)
        self.artActionNew.setObjectName(u"artActionNew")
        icon17 = QIcon()
        icon17.addFile(u":/light/icons/feather/light/plus-circle.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.artActionNew.setIcon(icon17)
        self.actionImport_image = QAction(MainWindow)
        self.actionImport_image.setObjectName(u"actionImport_image")
        icon18 = QIcon()
        icon18.addFile(u":/light/icons/feather/light/download.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionImport_image.setIcon(icon18)
        self.actionExport_image_button = QAction(MainWindow)
        self.actionExport_image_button.setObjectName(u"actionExport_image_button")
        icon19 = QIcon()
        icon19.addFile(u":/light/icons/feather/light/upload.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionExport_image_button.setIcon(icon19)
        self.actionNew_Conversation = QAction(MainWindow)
        self.actionNew_Conversation.setObjectName(u"actionNew_Conversation")
        icon20 = QIcon()
        icon20.addFile(u":/light/icons/feather/light/message-circle.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionNew_Conversation.setIcon(icon20)
        self.actionDelete_conversation = QAction(MainWindow)
        self.actionDelete_conversation.setObjectName(u"actionDelete_conversation")
        icon21 = QIcon()
        icon21.addFile(u":/light/icons/feather/light/trash-2.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionDelete_conversation.setIcon(icon21)
        self.actionDiscussions = QAction(MainWindow)
        self.actionDiscussions.setObjectName(u"actionDiscussions")
        icon22 = QIcon()
        icon22.addFile(u":/light/icons/feather/light/message-square.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionDiscussions.setIcon(icon22)
        self.actionDownload_Model = QAction(MainWindow)
        self.actionDownload_Model.setObjectName(u"actionDownload_Model")
        icon23 = QIcon()
        icon23.addFile(u":/light/icons/feather/light/arrow-down-circle.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.actionDownload_Model.setIcon(icon23)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.centralwidget.setEnabled(True)
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy1)
        self.centralwidget.setMinimumSize(QSize(0, 0))
        self.centralwidget.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.gridLayout_3 = QGridLayout(self.centralwidget)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.mode_tab_widget = QWidget(self.centralwidget)
        self.mode_tab_widget.setObjectName(u"mode_tab_widget")
        self.mode_tab_widget.setAutoFillBackground(False)
        self.mode_tab_widget.setStyleSheet(u"QTabWidget#mode_tab_widget::pane { border: 0; background: transparent; }")
        self.gridLayout = QGridLayout(self.mode_tab_widget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(5, 5, 5, 0)
        self.actionsidebar = QWidget(self.mode_tab_widget)
        self.actionsidebar.setObjectName(u"actionsidebar")
        self.action_sidebar = QVBoxLayout(self.actionsidebar)
        self.action_sidebar.setSpacing(5)
        self.action_sidebar.setObjectName(u"action_sidebar")
        self.action_sidebar.setContentsMargins(5, 5, 5, 5)
        self.chat_button = QPushButton(self.actionsidebar)
        self.chat_button.setObjectName(u"chat_button")
        self.chat_button.setMinimumSize(QSize(35, 35))
        self.chat_button.setMaximumSize(QSize(35, 35))
        self.chat_button.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.chat_button.setIcon(icon22)
        self.chat_button.setIconSize(QSize(20, 20))
        self.chat_button.setCheckable(True)
        self.chat_button.setChecked(True)
        self.chat_button.setFlat(True)

        self.action_sidebar.addWidget(self.chat_button)

        self.knowledgebase_button = QPushButton(self.actionsidebar)
        self.knowledgebase_button.setObjectName(u"knowledgebase_button")
        self.knowledgebase_button.setMinimumSize(QSize(35, 35))
        self.knowledgebase_button.setMaximumSize(QSize(35, 35))
        self.knowledgebase_button.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon24 = QIcon()
        icon24.addFile(u":/light/icons/feather/light/book.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.knowledgebase_button.setIcon(icon24)
        self.knowledgebase_button.setIconSize(QSize(20, 20))
        self.knowledgebase_button.setCheckable(True)
        self.knowledgebase_button.setFlat(True)

        self.action_sidebar.addWidget(self.knowledgebase_button)

        self.verticalSpacer = QSpacerItem(20, 40, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.action_sidebar.addItem(self.verticalSpacer)

        self.line = QFrame(self.actionsidebar)
        self.line.setObjectName(u"line")
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)

        self.action_sidebar.addWidget(self.line)

        self.text_to_speech_button = QPushButton(self.actionsidebar)
        self.text_to_speech_button.setObjectName(u"text_to_speech_button")
        self.text_to_speech_button.setMinimumSize(QSize(35, 35))
        self.text_to_speech_button.setMaximumSize(QSize(35, 35))
        self.text_to_speech_button.setIcon(icon14)
        self.text_to_speech_button.setIconSize(QSize(20, 20))
        self.text_to_speech_button.setCheckable(True)
        self.text_to_speech_button.setFlat(True)

        self.action_sidebar.addWidget(self.text_to_speech_button)

        self.speech_to_text_button = QPushButton(self.actionsidebar)
        self.speech_to_text_button.setObjectName(u"speech_to_text_button")
        self.speech_to_text_button.setMinimumSize(QSize(35, 35))
        self.speech_to_text_button.setMaximumSize(QSize(35, 35))
        self.speech_to_text_button.setIcon(icon15)
        self.speech_to_text_button.setIconSize(QSize(20, 20))
        self.speech_to_text_button.setCheckable(True)
        self.speech_to_text_button.setFlat(True)

        self.action_sidebar.addWidget(self.speech_to_text_button)


        self.gridLayout.addWidget(self.actionsidebar, 0, 0, 2, 1)

        self.actionsidebar_right = QWidget(self.mode_tab_widget)
        self.actionsidebar_right.setObjectName(u"actionsidebar_right")
        self.verticalLayout = QVBoxLayout(self.actionsidebar_right)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.stats_button = QPushButton(self.actionsidebar_right)
        self.stats_button.setObjectName(u"stats_button")
        self.stats_button.setMinimumSize(QSize(35, 35))
        self.stats_button.setMaximumSize(QSize(35, 35))
        self.stats_button.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        icon25 = QIcon()
        icon25.addFile(u":/light/icons/feather/light/activity.svg", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.stats_button.setIcon(icon25)
        self.stats_button.setCheckable(True)
        self.stats_button.setFlat(True)

        self.verticalLayout.addWidget(self.stats_button)

        self.verticalSpacer_2 = QSpacerItem(20, 574, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Expanding)

        self.verticalLayout.addItem(self.verticalSpacer_2)

        self.settings_button = QPushButton(self.actionsidebar_right)
        self.settings_button.setObjectName(u"settings_button")
        self.settings_button.setMinimumSize(QSize(35, 35))
        self.settings_button.setMaximumSize(QSize(35, 35))
        self.settings_button.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.settings_button.setIcon(icon12)
        self.settings_button.setIconSize(QSize(20, 20))
        self.settings_button.setFlat(True)

        self.verticalLayout.addWidget(self.settings_button)


        self.gridLayout.addWidget(self.actionsidebar_right, 0, 2, 2, 1)

        self.main_window_splitter = QSplitter(self.mode_tab_widget)
        self.main_window_splitter.setObjectName(u"main_window_splitter")
        self.main_window_splitter.setOrientation(Qt.Orientation.Horizontal)
        self.documents_sidebar = QWidget(self.main_window_splitter)
        self.documents_sidebar.setObjectName(u"documents_sidebar")
        sizePolicy1.setHeightForWidth(self.documents_sidebar.sizePolicy().hasHeightForWidth())
        self.documents_sidebar.setSizePolicy(sizePolicy1)
        self.documents_sidebar.setMinimumSize(QSize(64, 0))
        self.gridLayout_documents_sidebar = QGridLayout(self.documents_sidebar)
        self.gridLayout_documents_sidebar.setObjectName(u"gridLayout_documents_sidebar")
        self.gridLayout_documents_sidebar.setContentsMargins(0, 0, 0, 0)
        self.documents_placeholder = QWidget(self.documents_sidebar)
        self.documents_placeholder.setObjectName(u"documents_placeholder")

        self.gridLayout_documents_sidebar.addWidget(self.documents_placeholder, 0, 0, 1, 1)

        self.main_window_splitter.addWidget(self.documents_sidebar)
        self.generator_widget = GeneratorForm(self.main_window_splitter)
        self.generator_widget.setObjectName(u"generator_widget")
        self.generator_widget.setEnabled(True)
        sizePolicy1.setHeightForWidth(self.generator_widget.sizePolicy().hasHeightForWidth())
        self.generator_widget.setSizePolicy(sizePolicy1)
        self.generator_widget.setMinimumSize(QSize(250, 0))
        self.generator_widget.setMaximumSize(QSize(16777215, 16777215))
        self.generator_widget.setBaseSize(QSize(250, 0))
        self.main_window_splitter.addWidget(self.generator_widget)
        self.center_widget = QWidget(self.main_window_splitter)
        self.center_widget.setObjectName(u"center_widget")
        sizePolicy1.setHeightForWidth(self.center_widget.sizePolicy().hasHeightForWidth())
        self.center_widget.setSizePolicy(sizePolicy1)
        self.center_widget.setMinimumSize(QSize(64, 0))
        self.gridLayout_4 = QGridLayout(self.center_widget)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.center_tab_container = QWidget(self.center_widget)
        self.center_tab_container.setObjectName(u"center_tab_container")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Expanding)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.center_tab_container.sizePolicy().hasHeightForWidth())
        self.center_tab_container.setSizePolicy(sizePolicy2)
        self.center_tab_container.setBaseSize(QSize(0, 0))
        self.center_tab_container.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.gridLayout_2 = QGridLayout(self.center_tab_container)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.canvas_placeholder = QWidget(self.center_tab_container)
        self.canvas_placeholder.setObjectName(u"canvas_placeholder")
        sizePolicy2.setHeightForWidth(self.canvas_placeholder.sizePolicy().hasHeightForWidth())
        self.canvas_placeholder.setSizePolicy(sizePolicy2)
        self.canvas_placeholder.setMinimumSize(QSize(0, 0))
        self.canvas_placeholder.setMaximumSize(QSize(16777215, 16777215))
        self.canvas_placeholder.setCursor(QCursor(Qt.CursorShape.ArrowCursor))
        self.canvas_placeholder.setAcceptDrops(True)

        self.gridLayout_2.addWidget(self.canvas_placeholder, 0, 0, 1, 1)


        self.gridLayout_4.addWidget(self.center_tab_container, 0, 0, 1, 1)

        self.main_window_splitter.addWidget(self.center_widget)
        self.rightsidebar = QWidget(self.main_window_splitter)
        self.rightsidebar.setObjectName(u"rightsidebar")
        self.gridLayout_7 = QGridLayout(self.rightsidebar)
        self.gridLayout_7.setObjectName(u"gridLayout_7")
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.sidebar_tab = QTabWidget(self.rightsidebar)
        self.sidebar_tab.setObjectName(u"sidebar_tab")
        self.stats_placeholder = QWidget()
        self.stats_placeholder.setObjectName(u"stats_placeholder")
        self.sidebar_tab.addTab(self.stats_placeholder, "")

        self.gridLayout_7.addWidget(self.sidebar_tab, 0, 0, 1, 1)

        self.main_window_splitter.addWidget(self.rightsidebar)

        self.gridLayout.addWidget(self.main_window_splitter, 0, 1, 2, 1)


        self.gridLayout_3.addWidget(self.mode_tab_widget, 0, 0, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1074, 26))
        font1 = QFont()
        font1.setPointSize(11)
        self.menubar.setFont(font1)
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuFile.setTearOffEnabled(False)
        self.menuFile.setSeparatorsCollapsible(False)
        self.menuArt = QMenu(self.menuFile)
        self.menuArt.setObjectName(u"menuArt")
        self.menuArt.setIcon(icon16)
        self.menuChat = QMenu(self.menuFile)
        self.menuChat.setObjectName(u"menuChat")
        self.menuChat.setIcon(icon20)
        self.menuEdit = QMenu(self.menubar)
        self.menuEdit.setObjectName(u"menuEdit")
        self.menuFilters = QMenu(self.menubar)
        self.menuFilters.setObjectName(u"menuFilters")
        self.menuAbout = QMenu(self.menubar)
        self.menuAbout.setObjectName(u"menuAbout")
        self.menuAbout.setTearOffEnabled(False)
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")
        self.menuTools = QMenu(self.menubar)
        self.menuTools.setObjectName(u"menuTools")
        self.menuStable_Diffusion = QMenu(self.menuTools)
        self.menuStable_Diffusion.setObjectName(u"menuStable_Diffusion")
        self.menuStable_Diffusion.setIcon(icon16)
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuFilters.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.menuFile.addAction(self.menuArt.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.menuChat.menuAction())
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionReset_Settings_2)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionQuit)
        self.menuFile.addSeparator()
        self.menuArt.addAction(self.artActionNew)
        self.menuArt.addAction(self.actionImport_image)
        self.menuArt.addAction(self.actionExport_image_button)
        self.menuChat.addAction(self.actionNew_Conversation)
        self.menuChat.addAction(self.actionDelete_conversation)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionCut)
        self.menuEdit.addAction(self.actionCopy)
        self.menuEdit.addAction(self.actionPaste)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionClear_all_prompts)
        self.menuEdit.addSeparator()
        self.menuEdit.addAction(self.actionSettings)
        self.menuFilters.addSeparator()
        self.menuAbout.addAction(self.actionAbout)
        self.menuAbout.addAction(self.actionBug_report)
        self.menuAbout.addAction(self.actionReport_vulnerability)
        self.menuAbout.addSeparator()
        self.menuAbout.addAction(self.actionDiscussions)
        self.menuView.addAction(self.actionPrompt_Browser)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionBrowse_AI_Runner_Path)
        self.menuView.addSeparator()
        self.menuView.addAction(self.actionBrowse_Images_Path_2)
        self.menuView.addSeparator()
        self.menuTools.addAction(self.menuStable_Diffusion.menuAction())
        self.menuTools.addSeparator()
        self.menuTools.addSeparator()
        self.menuTools.addAction(self.actionRun_setup_wizard_2)
        self.menuTools.addSeparator()
        self.menuStable_Diffusion.addAction(self.actionSafety_Checker)
        self.menuStable_Diffusion.addAction(self.actionDownload_Model)

        self.retranslateUi(MainWindow)

        self.sidebar_tab.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"AI Runner", None))
        self.actionCopy.setText(QCoreApplication.translate("MainWindow", u"Copy", None))
#if QT_CONFIG(shortcut)
        self.actionCopy.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+C", None))
#endif // QT_CONFIG(shortcut)
        self.actionPaste.setText(QCoreApplication.translate("MainWindow", u"Paste", None))
#if QT_CONFIG(shortcut)
        self.actionPaste.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+V", None))
#endif // QT_CONFIG(shortcut)
        self.actionAbout.setText(QCoreApplication.translate("MainWindow", u"About", None))
        self.actionQuit.setText(QCoreApplication.translate("MainWindow", u"Quit", None))
#if QT_CONFIG(shortcut)
        self.actionQuit.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Q", None))
#endif // QT_CONFIG(shortcut)
        self.actionBug_report.setText(QCoreApplication.translate("MainWindow", u"Bug report", None))
        self.actionReport_vulnerability.setText(QCoreApplication.translate("MainWindow", u"Report vulnerability", None))
        self.actionPrompt_Browser.setText(QCoreApplication.translate("MainWindow", u"Prompt browser", None))
        self.actionClear_all_prompts.setText(QCoreApplication.translate("MainWindow", u"Clear all prompts", None))
#if QT_CONFIG(tooltip)
        self.actionClear_all_prompts.setToolTip(QCoreApplication.translate("MainWindow", u"Remove text from all prompts and negative prompts", None))
#endif // QT_CONFIG(tooltip)
        self.actionCut.setText(QCoreApplication.translate("MainWindow", u"Cut", None))
#if QT_CONFIG(shortcut)
        self.actionCut.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+X", None))
#endif // QT_CONFIG(shortcut)
        self.actionBrowse_AI_Runner_Path.setText(QCoreApplication.translate("MainWindow", u"Browse AI Runner Path", None))
        self.actionBrowse_Images_Path_2.setText(QCoreApplication.translate("MainWindow", u"Browse Images", None))
        self.actionReset_Settings_2.setText(QCoreApplication.translate("MainWindow", u"Reset Settings", None))
        self.actionSafety_Checker.setText(QCoreApplication.translate("MainWindow", u"Safety Checker", None))
        self.actionRun_setup_wizard_2.setText(QCoreApplication.translate("MainWindow", u"Run Setup Wizard", None))
        self.actionSettings.setText(QCoreApplication.translate("MainWindow", u"Preferences", None))
        self.actionToggle_LLM.setText(QCoreApplication.translate("MainWindow", u"Toggle LLM", None))
        self.actionToggle_Text_to_Speech.setText(QCoreApplication.translate("MainWindow", u"Toggle Text to Speech", None))
        self.actionToggle_Speech_to_Text.setText(QCoreApplication.translate("MainWindow", u"Toggle Speech to Text", None))
        self.actionToggle_Stable_Diffusion.setText(QCoreApplication.translate("MainWindow", u"Toggle Stable Diffusion", None))
        self.artActionNew.setText(QCoreApplication.translate("MainWindow", u"New", None))
        self.actionImport_image.setText(QCoreApplication.translate("MainWindow", u"Import image", None))
#if QT_CONFIG(shortcut)
        self.actionImport_image.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+I", None))
#endif // QT_CONFIG(shortcut)
        self.actionExport_image_button.setText(QCoreApplication.translate("MainWindow", u"Export image", None))
#if QT_CONFIG(shortcut)
        self.actionExport_image_button.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+E", None))
#endif // QT_CONFIG(shortcut)
        self.actionNew_Conversation.setText(QCoreApplication.translate("MainWindow", u"New Conversation", None))
        self.actionDelete_conversation.setText(QCoreApplication.translate("MainWindow", u"Delete conversation", None))
        self.actionDiscussions.setText(QCoreApplication.translate("MainWindow", u"Discussions", None))
        self.actionDownload_Model.setText(QCoreApplication.translate("MainWindow", u"Download Model", None))
#if QT_CONFIG(tooltip)
        self.chat_button.setToolTip(QCoreApplication.translate("MainWindow", u"Toggle Chat", None))
#endif // QT_CONFIG(tooltip)
        self.chat_button.setText("")
#if QT_CONFIG(tooltip)
        self.knowledgebase_button.setToolTip(QCoreApplication.translate("MainWindow", u"Toggle Knowledgebase", None))
#endif // QT_CONFIG(tooltip)
        self.knowledgebase_button.setText("")
#if QT_CONFIG(tooltip)
        self.text_to_speech_button.setToolTip(QCoreApplication.translate("MainWindow", u"Toggle Text to Speech", None))
#endif // QT_CONFIG(tooltip)
        self.text_to_speech_button.setText("")
#if QT_CONFIG(tooltip)
        self.speech_to_text_button.setToolTip(QCoreApplication.translate("MainWindow", u"Toggle Speech to Text", None))
#endif // QT_CONFIG(tooltip)
        self.speech_to_text_button.setText("")
#if QT_CONFIG(tooltip)
        self.stats_button.setToolTip(QCoreApplication.translate("MainWindow", u"Toggle VRAM Stats", None))
#endif // QT_CONFIG(tooltip)
        self.stats_button.setText("")
#if QT_CONFIG(tooltip)
        self.settings_button.setToolTip(QCoreApplication.translate("MainWindow", u"Settings", None))
#endif // QT_CONFIG(tooltip)
        self.settings_button.setText("")
        self.sidebar_tab.setTabText(self.sidebar_tab.indexOf(self.stats_placeholder), QCoreApplication.translate("MainWindow", u"Page", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.menuArt.setTitle(QCoreApplication.translate("MainWindow", u"Art", None))
        self.menuChat.setTitle(QCoreApplication.translate("MainWindow", u"Chat", None))
        self.menuEdit.setTitle(QCoreApplication.translate("MainWindow", u"Edit", None))
        self.menuFilters.setTitle(QCoreApplication.translate("MainWindow", u"Filters", None))
        self.menuAbout.setTitle(QCoreApplication.translate("MainWindow", u"Help", None))
        self.menuView.setTitle(QCoreApplication.translate("MainWindow", u"View", None))
        self.menuTools.setTitle(QCoreApplication.translate("MainWindow", u"Tools", None))
        self.menuStable_Diffusion.setTitle(QCoreApplication.translate("MainWindow", u"Art", None))
    # retranslateUi

