.TH AIRUNNER-CIVITAI-DOWNLOAD 1 "October 2026" "airunner 6.1.3" "User Commands"
.SH NAME
airunner-civitai-download \- CivitAI model downloader CLI tool.
.SH SYNOPSIS
.B airunner-civitai-download
.RI [ OPTIONS ]
.SH DESCRIPTION
.B airunner-civitai-download
is a CivitAI model downloader CLI tool.
.PP
This is the services-only package: it contains no Qt desktop client.
.SH SEE ALSO
.BR airunner-hf-download (1),
https://github.com/Capsize-Games/airunner
