.TH AIRUNNER-GENERATE-MIGRATION 1 "October 2026" "airunner 6.1.3" "User Commands"
.SH NAME
airunner-generate-migration \- Generate service-owned Alembic migrations.
.SH SYNOPSIS
.B airunner-generate-migration
.RI [ OPTIONS ]
.SH DESCRIPTION
.B airunner-generate-migration
generates service-owned Alembic migrations for AIRunner.
.PP
This is the services-only package: it contains no Qt desktop client.
.SH SEE ALSO
https://github.com/Capsize-Games/airunner
