.TH AIRUNNER-HF-DOWNLOAD 1 "October 2026" "airunner 6.1.3" "User Commands"
.SH NAME
airunner-hf-download \- HuggingFace model download utility.
.SH SYNOPSIS
.B airunner-hf-download
.RI [ OPTIONS ]
.SH DESCRIPTION
.B airunner-hf-download
is a HuggingFace model download utility for AI Runner.
.PP
This is the services-only package: it contains no Qt desktop client.
.SH SEE ALSO
.BR airunner-civitai-download (1),
https://github.com/Capsize-Games/airunner
