"""Backward-compatible settings module — delegates to ``conf.settings``.

All new code should import directly from
:mod:`airunner_services.conf`::

    from airunner_services.conf import settings
    db_url = settings.DATABASE_URL

Existing imports of ``from airunner_services.settings import AIRUNNER_*``
continue to work through this module.
"""

from __future__ import annotations

import logging
import os

from dotenv import load_dotenv

from airunner_services.conf import settings as _settings

# ---- .env loading (preserved for backward compat) ----
if os.environ.get("DEV_ENV", "1") == "1":
    load_dotenv(override=True)


# ------------------------------------------------------------------
# Re-export all known setting names.
# These resolve lazily through LazySettings so values reflect the
# full resolution chain (defaults → .env → env vars → preset).
# ------------------------------------------------------------------
def _get(name: str, default=None):
    """Read one setting from the new conf module."""
    return getattr(_settings, name, default)


DEV_ENV = _get("DEPLOYMENT_MODE") == "development"

AIRUNNER_VERSION = _get("AIRUNNER_VERSION", "5.0.0")
AIRUNNER_BASE_PATH = _get("AIRUNNER_BASE_PATH")
AIRUNNER_USER_DATA_PATH = _get("AIRUNNER_USER_DATA_PATH")
MODELS_DIR = _get("MODELS_DIR")

AIRUNNER_DB_URL = _get("AIRUNNER_DB_URL")

AIRUNNER_SERVER_HOST = _get("AIRUNNER_SERVER_HOST")
AIRUNNER_SERVER_PORT = _get("AIRUNNER_SERVER_PORT")
LOCAL_SERVER_HOST = _get("LOCAL_SERVER_HOST")

AIRUNNER_DEFAULT_LLM_HF_PATH = _get("AIRUNNER_DEFAULT_LLM_HF_PATH")
AIRUNNER_DEFAULT_STT_HF_PATH = _get("AIRUNNER_DEFAULT_STT_HF_PATH")
AIRUNNER_DEFAULT_STT_MODEL_FILENAME = _get(
    "AIRUNNER_DEFAULT_STT_MODEL_FILENAME"
)
AIRUNNER_DEFAULT_CHATBOT_SYSTEM_PROMPT = _get(
    "AIRUNNER_DEFAULT_CHATBOT_SYSTEM_PROMPT"
)
AIRUNNER_DEFAULT_CHATBOT_GUARDRAILS_PROMPT = _get(
    "AIRUNNER_DEFAULT_CHATBOT_GUARDRAILS_PROMPT"
)
AIRUNNER_DEFAULT_IMAGE_SYSTEM_PROMPT = _get(
    "AIRUNNER_DEFAULT_IMAGE_SYSTEM_PROMPT"
)
AIRUNNER_DEFAULT_IMAGE_LLM_GUARDRAILS = _get(
    "AIRUNNER_DEFAULT_IMAGE_LLM_GUARDRAILS"
)
AIRUNNER_DEFAULT_RAG_SEARCH_SYSTEM_PROMPT = _get(
    "AIRUNNER_DEFAULT_RAG_SEARCH_SYSTEM_PROMPT"
)
AIRUNNER_DEFAULT_APPLICATION_COMMAND_SYSTEM_PROMPT = _get(
    "AIRUNNER_DEFAULT_APPLICATION_COMMAND_SYSTEM_PROMPT"
)
AIRUNNER_DEFAULT_UPDATE_MOOD_SYSTEM_PROMPT = _get(
    "AIRUNNER_DEFAULT_UPDATE_MOOD_SYSTEM_PROMPT"
)
AIRUNNER_DEFAULT_SUMMARIZE_CHAT_SYSTEM_PROMPT = _get(
    "AIRUNNER_DEFAULT_SUMMARIZE_CHAT_SYSTEM_PROMPT"
)
AIRUNNER_DEFAULT_BRUSH_PRIMARY_COLOR = _get(
    "AIRUNNER_DEFAULT_BRUSH_PRIMARY_COLOR"
)
AIRUNNER_DEFAULT_BRUSH_SECONDARY_COLOR = _get(
    "AIRUNNER_DEFAULT_BRUSH_SECONDARY_COLOR"
)

AIRUNNER_LLM_ON = _get("AIRUNNER_LLM_ON")
AIRUNNER_TTS_ON = _get("AIRUNNER_TTS_ON")
AIRUNNER_STT_ON = _get("AIRUNNER_STT_ON")
AIRUNNER_SD_ON = _get("AIRUNNER_SD_ON")
AIRUNNER_CN_ON = _get("AIRUNNER_CN_ON")
AIRUNNER_ART_ENABLED = _get("AIRUNNER_ART_ENABLED")
AIRUNNER_TTS_MODEL_TYPE = _get("AIRUNNER_TTS_MODEL_TYPE")
AIRUNNER_ART_MODEL_PATH = _get("AIRUNNER_ART_MODEL_PATH")
AIRUNNER_ART_MODEL_VERSION = _get("AIRUNNER_ART_MODEL_VERSION")
AIRUNNER_ART_PIPELINE = _get("AIRUNNER_ART_PIPELINE")
AIRUNNER_ART_SCHEDULER = _get("AIRUNNER_ART_SCHEDULER")
AIRUNNER_ART_USE_COMPEL = _get("AIRUNNER_ART_USE_COMPEL")
AIRUNNER_DEFAULT_SCHEDULER = _get("AIRUNNER_DEFAULT_SCHEDULER")
AIRUNNER_SD_DEFAULT_VAE_PATH = _get("AIRUNNER_SD_DEFAULT_VAE_PATH")
AIRUNNER_MAX_SEED = _get("AIRUNNER_MAX_SEED")
AIRUNNER_SCRAPER_BLACKLIST = _get("AIRUNNER_SCRAPER_BLACKLIST", [])

AIRUNNER_LLM_AGENT_MAX_FUNCTION_CALLS = _get(
    "AIRUNNER_LLM_AGENT_MAX_FUNCTION_CALLS"
)
AIRUNNER_LLM_AGENT_UPDATE_MOOD_AFTER_N_TURNS = _get(
    "AIRUNNER_LLM_AGENT_UPDATE_MOOD_AFTER_N_TURNS"
)
AIRUNNER_LLM_AGENT_SUMMARIZE_AFTER_N_TURNS = _get(
    "AIRUNNER_LLM_AGENT_SUMMARIZE_AFTER_N_TURNS"
)
AIRUNNER_LLM_PERFORM_ANALYSIS = _get("AIRUNNER_LLM_PERFORM_ANALYSIS")
AIRUNNER_LLM_PERFORM_CONVERSATION_SUMMARY = _get(
    "AIRUNNER_LLM_PERFORM_CONVERSATION_SUMMARY"
)
AIRUNNER_LLM_PRINT_SYSTEM_PROMPT = _get("AIRUNNER_LLM_PRINT_SYSTEM_PROMPT")
AIRUNNER_LLM_OPENROUTER_MODEL = _get("AIRUNNER_LLM_OPENROUTER_MODEL")
AIRUNNER_LLM_USE_WEATHER_PROMPT = _get("AIRUNNER_LLM_USE_WEATHER_PROMPT")
AIRUNNER_LLM_UPDATE_USER_DATA_ENABLED = _get(
    "AIRUNNER_LLM_UPDATE_USER_DATA_ENABLED"
)
AIRUNNER_LLM_USE_CHATBOT_MOOD = _get("AIRUNNER_LLM_USE_CHATBOT_MOOD")
AIRUNNER_LLM_PERFORM_CONVERSATION_RAG = _get(
    "AIRUNNER_LLM_PERFORM_CONVERSATION_RAG"
)
AIRUNNER_LLM_DUPLICATE_TOOL_CALL_WINDOW = _get(
    "AIRUNNER_LLM_DUPLICATE_TOOL_CALL_WINDOW"
)
AIRUNNER_LLM_CHAT_STORE = _get("AIRUNNER_LLM_CHAT_STORE")

AIRUNNER_MEM_USE_LAST_CHANNELS = _get("AIRUNNER_MEM_USE_LAST_CHANNELS")
AIRUNNER_MEM_USE_ATTENTION_SLICING = _get("AIRUNNER_MEM_USE_ATTENTION_SLICING")
AIRUNNER_MEM_USE_ENABLE_VAE_SLICING = _get(
    "AIRUNNER_MEM_USE_ENABLE_VAE_SLICING"
)
AIRUNNER_MEM_USE_ACCELERATED_TRANSFORMERS = _get(
    "AIRUNNER_MEM_USE_ACCELERATED_TRANSFORMERS"
)
AIRUNNER_MEM_USE_TILED_VAE = _get("AIRUNNER_MEM_USE_TILED_VAE")
AIRUNNER_MEM_ENABLE_MODEL_CPU_OFFLOAD = _get(
    "AIRUNNER_MEM_ENABLE_MODEL_CPU_OFFLOAD"
)
AIRUNNER_MEM_USE_ENABLE_SEQUENTIAL_CPU_OFFLOAD = _get(
    "AIRUNNER_MEM_USE_ENABLE_SEQUENTIAL_CPU_OFFLOAD"
)
AIRUNNER_MEM_USE_TOME_SD = _get("AIRUNNER_MEM_USE_TOME_SD")
AIRUNNER_MEM_TOME_SD_RATIO = _get("AIRUNNER_MEM_TOME_SD_RATIO")
AIRUNNER_MEM_SD_DEVICE = _get("AIRUNNER_MEM_SD_DEVICE")
AIRUNNER_MEM_LLM_DEVICE = _get("AIRUNNER_MEM_LLM_DEVICE")
AIRUNNER_MEM_TTS_DEVICE = _get("AIRUNNER_MEM_TTS_DEVICE")
AIRUNNER_MEM_STT_DEVICE = _get("AIRUNNER_MEM_STT_DEVICE")
AIRUNNER_DISABLE_FLASH_ATTENTION = _get("AIRUNNER_DISABLE_FLASH_ATTENTION")

AIRUNNER_DISABLE_FACEHUGGERSHIELD = _get("AIRUNNER_DISABLE_FACEHUGGERSHIELD")
AIRUNNER_DISABLE_SETUP_WIZARD = _get("AIRUNNER_DISABLE_SETUP_WIZARD")
AIRUNNER_LOCAL_FILES_ONLY = _get("AIRUNNER_LOCAL_FILES_ONLY")
AIRUNNER_ADD_WATER_MARK = _get("AIRUNNER_ADD_WATER_MARK")
AIRUNNER_ORGANIZATION = _get("AIRUNNER_ORGANIZATION")
AIRUNNER_APPLICATION_NAME = _get("AIRUNNER_APPLICATION_NAME")
AIRUNNER_MOOD_PROMPT_OVERRIDE = _get("AIRUNNER_MOOD_PROMPT_OVERRIDE")
AIRUNNER_CUDA_OUT_OF_MEMORY_MESSAGE = _get(
    "AIRUNNER_CUDA_OUT_OF_MEMORY_MESSAGE"
)
AIRUNNER_SLEEP_TIME_IN_MS = _get("AIRUNNER_SLEEP_TIME_IN_MS")
AIRUNNER_MIN_NUM_INFERENCE_STEPS_IMG2IMG = _get(
    "AIRUNNER_MIN_NUM_INFERENCE_STEPS_IMG2IMG"
)

AIRUNNER_LOG_FILE = _get("AIRUNNER_LOG_FILE")
AIRUNNER_LOG_LEVEL = _get("AIRUNNER_LOG_LEVEL")

AIRUNNER_SAVE_LOG_TO_FILE = _get("AIRUNNER_SAVE_LOG_TO_FILE")

DEFAULT_HF_ENDPOINT = _get("DEFAULT_HF_ENDPOINT")

EXTENSIONS = _get("EXTENSIONS")
DATABASE_BACKEND = _get("DATABASE_BACKEND")


# ------------------------------------------------------------------
# Legacy functions
# ------------------------------------------------------------------
def get_log_level_from_env() -> int:
    """Resolve the configured Python logging level."""
    level_str = str(_get("AIRUNNER_LOG_LEVEL", "INFO")).upper()
    log_levels = {
        "CRITICAL": logging.CRITICAL,
        "ERROR": logging.ERROR,
        "WARNING": logging.WARNING,
        "INFO": logging.INFO,
        "DEBUG": logging.DEBUG,
        "NOTSET": logging.NOTSET,
    }
    return log_levels.get(level_str, logging.INFO)


__all__ = [
    "AIRUNNER_ADD_WATER_MARK",
    "AIRUNNER_APPLICATION_NAME",
    "AIRUNNER_ART_ENABLED",
    "AIRUNNER_ART_MODEL_PATH",
    "AIRUNNER_ART_MODEL_VERSION",
    "AIRUNNER_ART_PIPELINE",
    "AIRUNNER_ART_SCHEDULER",
    "AIRUNNER_ART_USE_COMPEL",
    "AIRUNNER_BASE_PATH",
    "AIRUNNER_CN_ON",
    "AIRUNNER_CUDA_OUT_OF_MEMORY_MESSAGE",
    "AIRUNNER_DB_URL",
    "AIRUNNER_DEFAULT_APPLICATION_COMMAND_SYSTEM_PROMPT",
    "AIRUNNER_DEFAULT_BRUSH_PRIMARY_COLOR",
    "AIRUNNER_DEFAULT_BRUSH_SECONDARY_COLOR",
    "AIRUNNER_DEFAULT_CHATBOT_GUARDRAILS_PROMPT",
    "AIRUNNER_DEFAULT_CHATBOT_SYSTEM_PROMPT",
    "AIRUNNER_DEFAULT_IMAGE_LLM_GUARDRAILS",
    "AIRUNNER_DEFAULT_IMAGE_SYSTEM_PROMPT",
    "AIRUNNER_DEFAULT_LLM_HF_PATH",
    "AIRUNNER_DEFAULT_RAG_SEARCH_SYSTEM_PROMPT",
    "AIRUNNER_DEFAULT_SCHEDULER",
    "AIRUNNER_DEFAULT_STT_HF_PATH",
    "AIRUNNER_DEFAULT_STT_MODEL_FILENAME",
    "AIRUNNER_DEFAULT_SUMMARIZE_CHAT_SYSTEM_PROMPT",
    "AIRUNNER_DEFAULT_UPDATE_MOOD_SYSTEM_PROMPT",
    "AIRUNNER_DISABLE_FACEHUGGERSHIELD",
    "AIRUNNER_DISABLE_FLASH_ATTENTION",
    "AIRUNNER_DISABLE_SETUP_WIZARD",
    "AIRUNNER_LLM_AGENT_MAX_FUNCTION_CALLS",
    "AIRUNNER_LLM_AGENT_SUMMARIZE_AFTER_N_TURNS",
    "AIRUNNER_LLM_AGENT_UPDATE_MOOD_AFTER_N_TURNS",
    "AIRUNNER_LLM_CHAT_STORE",
    "AIRUNNER_LLM_DUPLICATE_TOOL_CALL_WINDOW",
    "AIRUNNER_LLM_ON",
    "AIRUNNER_LLM_OPENROUTER_MODEL",
    "AIRUNNER_LLM_PERFORM_ANALYSIS",
    "AIRUNNER_LLM_PERFORM_CONVERSATION_RAG",
    "AIRUNNER_LLM_PERFORM_CONVERSATION_SUMMARY",
    "AIRUNNER_LLM_PRINT_SYSTEM_PROMPT",
    "AIRUNNER_LLM_UPDATE_USER_DATA_ENABLED",
    "AIRUNNER_LLM_USE_CHATBOT_MOOD",
    "AIRUNNER_LLM_USE_WEATHER_PROMPT",
    "AIRUNNER_LOCAL_FILES_ONLY",
    "AIRUNNER_LOG_FILE",
    "AIRUNNER_LOG_LEVEL",
    "AIRUNNER_MAX_SEED",
    "AIRUNNER_MEM_ENABLE_MODEL_CPU_OFFLOAD",
    "AIRUNNER_MEM_LLM_DEVICE",
    "AIRUNNER_MEM_SD_DEVICE",
    "AIRUNNER_MEM_STT_DEVICE",
    "AIRUNNER_MEM_TOME_SD_RATIO",
    "AIRUNNER_MEM_TTS_DEVICE",
    "AIRUNNER_MEM_USE_ACCELERATED_TRANSFORMERS",
    "AIRUNNER_MEM_USE_ATTENTION_SLICING",
    "AIRUNNER_MEM_USE_ENABLE_SEQUENTIAL_CPU_OFFLOAD",
    "AIRUNNER_MEM_USE_ENABLE_VAE_SLICING",
    "AIRUNNER_MEM_USE_LAST_CHANNELS",
    "AIRUNNER_MEM_USE_TILED_VAE",
    "AIRUNNER_MEM_USE_TOME_SD",
    "AIRUNNER_MIN_NUM_INFERENCE_STEPS_IMG2IMG",
    "AIRUNNER_MOOD_PROMPT_OVERRIDE",
    "AIRUNNER_ORGANIZATION",
    "AIRUNNER_SAVE_LOG_TO_FILE",
    "AIRUNNER_SCRAPER_BLACKLIST",
    "AIRUNNER_SD_DEFAULT_VAE_PATH",
    "AIRUNNER_SD_ON",
    "AIRUNNER_SERVER_HOST",
    "AIRUNNER_SERVER_PORT",
    "AIRUNNER_SLEEP_TIME_IN_MS",
    "AIRUNNER_STT_ON",
    "AIRUNNER_TTS_MODEL_TYPE",
    "AIRUNNER_TTS_ON",
    "AIRUNNER_USER_DATA_PATH",
    "AIRUNNER_VERSION",
    "DATABASE_BACKEND",
    "DEFAULT_HF_ENDPOINT",
    "DEV_ENV",
    "EXTENSIONS",
    "LOCAL_SERVER_HOST",
    "MODELS_DIR",
    "get_log_level_from_env",
]
