# Form implementation generated from reading ui file '/home/joe/Projects/imagetopixel/airunner/src/airunner/../../src/airunner/widgets/tts/templates/tts_preferences.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_tts_preferences(object):
    def setupUi(self, tts_preferences):
        tts_preferences.setObjectName("tts_preferences")
        tts_preferences.resize(512, 787)
        self.gridLayout = QtWidgets.QGridLayout(tts_preferences)
        self.gridLayout.setObjectName("gridLayout")
        self.enable_tts = QtWidgets.QCheckBox(parent=tts_preferences)
        self.enable_tts.setObjectName("enable_tts")
        self.gridLayout.addWidget(self.enable_tts, 0, 0, 1, 1)
        self.line = QtWidgets.QFrame(parent=tts_preferences)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(parent=tts_preferences)
        self.groupBox_7.setObjectName("groupBox_7")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_7)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.model_combobox = QtWidgets.QComboBox(parent=self.groupBox_7)
        self.model_combobox.setObjectName("model_combobox")
        self.gridLayout_9.addWidget(self.model_combobox, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_7, 2, 0, 1, 1)
        self.bark_preferences = BarkPreferencesWidget(parent=tts_preferences)
        self.bark_preferences.setObjectName("bark_preferences")
        self.gridLayout.addWidget(self.bark_preferences, 3, 0, 1, 1)
        self.espeak_preferences = ESpeakPreferencesWidget(parent=tts_preferences)
        self.espeak_preferences.setObjectName("espeak_preferences")
        self.gridLayout.addWidget(self.espeak_preferences, 4, 0, 1, 1)
        self.speecht5_preferences = SpeechT5PreferencesWidget(parent=tts_preferences)
        self.speecht5_preferences.setObjectName("speecht5_preferences")
        self.gridLayout.addWidget(self.speecht5_preferences, 5, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 6, 0, 1, 1)

        self.retranslateUi(tts_preferences)
        self.enable_tts.toggled['bool'].connect(tts_preferences.enable_tts_changed) # type: ignore
        self.model_combobox.currentTextChanged['QString'].connect(tts_preferences.model_changed) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(tts_preferences)

    def retranslateUi(self, tts_preferences):
        _translate = QtCore.QCoreApplication.translate
        tts_preferences.setWindowTitle(_translate("tts_preferences", "Form"))
        self.enable_tts.setText(_translate("tts_preferences", "Enable Text to Speech"))
        self.groupBox_7.setTitle(_translate("tts_preferences", "Model"))
from airunner.widgets.tts.bark_preferences_widget import BarkPreferencesWidget
from airunner.widgets.tts.espeak_preferences_widget import ESpeakPreferencesWidget
from airunner.widgets.tts.speecht5_preferences_widget import SpeechT5PreferencesWidget
