# Form implementation generated from reading ui file '/home/joe/Projects/imagetopixel/airunner/src/airunner/../../src/airunner/widgets/tts/templates/tts_preferences.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_tts_preferences(object):
    def setupUi(self, tts_preferences):
        tts_preferences.setObjectName("tts_preferences")
        tts_preferences.resize(400, 301)
        self.gridLayout_2 = QtWidgets.QGridLayout(tts_preferences)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.use_bark = QtWidgets.QCheckBox(parent=tts_preferences)
        self.use_bark.setObjectName("use_bark")
        self.gridLayout_2.addWidget(self.use_bark, 3, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(parent=tts_preferences)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.language_combobox = QtWidgets.QComboBox(parent=self.groupBox_3)
        self.language_combobox.setObjectName("language_combobox")
        self.gridLayout_4.addWidget(self.language_combobox, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=tts_preferences)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gender_combobox = QtWidgets.QComboBox(parent=self.groupBox_2)
        self.gender_combobox.setObjectName("gender_combobox")
        self.gender_combobox.addItem("")
        self.gender_combobox.addItem("")
        self.gridLayout_3.addWidget(self.gender_combobox, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(parent=tts_preferences)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.voice_combobox = QtWidgets.QComboBox(parent=self.groupBox)
        self.voice_combobox.setObjectName("voice_combobox")
        self.gridLayout.addWidget(self.voice_combobox, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 5, 0, 1, 1)
        self.enable_tts = QtWidgets.QCheckBox(parent=tts_preferences)
        self.enable_tts.setObjectName("enable_tts")
        self.gridLayout_2.addWidget(self.enable_tts, 4, 0, 1, 1)

        self.retranslateUi(tts_preferences)
        self.language_combobox.currentTextChanged['QString'].connect(tts_preferences.language_changed) # type: ignore
        self.voice_combobox.currentTextChanged['QString'].connect(tts_preferences.voice_changed) # type: ignore
        self.gender_combobox.currentTextChanged['QString'].connect(tts_preferences.gender_changed) # type: ignore
        self.use_bark.toggled['bool'].connect(tts_preferences.use_bark_changed) # type: ignore
        self.enable_tts.toggled['bool'].connect(tts_preferences.enable_tts_changed) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(tts_preferences)

    def retranslateUi(self, tts_preferences):
        _translate = QtCore.QCoreApplication.translate
        tts_preferences.setWindowTitle(_translate("tts_preferences", "Form"))
        self.use_bark.setText(_translate("tts_preferences", "Use Bark"))
        self.groupBox_3.setTitle(_translate("tts_preferences", "Language"))
        self.groupBox_2.setTitle(_translate("tts_preferences", "Gender"))
        self.gender_combobox.setItemText(0, _translate("tts_preferences", "Male"))
        self.gender_combobox.setItemText(1, _translate("tts_preferences", "Female"))
        self.groupBox.setTitle(_translate("tts_preferences", "Voice"))
        self.enable_tts.setText(_translate("tts_preferences", "Enable Text to Speech"))
