# Form implementation generated from reading ui file '/home/joe/Projects/imagetopixel/airunner/src/airunner/../../src/airunner/widgets/generator_form/templates/generator_tab.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_generator_tab(object):
    def setupUi(self, generator_tab):
        generator_tab.setObjectName("generator_tab")
        generator_tab.resize(576, 1284)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(generator_tab.sizePolicy().hasHeightForWidth())
        generator_tab.setSizePolicy(sizePolicy)
        self.gridLayout_2 = QtWidgets.QGridLayout(generator_tab)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.generator_tabs = QtWidgets.QTabWidget(parent=generator_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generator_tabs.sizePolicy().hasHeightForWidth())
        self.generator_tabs.setSizePolicy(sizePolicy)
        self.generator_tabs.setObjectName("generator_tabs")
        self.tab_stablediffusion = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_stablediffusion.sizePolicy().hasHeightForWidth())
        self.tab_stablediffusion.setSizePolicy(sizePolicy)
        self.tab_stablediffusion.setObjectName("tab_stablediffusion")
        self.gridLayout = QtWidgets.QGridLayout(self.tab_stablediffusion)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.generator_form_stablediffusion = GeneratorForm(parent=self.tab_stablediffusion)
        self.generator_form_stablediffusion.setObjectName("generator_form_stablediffusion")
        self.gridLayout.addWidget(self.generator_form_stablediffusion, 0, 0, 1, 1)
        self.generator_tabs.addTab(self.tab_stablediffusion, "")
        self.gridLayout_2.addWidget(self.generator_tabs, 0, 0, 1, 1)

        self.retranslateUi(generator_tab)
        self.generator_tabs.setCurrentIndex(0)
        self.generator_tabs.currentChanged['int'].connect(generator_tab.handle_generator_tab_changed) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(generator_tab)

    def retranslateUi(self, generator_tab):
        _translate = QtCore.QCoreApplication.translate
        generator_tab.setWindowTitle(_translate("generator_tab", "Form"))
        self.generator_form_stablediffusion.setProperty("generator_section", _translate("generator_tab", "txt2img"))
        self.generator_form_stablediffusion.setProperty("generator_name", _translate("generator_tab", "stablediffusion"))
        self.generator_tabs.setTabText(self.generator_tabs.indexOf(self.tab_stablediffusion), _translate("generator_tab", "Stable Diffusion"))
from airunner.widgets.generator_form.generator_form_widget import GeneratorForm
