services:
  airunner_build_runtime:
    container_name: airunner_build_runtime
    image: ghcr.io/capsize-games/airunner/airunner:linux_build_runtime
    build:
      context: ../..
      dockerfile: package/prod/Dockerfile.linux_build_runtime
      args:
        - INSTALL_XCB_CURSOR=1
    user: "${HOST_UID}:${HOST_GID}"
    stdin_open: true
    tty: true
    entrypoint: ["/home/appuser/entrypoint.sh"]
    working_dir: /app
    runtime: nvidia
    ports:
      - "8000:8000"
    ipc: host
    network_mode: "host"
    environment:
      - DEV_ENV=${DEV_ENV}
      - QT_QPA_PLATFORM=wayland
      - QT_WAYLAND_DISABLE_WINDOWDECORATION=1
      - QT_QPA_PLATFORMTHEME=gtk3
      - GDK_BACKEND=wayland
      - XDG_SESSION_TYPE=wayland
      - XDG_RUNTIME_DIR=/tmp
    volumes:
      - ${HOST_HOME}/.local/share/airunner:/home/appuser/.local/share/airunner
      - ${HOST_HOME}/.config/airunner:/home/appuser/.config/airunner
      - ${XDG_RUNTIME_DIR}:/tmp