# Form implementation generated from reading ui file '/home/joe/Projects/imagetopixel/airunner/src/airunner/windows/deterministic_generation/templates/deterministic_generation_window.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_deterministic_generation_window(object):
    def setupUi(self, deterministic_generation_window):
        deterministic_generation_window.setObjectName("deterministic_generation_window")
        deterministic_generation_window.resize(436, 490)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(deterministic_generation_window.sizePolicy().hasHeightForWidth())
        deterministic_generation_window.setSizePolicy(sizePolicy)
        deterministic_generation_window.setMinimumSize(QtCore.QSize(436, 490))
        deterministic_generation_window.setMaximumSize(QtCore.QSize(436, 490))
        self.layoutWidget = QtWidgets.QWidget(parent=deterministic_generation_window)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 414, 474))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")

        self.retranslateUi(deterministic_generation_window)
        QtCore.QMetaObject.connectSlotsByName(deterministic_generation_window)

    def retranslateUi(self, deterministic_generation_window):
        _translate = QtCore.QCoreApplication.translate
        deterministic_generation_window.setWindowTitle(_translate("deterministic_generation_window", "Batch Generation"))
