FROM capsize-games/airunner/airunner:dev_latest
WORKDIR /app
ENV DEV_ENV=${DEV_ENV:-1}
ENV AIRUNNER_ENVIRONMENT="prod"
ENV PYTHONOPTIMIZE=0

# Install Python packages at build time
USER root
RUN pip3.13 install --no-cache-dir pip setuptools wheel --upgrade && \
    pip3.13 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128 && \
    cd /app && pip3.13 install --no-cache-dir -e .[all_dev] -U langchain-community && \
    pip3.13 install -U timm && \
    rm -rf /tmp/* /var/tmp/* /root/.cache/pip

# Switch back to non-root user
USER appuser