services:
  linux_dev_package:
    container_name: linux_dev_package
    image: capsize-games/airunner/airunner:linux_dev_package
    build:
      context: ../..
      dockerfile: package/dev/Dockerfile.linux_dev_package
      args:
        - INSTALL_XCB_CURSOR=1
    user: "${HOST_UID}:${HOST_GID}"
    stdin_open: true
    tty: true
    working_dir: /app
    runtime: nvidia
    ports:
      - "8000:8000"
    ipc: host
    network_mode: "host"
    environment:
      - DEV_ENV=1
      - BNB_CUDA_VERSION=124
      - HOST_UID=${HOST_UID}
      - HOST_GID=${HOST_GID}
    entrypoint: ["/home/appuser/entrypoint.sh"]
    volumes:
      - ../../:/app:rw,z
      - ../package/asound.conf:/etc/asound.conf:rw
      - "${AIRUNNER_HOME_DIR:-~/.local/share/airunner}:/home/appuser/.local/share/airunner:rw,z"
      - "${AIRUNNER_HOME_DIR:-~/.local/share/airunner}/python:/home/appuser/.local/share/airunner/python:rw,z"
      - "${AIRUNNER_HOME_DIR:-~/.local/share/airunner}/lib:/home/appuser/.local/share/airunner/lib:rw,z"
      - "${AIRUNNER_HOME_DIR:-~/.local/share/airunner}/bin:/home/appuser/.local/share/airunner/bin:rw,z"
      - "${AIRUNNER_HOME_DIR:-~/.local/share/airunner}/lib/python3.10:/home/appuser/.local/lib/python3.10:rw,z"
      - "${AIRUNNER_HOME_DIR:-~/.local/share/airunner}/lib/python3.10/site-packages:/home/appuser/.local/lib/python3.10/site-packages:rw,z"
      - "${AIRUNNER_HOME_DIR:-~/.local/share/airunner}/data:/home/appuser/.local/share/airunner/data:rw,z"
      - "${HOST_HOME}/.cache/huggingface:/home/appuser/.cache/huggingface:rw,z"
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /run/user/${HOST_UID}/pulse:/run/user/1000/pulse:ro
      - ${XAUTHORITY}:${XAUTHORITY}:rw,z
      - ${AIRUNNER_HOME_DIR:-~/.local/share/airunner}/torch/hub:/home/appuser/.cache/torch/hub:rw,z
      - ${AIRUNNER_HOME_DIR:-~/.local/share/airunner}/python:/home/appuser/.local:rw,z
