"""add n_ctx and enable_tools to llm generator settings

Revision ID: 970363fddcd6
Revises: 9e321c582dbe
Create Date: 2026-03-22 09:08:31.060827

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "970363fddcd6"
down_revision: Union[str, None] = "9e321c582dbe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "llm_generator_settings",
        sa.Column("n_ctx", sa.Integer(), nullable=True),
    )
    op.add_column(
        "llm_generator_settings",
        sa.Column("enable_tools", sa.Boolean(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("llm_generator_settings", "enable_tools")
    op.drop_column("llm_generator_settings", "n_ctx")
    # ### end Alembic commands ###
