# Form implementation generated from reading ui file '/home/joe/Projects/imagetopixel/airunner/src/airunner/../../src/airunner/widgets/llm/templates/bot_preferences.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_bot_preferences(object):
    def setupUi(self, bot_preferences):
        bot_preferences.setObjectName("bot_preferences")
        bot_preferences.resize(701, 721)
        self.gridLayout = QtWidgets.QGridLayout(bot_preferences)
        self.gridLayout.setObjectName("gridLayout")
        self.mood_groupbox = QtWidgets.QGroupBox(parent=bot_preferences)
        self.mood_groupbox.setCheckable(True)
        self.mood_groupbox.setObjectName("mood_groupbox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.mood_groupbox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.bot_mood = QtWidgets.QPlainTextEdit(parent=self.mood_groupbox)
        self.bot_mood.setObjectName("bot_mood")
        self.gridLayout_2.addWidget(self.bot_mood, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.mood_groupbox, 4, 0, 1, 1)
        self.guardrails_groupbox = QtWidgets.QGroupBox(parent=bot_preferences)
        self.guardrails_groupbox.setCheckable(True)
        self.guardrails_groupbox.setObjectName("guardrails_groupbox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.guardrails_groupbox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.guardrails_prompt = QtWidgets.QPlainTextEdit(parent=self.guardrails_groupbox)
        self.guardrails_prompt.setObjectName("guardrails_prompt")
        self.verticalLayout_2.addWidget(self.guardrails_prompt)
        self.gridLayout.addWidget(self.guardrails_groupbox, 6, 0, 1, 1)
        self.names_groupbox = QtWidgets.QGroupBox(parent=bot_preferences)
        self.names_groupbox.setCheckable(True)
        self.names_groupbox.setObjectName("names_groupbox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.names_groupbox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(parent=self.names_groupbox)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.username = QtWidgets.QLineEdit(parent=self.names_groupbox)
        self.username.setObjectName("username")
        self.verticalLayout_5.addWidget(self.username)
        self.verticalLayout.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label = QtWidgets.QLabel(parent=self.names_groupbox)
        self.label.setObjectName("label")
        self.verticalLayout_6.addWidget(self.label)
        self.botname = QtWidgets.QLineEdit(parent=self.names_groupbox)
        self.botname.setCursorPosition(6)
        self.botname.setObjectName("botname")
        self.verticalLayout_6.addWidget(self.botname)
        self.verticalLayout.addLayout(self.verticalLayout_6)
        self.gridLayout.addWidget(self.names_groupbox, 2, 0, 1, 1)
        self.personality_groupbox = QtWidgets.QGroupBox(parent=bot_preferences)
        self.personality_groupbox.setCheckable(True)
        self.personality_groupbox.setObjectName("personality_groupbox")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.personality_groupbox)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.bot_personality = QtWidgets.QPlainTextEdit(parent=self.personality_groupbox)
        self.bot_personality.setObjectName("bot_personality")
        self.gridLayout_5.addWidget(self.bot_personality, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.personality_groupbox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.personality_groupbox, 3, 0, 1, 1)
        self.system_instructions_groupbox = QtWidgets.QGroupBox(parent=bot_preferences)
        self.system_instructions_groupbox.setCheckable(True)
        self.system_instructions_groupbox.setObjectName("system_instructions_groupbox")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.system_instructions_groupbox)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.system_instructions = QtWidgets.QPlainTextEdit(parent=self.system_instructions_groupbox)
        self.system_instructions.setObjectName("system_instructions")
        self.verticalLayout_3.addWidget(self.system_instructions)
        self.gridLayout.addWidget(self.system_instructions_groupbox, 5, 0, 1, 1)

        self.retranslateUi(bot_preferences)
        self.username.textChanged['QString'].connect(bot_preferences.username_changed) # type: ignore
        self.botname.textChanged['QString'].connect(bot_preferences.botname_changed) # type: ignore
        self.bot_personality.textChanged.connect(bot_preferences.bot_personality_changed) # type: ignore
        self.bot_mood.textChanged.connect(bot_preferences.bot_mood_changed) # type: ignore
        self.names_groupbox.toggled['bool'].connect(bot_preferences.toggle_use_names) # type: ignore
        self.personality_groupbox.toggled['bool'].connect(bot_preferences.toggle_use_personality) # type: ignore
        self.guardrails_prompt.textChanged.connect(bot_preferences.guardrails_prompt_changed) # type: ignore
        self.system_instructions.textChanged.connect(bot_preferences.system_instructions_changed) # type: ignore
        self.mood_groupbox.toggled['bool'].connect(bot_preferences.toggle_use_mood) # type: ignore
        self.guardrails_groupbox.toggled['bool'].connect(bot_preferences.toggle_use_guardrails) # type: ignore
        self.system_instructions_groupbox.toggled['bool'].connect(bot_preferences.toggle_use_system_instructions) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(bot_preferences)

    def retranslateUi(self, bot_preferences):
        _translate = QtCore.QCoreApplication.translate
        bot_preferences.setWindowTitle(_translate("bot_preferences", "Form"))
        self.mood_groupbox.setTitle(_translate("bot_preferences", "Bot Mood"))
        self.bot_mood.setPlaceholderText(_translate("bot_preferences", "EXAMPLE: Excited"))
        self.guardrails_groupbox.setTitle(_translate("bot_preferences", "Guardrails"))
        self.guardrails_prompt.setPlaceholderText(_translate("bot_preferences", "The guardrails prompt is used to moderate results."))
        self.names_groupbox.setTitle(_translate("bot_preferences", "Use names"))
        self.label_3.setText(_translate("bot_preferences", "User name"))
        self.username.setText(_translate("bot_preferences", "User"))
        self.username.setPlaceholderText(_translate("bot_preferences", "User name"))
        self.label.setText(_translate("bot_preferences", "Bot name"))
        self.botname.setText(_translate("bot_preferences", "ChatAI"))
        self.botname.setPlaceholderText(_translate("bot_preferences", "Bot name"))
        self.personality_groupbox.setTitle(_translate("bot_preferences", "Bot Personality"))
        self.bot_personality.setPlaceholderText(_translate("bot_preferences", "EXAMPLE: {{ botname }} is very helpful and {{ gender }} loves {{ username }}."))
        self.label_2.setText(_translate("bot_preferences", "A brief description of the bot\'s personality"))
        self.system_instructions_groupbox.setTitle(_translate("bot_preferences", "System Instructions"))
        self.system_instructions.setPlaceholderText(_translate("bot_preferences", "Instructions for the LLM"))
