# Form implementation generated from reading ui file '/home/joe/Projects/imagetopixel/airunner/src/airunner/../../src/airunner/widgets/llm/templates/chat_prompt.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_chat_prompt(object):
    def setupUi(self, chat_prompt):
        chat_prompt.setObjectName("chat_prompt")
        chat_prompt.resize(734, 1077)
        self.gridLayout = QtWidgets.QGridLayout(chat_prompt)
        self.gridLayout.setObjectName("gridLayout")
        self.conversation = QtWidgets.QTextEdit(parent=chat_prompt)
        self.conversation.setReadOnly(True)
        self.conversation.setObjectName("conversation")
        self.gridLayout.addWidget(self.conversation, 0, 0, 1, 1)
        self.chat_container = QtWidgets.QScrollArea(parent=chat_prompt)
        self.chat_container.setWidgetResizable(True)
        self.chat_container.setObjectName("chat_container")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 714, 492))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.chat_container.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.chat_container, 1, 0, 1, 1)
        self.widget_5 = QtWidgets.QWidget(parent=chat_prompt)
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.prompt = QtWidgets.QLineEdit(parent=self.widget_5)
        self.prompt.setObjectName("prompt")
        self.horizontalLayout.addWidget(self.prompt)
        self.comboBox = QtWidgets.QComboBox(parent=self.widget_5)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout.addWidget(self.comboBox)
        self.gridLayout.addWidget(self.widget_5, 2, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.send_button = QtWidgets.QPushButton(parent=chat_prompt)
        self.send_button.setObjectName("send_button")
        self.horizontalLayout_2.addWidget(self.send_button)
        self.progressBar = QtWidgets.QProgressBar(parent=chat_prompt)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_2.addWidget(self.progressBar)
        self.clear_conversatiion_button = QtWidgets.QPushButton(parent=chat_prompt)
        self.clear_conversatiion_button.setObjectName("clear_conversatiion_button")
        self.horizontalLayout_2.addWidget(self.clear_conversatiion_button)
        self.gridLayout.addLayout(self.horizontalLayout_2, 3, 0, 1, 1)

        self.retranslateUi(chat_prompt)
        self.send_button.clicked.connect(chat_prompt.action_button_clicked_send) # type: ignore
        self.clear_conversatiion_button.clicked.connect(chat_prompt.action_button_clicked_clear_conversation) # type: ignore
        self.comboBox.currentTextChanged['QString'].connect(chat_prompt.message_type_text_changed) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(chat_prompt)

    def retranslateUi(self, chat_prompt):
        _translate = QtCore.QCoreApplication.translate
        chat_prompt.setWindowTitle(_translate("chat_prompt", "Form"))
        self.prompt.setPlaceholderText(_translate("chat_prompt", "Chat input"))
        self.comboBox.setItemText(0, _translate("chat_prompt", "Chat"))
        self.comboBox.setItemText(1, _translate("chat_prompt", "Narrate"))
        self.comboBox.setItemText(2, _translate("chat_prompt", "Generate Image"))
        self.comboBox.setItemText(3, _translate("chat_prompt", "Summarize"))
        self.comboBox.setItemText(4, _translate("chat_prompt", "Translate"))
        self.send_button.setText(_translate("chat_prompt", "Send"))
        self.clear_conversatiion_button.setText(_translate("chat_prompt", "New Conversation"))
