# Form implementation generated from reading ui file '/home/joe/Projects/imagetopixel/airunner/src/airunner/../../src/airunner/widgets/llm/templates/llm_preferences.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_llm_preferences_widget(object):
    def setupUi(self, llm_preferences_widget):
        llm_preferences_widget.setObjectName("llm_preferences_widget")
        llm_preferences_widget.resize(1371, 957)
        self.gridLayout = QtWidgets.QGridLayout(llm_preferences_widget)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(parent=llm_preferences_widget)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.splitter.setObjectName("splitter")
        self.groupBox = QtWidgets.QGroupBox(parent=self.splitter)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.prefix = QtWidgets.QPlainTextEdit(parent=self.groupBox)
        self.prefix.setObjectName("prefix")
        self.gridLayout_3.addWidget(self.prefix, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.splitter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.suffix = QtWidgets.QPlainTextEdit(parent=self.groupBox_2)
        self.suffix.setObjectName("suffix")
        self.gridLayout_4.addWidget(self.suffix, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(parent=llm_preferences_widget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.botname = QtWidgets.QLineEdit(parent=self.groupBox_3)
        self.botname.setCursorPosition(6)
        self.botname.setObjectName("botname")
        self.verticalLayout_2.addWidget(self.botname)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.personality_type = QtWidgets.QComboBox(parent=self.groupBox_3)
        self.personality_type.setObjectName("personality_type")
        self.personality_type.addItem("")
        self.personality_type.addItem("")
        self.personality_type.addItem("")
        self.personality_type.addItem("")
        self.personality_type.addItem("")
        self.verticalLayout_3.addWidget(self.personality_type)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.gridLayout.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(parent=llm_preferences_widget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.username = QtWidgets.QLineEdit(parent=self.groupBox_4)
        self.username.setObjectName("username")
        self.gridLayout_13.addWidget(self.username, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_4, 2, 0, 1, 1)
        self.generate_characters_button = QtWidgets.QPushButton(parent=llm_preferences_widget)
        self.generate_characters_button.setObjectName("generate_characters_button")
        self.gridLayout.addWidget(self.generate_characters_button, 3, 0, 1, 1)

        self.retranslateUi(llm_preferences_widget)
        self.generate_characters_button.clicked.connect(llm_preferences_widget.action_button_clicked_generate_characters) # type: ignore
        self.username.textEdited['QString'].connect(llm_preferences_widget.username_text_changed) # type: ignore
        self.botname.textEdited['QString'].connect(llm_preferences_widget.botname_text_changed) # type: ignore
        self.personality_type.textHighlighted['QString'].connect(llm_preferences_widget.personality_type_changed) # type: ignore
        self.suffix.textChanged.connect(llm_preferences_widget.suffix_text_changed) # type: ignore
        self.prefix.textChanged.connect(llm_preferences_widget.prefix_text_changed) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(llm_preferences_widget)
        llm_preferences_widget.setTabOrder(self.prefix, self.suffix)
        llm_preferences_widget.setTabOrder(self.suffix, self.botname)
        llm_preferences_widget.setTabOrder(self.botname, self.username)

    def retranslateUi(self, llm_preferences_widget):
        _translate = QtCore.QCoreApplication.translate
        llm_preferences_widget.setWindowTitle(_translate("llm_preferences_widget", "Form"))
        self.groupBox.setTitle(_translate("llm_preferences_widget", "Prefix"))
        self.groupBox_2.setTitle(_translate("llm_preferences_widget", "Suffix"))
        self.groupBox_3.setTitle(_translate("llm_preferences_widget", "Bot details"))
        self.label.setText(_translate("llm_preferences_widget", "Name"))
        self.botname.setText(_translate("llm_preferences_widget", "ChatAI"))
        self.label_2.setText(_translate("llm_preferences_widget", "Personality"))
        self.personality_type.setItemText(0, _translate("llm_preferences_widget", "Nice"))
        self.personality_type.setItemText(1, _translate("llm_preferences_widget", "Mean"))
        self.personality_type.setItemText(2, _translate("llm_preferences_widget", "Weird"))
        self.personality_type.setItemText(3, _translate("llm_preferences_widget", "Insane"))
        self.personality_type.setItemText(4, _translate("llm_preferences_widget", "Random"))
        self.groupBox_4.setTitle(_translate("llm_preferences_widget", "User name"))
        self.username.setText(_translate("llm_preferences_widget", "User"))
        self.generate_characters_button.setText(_translate("llm_preferences_widget", "Generate Characters"))
