# Form implementation generated from reading ui file '/home/joe/Projects/imagetopixel/airunner/src/airunner/../../src/airunner/widgets/llm/templates/loading.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_loading_message(object):
    def setupUi(self, loading_message):
        loading_message.setObjectName("loading_message")
        loading_message.resize(605, 707)
        self.gridLayout = QtWidgets.QGridLayout(loading_message)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(parent=loading_message)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.retranslateUi(loading_message)
        QtCore.QMetaObject.connectSlotsByName(loading_message)

    def retranslateUi(self, loading_message):
        _translate = QtCore.QCoreApplication.translate
        loading_message.setWindowTitle(_translate("loading_message", "Form"))
