# Form implementation generated from reading ui file '/home/joe/Projects/imagetopixel/airunner/src/airunner/widgets/llm/templates/prompt_template_editor.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(364, 447)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(parent=Form)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.system_instructions = QtWidgets.QPlainTextEdit(parent=self.groupBox_3)
        self.system_instructions.setObjectName("system_instructions")
        self.gridLayout_4.addWidget(self.system_instructions, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.groupBox_3)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_3, 2, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(parent=Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.llm_category = QtWidgets.QComboBox(parent=self.groupBox)
        self.llm_category.setObjectName("llm_category")
        self.gridLayout_2.addWidget(self.llm_category, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.template_name = QtWidgets.QComboBox(parent=Form)
        self.template_name.setObjectName("template_name")
        self.horizontalLayout.addWidget(self.template_name)
        self.pushButton_2 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.template_format = QtWidgets.QComboBox(parent=self.groupBox_2)
        self.template_format.setObjectName("template_format")
        self.gridLayout_3.addWidget(self.template_format, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 1)

        self.retranslateUi(Form)
        self.llm_category.currentTextChanged['QString'].connect(Form.llm_category_changed) # type: ignore
        self.template_format.currentTextChanged['QString'].connect(Form.model_changed) # type: ignore
        self.system_instructions.textChanged.connect(Form.system_instructions_changed) # type: ignore
        self.template_name.currentTextChanged['QString'].connect(Form.template_name_changed) # type: ignore
        self.pushButton_2.clicked.connect(Form.save_clicked) # type: ignore
        self.pushButton_3.clicked.connect(Form.delete_clicked) # type: ignore
        self.pushButton.clicked.connect(Form.new_clicked) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_3.setTitle(_translate("Form", "System Instructions"))
        self.system_instructions.setPlaceholderText(_translate("Form", "EXAMPLE: You are {{ botname }}. You are having a conversation with {{ username }}. {{ username }} is the user and you are the assistant. You should stay in character and respond as {{ botname }}."))
        self.label.setText(_translate("Form", "Keep the instructions brief, but be descriptive."))
        self.groupBox.setTitle(_translate("Form", "LLM Category"))
        self.pushButton_2.setText(_translate("Form", "Save"))
        self.pushButton_3.setText(_translate("Form", "Delete"))
        self.pushButton.setText(_translate("Form", "New"))
        self.groupBox_2.setTitle(_translate("Form", "Model"))
