FROM ubuntu:22.04 AS base_image
ENV DEBIAN_FRONTEND=noninteractive
ENV DEBCONF_NOWARNINGS="yes"
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
 python3.10 \
 python3.10-venv \
 python3-pip \
 python3.10-distutils \
 build-essential \
 git \
 wget \
 libffi-dev \
 libssl-dev \
 libgl1-mesa-dev \
 libjpeg-dev \
 zlib1g-dev \
 libpng-dev \
 cmake \
 ninja-build \
 nvidia-cuda-toolkit \
 xclip \
 xserver-xorg \
 xvfb \
 # Qt6 dependencies for XCB
 libxcb-cursor0 \
 libxcb-xinput0 \
 libxcb-xfixes0 \
 libxcomposite1 \
 libxcb-icccm4 \
 libxcb-image0 \
 libxcb-keysyms1 \
 libxcb-randr0 \
 libxcb-render-util0 \
 libxcb-xinerama0 \
 libxcb-xkb1 \
 libxcb-glx0 \
 libxcb-shape0 \
 libxcb-shm0 \
 libxcb-sync1 \
 libxcb-dri2-0 \
 libxcb-dri3-0 \
 libxcb-present0 \
 libxkbcommon-x11-0 \
 libx11-xcb1 \
 libxcb1 \
 gstreamer1.0-gl \
 x11-utils \
 patchelf \
 mesa-utils \
 xauth \
 # Fontconfig and fonts
 fontconfig \
 fonts-liberation \
 && rm -rf /var/lib/apt/lists/*

RUN useradd -ms /bin/bash appuser
RUN mkdir -p /home/appuser/.local && chown -R appuser:appuser /home/appuser
RUN chown -R appuser:appuser /app

# Create X11 directory with correct permissions
RUN mkdir -p /tmp/.X11-unix && chmod 1777 /tmp/.X11-unix

FROM base_image AS dev_image
USER appuser
WORKDIR /app

# Install PyTorch dependencies
RUN pip install --user --no-cache-dir pip setuptools wheel --upgrade \
   && pip install --user torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu126

# Install PySide6
RUN pip install --user PySide6==6.7.0

FROM dev_image AS final_image
USER root

COPY --chown=appuser:appuser . /app/
RUN ls -la /app
USER appuser

RUN pip install --no-cache-dir -e .[gui,linux,dev,art,llm,llm_weather,tts] && pip install --no-cache-dir -U timm

USER appuser

# Set environment variables for QT
ENV QT_DEBUG_PLUGINS=1
ENV QT_LOGGING_RULES="qt.qpa.*=true"
ENV QT_QPA_PLATFORM_PLUGIN_PATH=/home/appuser/.local/lib/python3.10/site-packages/PySide6/Qt/plugins/platforms
ENV QT_QPA_PLATFORM=xcb

ENTRYPOINT ["entrypoint-dev.sh"]
CMD ["/bin/bash"]
