version: "3.6"
services:
  airunner_dev:
    container_name: airunner_dev
    build:
      context: ..
      dockerfile: package/Dockerfile-dev
    user: appuser
    environment:
      - DEV_ENV=1
      - AIRUNNER_ENVIRONMENT=dev
      - PYTORCH_CUDA_ALLOC_CONF=garbage_collection_threshold:0.9,max_split_size_mb:512
      - NUMBA_CACHE_DIR=/tmp/numba_cache
      - LD_LIBRARY_PATH=/usr/lib/python3.10:/usr/lib/x86_64-linux-gnu/:/usr/local/lib/:/usr/local/lib/python3.10:/usr/local/lib/python3.10/dist-packages
      - DISABLE_TELEMETRY=1
      - PYTHONUSERBASE=/home/appuser/.local
      - PYTHONPATH=/home/appuser/.local/lib/python3.10/site-packages:/app
      - PIP_USER=1
      - DISPLAY=:1
      - QT_DEBUG_PLUGINS=1
      - QT_QPA_PLATFORM=xcb
      - DEBIAN_FRONTEND=noninteractive
      - TZ=America/Denver
      - HOME=/home/appuser
      - PATH=/home/appuser/.local/bin:$PATH
    entrypoint: ["/app/package/entrypoint-dev.sh"]
    command: ["airunner"]
    volumes:
      - ../:/app:rw
      - /home/joe/Documents/airunner:/home/appuser/.airunner:rw
      - /home/joe/.local/share/airunner/data:/airunner_data:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    working_dir: /app
    runtime: nvidia
    ports:
      - "8000:8000"
    ipc: host
