name: Linux Build

on:
  workflow_dispatch:

env:
  DOCKER_IMAGE: ghcr.io/capsize-games/airunner/airunner:linux
  BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
  CR_PAT: ${{ secrets.CR_PAT }}
  CR_REPO: ${{ secrets.CR_REPO }}
  CR_USERNAME: ${{ secrets.CR_USERNAME }}

jobs:
  buildDocker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file windows.Dockerfile --tag ghcr.io/capsize-games/airunner/airunner:linux
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Push Docker image to Container Registry
        run: docker push ghcr.io/capsize-games/airunner/airunner:linux
  buildLinux:
    needs: buildDocker
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Pull docker image
        run: |
          docker pull $DOCKER_IMAGE
      - name: Build Linux
        run: |
          docker run --rm \
            -e BUTLER_API_KEY=${{ secrets.BUTLER_API_KEY }} \
            -e ITCHIO_USERNAME=${{ secrets.ITCHIO_USERNAME }} \
            -e DEV_ENV=0 \
            -e AIRUNNER_ENVIRONMENT=prod \
            -e AIRUNNER_OS=linux \
            -e PYTORCH_CUDA_ALLOC_CONF=garbage_collection_threshold:0.9,max_split_size_mb:512 \
            -e NUMBA_CACHE_DIR=/tmp/numba_cache \
            -e DISABLE_TELEMETRY=1 \
            -e TCL_LIBDIR_PATH=/usr/lib/x86_64-linux-gnu/ \
            -e TK_LIBDIR_PATH=/usr/lib/x86_64-linux-gnu/ \
            -v $(pwd)/dist:/app/dist \
            ghcr.io/capsize-games/airunner/airunner:linux bash build.sh
