name: Linux Build

on:
  release:
    types: [ published ]
  workflow_dispatch:

env:
  DOCKER_IMAGE: ghcr.io/capsize-games/airunner/airunner:linux
  WORKING_HOME: ${{ github.workspace }}

jobs:
  buildLinux:
    runs-on: self-hosted
    steps:
      - name: Create WORKING_HOME directory
        run: mkdir -p ${{ env.WORKING_HOME }}
        
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: ${{ env.WORKING_HOME }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Pull docker image
        run: |
          docker pull $DOCKER_IMAGE

      - name: Create required directories
        run: |
          mkdir -p ${{ github.workspace }}/.local/share/airunner
          mkdir -p ${{ github.workspace }}/.local/share/airunner/data
          mkdir -p ${{ github.workspace }}/.local/share/airunner/torch/hub
          mkdir -p ${{ github.workspace }}/.local/share/airunner/python

      - name: Set PYTHONUSERBASE
        run: |
          export PYTHONUSERBASE=${{ github.workspace }}/.local/share/airunner/python
          mkdir -p $PYTHONUSERBASE

      - name: Build Linux
        run: |
          python3 src/airunner/bin/docker_wrapper.py linuxbuild-prod
