name: PyPi

on:
  release:
    types: [ published ]
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.10'

jobs:
  buildAndDeployPyPi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for tags and versioning
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build wheel twine
      
      - name: Build package
        run: python -m build
      
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: true
      
      - name: Upload package artifacts
        uses: actions/upload-artifact@v4
        with:
          name: airunner-pypi-dist
          path: dist/
          retention-days: 7
