name: Trigger build-and-deploy workflow

on:
  release:
    types: [created]
    branches:
      - main

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger build-and-deploy workflow
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.CAPSIZE_GAMES_ACCESS_TOKEN }}
          script: |
            const response = await fetch('https://api.github.com/repos/w4ffl35/aibuilder/dispatches', {
              method: 'POST',
              headers: {
                'Authorization': `Bearer ${{ secrets.W4FFL35_ACCESS_TOKEN }}`,
                'Accept': 'application/vnd.github.everest-preview+json',
                'Content-Type': 'application/json'
              },
              body: JSON.stringify({
                event_type: 'build-and-deploy',
                client_payload: {
                  release_tag: '${{ github.ref }}'
                }
              })
            });
            console.log(await response.text());
