name: Build

on:
  release:
    types: [ published ]
  workflow_dispatch:

env:
  DOCKER_IMAGE: ghcr.io/capsize-games/airunner/airunner:linux
  BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
  CR_PAT: ${{ secrets.CR_PAT }}
  CR_REPO: ${{ secrets.CR_REPO }}
  CR_USERNAME: ${{ secrets.CR_USERNAME }}

jobs:
  buildLinux:
    runs-on: ghcr.io/capsize-games/airunner/airunner:linux
    steps:
      - name: Build Linux
        run: bash /app/build.sh
  buildWindows:
    runs-on: ghcr.io/capsize-games/airunner/airunner:linux
    steps:
      - name: Build for Windows
        run: bash wine64 Z:\\app\\build.windows.cmd

