name: Run airunner on Linux

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  DOCKER_IMAGE: ghcr.io/capsize-games/airunner/airunner:linux
  BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}
  CR_PAT: ${{ secrets.CR_PAT }}
  CR_REPO: ${{ secrets.CR_REPO }}
  CR_USERNAME: ${{ secrets.CR_USERNAME }}

jobs:
  run-airunner:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Run airunner on Linux
        run: |
          docker pull $DOCKER_IMAGE
          docker run --rm \
            -e BUTLER_API_KEY=${{ secrets.BUTLER_API_KEY }} \
            -e ITCHIO_USERNAME=${{ secrets.ITCHIO_USERNAME }} \
            -e DEV_ENV=0 \
            -e AIRUNNER_ENVIRONMENT=prod \
            -e AIRUNNER_OS=linux \
            -e PYTORCH_CUDA_ALLOC_CONF=garbage_collection_threshold:0.9,max_split_size_mb:512 \
            -e NUMBA_CACHE_DIR=/tmp/numba_cache \
            -e LD_LIBRARY_PATH=/usr/lib/python3.10:/usr/lib/x86_64-linux-gnu/:/usr/local/lib/:/usr/local/lib/python3.10:/usr/local/lib/python3.10/dist-packages \
            -e DISABLE_TELEMETRY=1 \
            -e TCL_LIBDIR_PATH=/usr/lib/x86_64-linux-gnu/ \
            -e TK_LIBDIR_PATH=/usr/lib/x86_64-linux-gnu/ \
            ghcr.io/capsize-games/airunner/airunner:linux bash build.sh
